// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as template$0 from "../template/models.js";

/**
 * FormView is the Vue-facing payload returned by BuildView and SaveValues.
 * Vue iterates Template.Fields in order and consults LoopGroups to know
 * when a slice of fields belongs to a loopstart/loopstop block. Values
 * is keyed by field.key; loop keys hold []map[string]any (one entry
 * per item), with inner field values keyed inside.
 */
export class FormView {
    "template": template$0.Template | null;
    "values": { [_ in string]?: any };
    "meta": storage$0.FormMeta;
    "loop_groups": LoopGroup[];
    "datafile": string;
    "saved": boolean;

    /** Creates a new FormView instance. */
    constructor($$source: Partial<FormView> = {}) {
        if (!("template" in $$source)) {
            this["template"] = null;
        }
        if (!("values" in $$source)) {
            this["values"] = {};
        }
        if (!("meta" in $$source)) {
            this["meta"] = (new storage$0.FormMeta());
        }
        if (!("loop_groups" in $$source)) {
            this["loop_groups"] = [];
        }
        if (!("datafile" in $$source)) {
            this["datafile"] = "";
        }
        if (!("saved" in $$source)) {
            this["saved"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FormView instance from a string or object.
     */
    static createFrom($$source: any = {}): FormView {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("template" in $$parsedSource) {
            $$parsedSource["template"] = $$createField0_0($$parsedSource["template"]);
        }
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField1_0($$parsedSource["values"]);
        }
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField2_0($$parsedSource["meta"]);
        }
        if ("loop_groups" in $$parsedSource) {
            $$parsedSource["loop_groups"] = $$createField3_0($$parsedSource["loop_groups"]);
        }
        return new FormView($$parsedSource as Partial<FormView>);
    }
}

/**
 * LoopGroup is one precomputed loopstart/loopstop pair. Vue uses
 * StartIndex/StopIndex to slice into Template.Fields and DefaultCollapsed
 * for the initial UI state. SummaryFieldKey is the field key whose
 * value is shown in the loop-item header when the item is collapsed
 * (mirrors loopstart.summary_field).
 */
export class LoopGroup {
    "key": string;
    "start_index": number;
    "stop_index": number;
    "depth": number;
    "summary_field_key": string;
    "default_collapsed": boolean;

    /** Creates a new LoopGroup instance. */
    constructor($$source: Partial<LoopGroup> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("start_index" in $$source)) {
            this["start_index"] = 0;
        }
        if (!("stop_index" in $$source)) {
            this["stop_index"] = 0;
        }
        if (!("depth" in $$source)) {
            this["depth"] = 0;
        }
        if (!("summary_field_key" in $$source)) {
            this["summary_field_key"] = "";
        }
        if (!("default_collapsed" in $$source)) {
            this["default_collapsed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoopGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): LoopGroup {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoopGroup($$parsedSource as Partial<LoopGroup>);
    }
}

/**
 * SavePayload is what Vue sends to SaveValues. Datafile may be empty
 * for never-persisted forms - the caller (UI) is expected to gather
 * a filename from the user (mirrors the original New-entry dialog).
 */
export class SavePayload {
    "datafile": string;
    "values": { [_ in string]?: any };
    "meta": storage$0.FormMeta;

    /** Creates a new SavePayload instance. */
    constructor($$source: Partial<SavePayload> = {}) {
        if (!("datafile" in $$source)) {
            this["datafile"] = "";
        }
        if (!("values" in $$source)) {
            this["values"] = {};
        }
        if (!("meta" in $$source)) {
            this["meta"] = (new storage$0.FormMeta());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavePayload instance from a string or object.
     */
    static createFrom($$source: any = {}): SavePayload {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField1_0($$parsedSource["values"]);
        }
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField2_0($$parsedSource["meta"]);
        }
        return new SavePayload($$parsedSource as Partial<SavePayload>);
    }
}

// Private type creation functions
const $$createType0 = template$0.Template.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = storage$0.FormMeta.createFrom;
const $$createType4 = LoopGroup.createFrom;
const $$createType5 = $Create.Array($$createType4);
