// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound facade. Its surface is the single
 * entry point Vue uses for form ops; template/storage services stay
 * available for list/template-side work.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BuildView returns the prepared FormView for a (template, datafile)
 * pair. datafile == "" produces an unsaved view with defaults.
 */
export function BuildView(templateName: string, datafile: string): $CancellablePromise<$models.FormView | null> {
    return $Call.ByID(2643711629, templateName, datafile).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CopyForm duplicates sourceDatafile into newDatafile with a fresh identity (new
 * GUID, new Created/Updated), keeping every field value, tag and facet. Returns
 * the saved view of the new record, ready for the editor to open.
 */
export function CopyForm(templateName: string, sourceDatafile: string, newDatafile: string): $CancellablePromise<$models.FormView | null> {
    return $Call.ByID(781894739, templateName, sourceDatafile, newDatafile).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DedupFieldValue fetches a list/table field from the saved record, removes
 * duplicates, and returns the result (no persistence). column is the table
 * column key whose value marks a duplicate row (empty = first column); ignored
 * for list fields.
 */
export function DedupFieldValue(templateName: string, datafile: string, fieldKey: string, column: string): $CancellablePromise<any> {
    return $Call.ByID(1008232297, templateName, datafile, fieldKey, column);
}

/**
 * DeleteForm removes the meta.json. Missing is a no-op.
 */
export function DeleteForm(templateName: string, datafile: string): $CancellablePromise<void> {
    return $Call.ByID(3502554773, templateName, datafile);
}

/**
 * EnsureFormDir creates the per-template storage folder. Vue calls
 * this on first list against a freshly-created template.
 */
export function EnsureFormDir(templateName: string): $CancellablePromise<void> {
    return $Call.ByID(1936801635, templateName);
}

/**
 * ImportRelations is the relations pass of a multipass import: given a parsed
 * sheet (headers + rows) and the two id columns, the backend extracts the
 * {from,to} pairs and links them through fieldKey, writing the api value onto
 * each source record so the reference-edge syncer mirrors the edges. See
 * Manager.ImportRelationsFromColumns.
 */
export function ImportRelations(sourceTemplate: string, fieldKey: string, fromColumn: string, toColumn: string, headers: string[], rows: string[][]): $CancellablePromise<$models.ImportRelationResult> {
    return $Call.ByID(247265434, sourceTemplate, fieldKey, fromColumn, toColumn, headers, rows).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListForms returns the per-template form summaries (title + meta +
 * expression-bearing fields for the sidebar).
 */
export function ListForms(templateName: string): $CancellablePromise<storage$0.FormSummary[]> {
    return $Call.ByID(1337737659, templateName).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * NormalizeSequence re-spreads the collection to clean step spacing (the
 * "Normalize" action). See Manager.NormalizeSequence.
 */
export function NormalizeSequence(templateName: string): $CancellablePromise<$models.ReorderResult> {
    return $Call.ByID(1224904886, templateName).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * RelationFields returns the source template's api fields, the relation targets
 * the relations-import mode can fill. The dialog's relation picker reads this
 * instead of filtering the template client-side.
 */
export function RelationFields(sourceTemplate: string): $CancellablePromise<$models.RelationField[]> {
    return $Call.ByID(336515629, sourceTemplate).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ReorderSequence moves one record to its new position (drag-to-reorder),
 * writing only the moved record's sequence value unless the gaps force a
 * renumber. See Manager.ReorderSequence.
 */
export function ReorderSequence(templateName: string, movedDatafile: string, orderedDatafiles: string[]): $CancellablePromise<$models.ReorderResult> {
    return $Call.ByID(1423545710, templateName, movedDatafile, orderedDatafiles).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SaveValues persists the form (storage.Sanitize handles the heavy
 * lifting; this layer adds author injection from config, then
 * re-builds the view from disk).
 */
export function SaveValues(templateName: string, payload: $models.SavePayload): $CancellablePromise<$models.FormView | null> {
    return $Call.ByID(3432782407, templateName, payload).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SequenceOrder returns the collection's datafiles in sequence order, so the
 * studio list can render a presentation template as an ordered deck.
 */
export function SequenceOrder(templateName: string): $CancellablePromise<string[]> {
    return $Call.ByID(1461479659, templateName).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * SortFieldValue fetches a list/table field from the saved record, sorts it,
 * and returns the sorted value (no persistence: the frontend applies it and
 * the normal save writes it). column is the table column key (empty = first
 * column); direction is "asc" (default) or "desc". Ignored column for lists.
 */
export function SortFieldValue(templateName: string, datafile: string, fieldKey: string, column: string, direction: string): $CancellablePromise<any> {
    return $Call.ByID(2518961349, templateName, datafile, fieldKey, column, direction);
}

/**
 * SyncRelationsForTemplate back-fills every api field on the template from
 * existing relation edges (the "Synchronize from relations" utility), returning
 * the summed result. See Manager.SyncRelationsForTemplate. Idempotent.
 */
export function SyncRelationsForTemplate(template: string): $CancellablePromise<$models.ImportRelationResult> {
    return $Call.ByID(3884228353, template).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SyncRelationsToField back-fills an api field from the relation edges that
 * already exist for it (e.g. an inverse field added after the links were made),
 * writing each host record's target ids so field, edges, and graph agree. See
 * Manager.SyncRelationsToField. Idempotent.
 */
export function SyncRelationsToField(template: string, fieldKey: string): $CancellablePromise<$models.ImportRelationResult> {
    return $Call.ByID(3579787831, template, fieldKey).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.FormView.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ImportRelationResult.createFrom;
const $$createType3 = storage$0.FormSummary.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.ReorderResult.createFrom;
const $$createType6 = $models.RelationField.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($Create.Any);
