// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound facade. Its surface is the single
 * entry point Vue uses for form ops; template/storage services stay
 * available for list/template-side work.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BuildView returns the prepared FormView for a (template, datafile)
 * pair. datafile == "" produces an unsaved view with defaults.
 */
export function BuildView(templateName: string, datafile: string): $CancellablePromise<$models.FormView | null> {
    return $Call.ByID(2643711629, templateName, datafile).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteForm removes the meta.json. Missing is a no-op.
 */
export function DeleteForm(templateName: string, datafile: string): $CancellablePromise<void> {
    return $Call.ByID(3502554773, templateName, datafile);
}

/**
 * EnsureFormDir creates the per-template storage folder. Vue calls
 * this on first list against a freshly-created template.
 */
export function EnsureFormDir(templateName: string): $CancellablePromise<void> {
    return $Call.ByID(1936801635, templateName);
}

/**
 * ListForms returns the per-template form summaries (title + meta +
 * expression-bearing fields for the sidebar).
 */
export function ListForms(templateName: string): $CancellablePromise<storage$0.FormSummary[]> {
    return $Call.ByID(1337737659, templateName).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SaveValues persists the form (storage.Sanitize handles the heavy
 * lifting; this layer adds LaTeX coercion + author injection from
 * config, then re-builds the view from disk).
 */
export function SaveValues(templateName: string, payload: $models.SavePayload): $CancellablePromise<$models.FormView | null> {
    return $Call.ByID(3432782407, templateName, payload).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.FormView.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = storage$0.FormSummary.createFrom;
const $$createType3 = $Create.Array($$createType2);
