// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Bin buckets a date dimension; "" means no binning (group by raw value).
 */
export enum Bin {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    BinNone = "",
    BinYear = "year",
    BinMonth = "month",
    BinDay = "day",
};

/**
 * BranchGrid is one parent category and the child object drilling it (nil = a
 * leaf with no edge).
 */
export class BranchGrid {
    "branch": string;
    "child": Grid | null;

    /** Creates a new BranchGrid instance. */
    constructor($$source: Partial<BranchGrid> = {}) {
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("child" in $$source)) {
            this["child"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BranchGrid instance from a string or object.
     */
    static createFrom($$source: any = {}): BranchGrid {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("child" in $$parsedSource) {
            $$parsedSource["child"] = $$createField1_0($$parsedSource["child"]);
        }
        return new BranchGrid($$parsedSource as Partial<BranchGrid>);
    }
}

/**
 * CompositeEdgeOption is one branch of a parent and the child objects eligible
 * to drill it.
 */
export class CompositeEdgeOption {
    /**
     * a parent branch value (a child's eq-filter value on the base)
     */
    "branch": string;

    /**
     * names of eligible child objects
     */
    "children": string[];

    /** Creates a new CompositeEdgeOption instance. */
    constructor($$source: Partial<CompositeEdgeOption> = {}) {
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("children" in $$source)) {
            this["children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompositeEdgeOption instance from a string or object.
     */
    static createFrom($$source: any = {}): CompositeEdgeOption {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField1_0($$parsedSource["children"]);
        }
        return new CompositeEdgeOption($$parsedSource as Partial<CompositeEdgeOption>);
    }
}

/**
 * CompositeEdgeSpec maps one parent branch value to the child object that
 * drills it.
 */
export class CompositeEdgeSpec {
    "branch": string;
    "child": string;

    /** Creates a new CompositeEdgeSpec instance. */
    constructor($$source: Partial<CompositeEdgeSpec> = {}) {
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("child" in $$source)) {
            this["child"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompositeEdgeSpec instance from a string or object.
     */
    static createFrom($$source: any = {}): CompositeEdgeSpec {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CompositeEdgeSpec($$parsedSource as Partial<CompositeEdgeSpec>);
    }
}

/**
 * CompositeGrid is the evaluated composite: the parent rank-1 grid plus, in
 * the parent's axis order, the child grid that drills each category (nil for a
 * solid leaf).
 */
export class CompositeGrid {
    "parent": Grid | null;
    "branches": BranchGrid[];

    /** Creates a new CompositeGrid instance. */
    constructor($$source: Partial<CompositeGrid> = {}) {
        if (!("parent" in $$source)) {
            this["parent"] = null;
        }
        if (!("branches" in $$source)) {
            this["branches"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompositeGrid instance from a string or object.
     */
    static createFrom($$source: any = {}): CompositeGrid {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("parent" in $$parsedSource) {
            $$parsedSource["parent"] = $$createField0_0($$parsedSource["parent"]);
        }
        if ("branches" in $$parsedSource) {
            $$parsedSource["branches"] = $$createField1_0($$parsedSource["branches"]);
        }
        return new CompositeGrid($$parsedSource as Partial<CompositeGrid>);
    }
}

/**
 * CompositeOption is one composite the builder may offer: a rank-1 parent
 * object and, per branch, the existing child objects that can drill it (those
 * whose DSL already filters the parent base to that branch value). The frontend
 * renders only these, so an author can only wire links the engine will accept.
 * Backend steers; the structure is the gate.
 */
export class CompositeOption {
    /**
     * parent object name
     */
    "parent": string;

    /**
     * the base (group-by) source the children must filter
     */
    "base": string;
    "edges": CompositeEdgeOption[];

    /** Creates a new CompositeOption instance. */
    constructor($$source: Partial<CompositeOption> = {}) {
        if (!("parent" in $$source)) {
            this["parent"] = "";
        }
        if (!("base" in $$source)) {
            this["base"] = "";
        }
        if (!("edges" in $$source)) {
            this["edges"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompositeOption instance from a string or object.
     */
    static createFrom($$source: any = {}): CompositeOption {
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField2_0($$parsedSource["edges"]);
        }
        return new CompositeOption($$parsedSource as Partial<CompositeOption>);
    }
}

/**
 * CompositeSpec is the stored form of a composite (hop route): a parent
 * object name plus per-branch child object names. Resolved against the
 * template's other objects by ResolveComposite. Kept name-based (not
 * inlined configs) so the parent and children stay single sources of truth.
 */
export class CompositeSpec {
    "parent": string;
    "edges": CompositeEdgeSpec[];

    /** Creates a new CompositeSpec instance. */
    constructor($$source: Partial<CompositeSpec> = {}) {
        if (!("parent" in $$source)) {
            this["parent"] = "";
        }
        if (!("edges" in $$source)) {
            this["edges"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompositeSpec instance from a string or object.
     */
    static createFrom($$source: any = {}): CompositeSpec {
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField1_0($$parsedSource["edges"]);
        }
        return new CompositeSpec($$parsedSource as Partial<CompositeSpec>);
    }
}

/**
 * Dimension is one group-by axis: a source, optionally date-binned, and
 * optionally capped to its Top-N categories (ranked by the first measure,
 * the tail dropped). Top 0 means all categories; valid Top is 1..20.
 */
export class Dimension {
    "Source": SourceRef;
    "Bin": Bin;
    "Top": number;

    /** Creates a new Dimension instance. */
    constructor($$source: Partial<Dimension> = {}) {
        if (!("Source" in $$source)) {
            this["Source"] = (new SourceRef());
        }
        if (!("Bin" in $$source)) {
            this["Bin"] = Bin.$zero;
        }
        if (!("Top" in $$source)) {
            this["Top"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Dimension instance from a string or object.
     */
    static createFrom($$source: any = {}): Dimension {
        const $$createField0_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Source" in $$parsedSource) {
            $$parsedSource["Source"] = $$createField0_0($$parsedSource["Source"]);
        }
        return new Dimension($$parsedSource as Partial<Dimension>);
    }
}

/**
 * Filter scopes which rows count, before grouping: keep only those where
 * Source <op> Value holds. AND-chained. Equality ops match the text
 * value; comparison ops match the numeric value.
 */
export class Filter {
    "Source": SourceRef;
    "Op": FilterOp;
    "Value": string;

    /** Creates a new Filter instance. */
    constructor($$source: Partial<Filter> = {}) {
        if (!("Source" in $$source)) {
            this["Source"] = (new SourceRef());
        }
        if (!("Op" in $$source)) {
            this["Op"] = FilterOp.$zero;
        }
        if (!("Value" in $$source)) {
            this["Value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Filter instance from a string or object.
     */
    static createFrom($$source: any = {}): Filter {
        const $$createField0_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Source" in $$parsedSource) {
            $$parsedSource["Source"] = $$createField0_0($$parsedSource["Source"]);
        }
        return new Filter($$parsedSource as Partial<Filter>);
    }
}

/**
 * FilterOp is a where-clause comparison operator.
 */
export enum FilterOp {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FilterEq = "eq",
    FilterNe = "ne",
    FilterLt = "lt",
    FilterLe = "le",
    FilterGt = "gt",
    FilterGe = "ge",
};

/**
 * FilterOpDescriptor describes a where-clause operator: Numeric is true
 * when its value is a number (comparison) rather than a text literal
 * (equality). The builder uses this to render the value input and to
 * offer comparisons only on numeric sources.
 */
export class FilterOpDescriptor {
    "op": FilterOp;
    "numeric": boolean;

    /** Creates a new FilterOpDescriptor instance. */
    constructor($$source: Partial<FilterOpDescriptor> = {}) {
        if (!("op" in $$source)) {
            this["op"] = FilterOp.$zero;
        }
        if (!("numeric" in $$source)) {
            this["numeric"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilterOpDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): FilterOpDescriptor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FilterOpDescriptor($$parsedSource as Partial<FilterOpDescriptor>);
    }
}

/**
 * Grid is the rank-N output of evaluating a StatConfig: one Axis per
 * dimension (in declared order), the measure labels, and sparse Cells
 * (a coordinate tuple into the axes plus one value per measure). Total is
 * the form-count denominator for percentages. No dimensions => one cell
 * with empty coords (a rank-0 scalar).
 */
export class Grid {
    "axes": GridAxis[];
    "measures": string[];
    "cells": GridCell[];
    "total": number;

    /** Creates a new Grid instance. */
    constructor($$source: Partial<Grid> = {}) {
        if (!("axes" in $$source)) {
            this["axes"] = [];
        }
        if (!("measures" in $$source)) {
            this["measures"] = [];
        }
        if (!("cells" in $$source)) {
            this["cells"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Grid instance from a string or object.
     */
    static createFrom($$source: any = {}): Grid {
        const $$createField0_0 = $$createType11;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("axes" in $$parsedSource) {
            $$parsedSource["axes"] = $$createField0_0($$parsedSource["axes"]);
        }
        if ("measures" in $$parsedSource) {
            $$parsedSource["measures"] = $$createField1_0($$parsedSource["measures"]);
        }
        if ("cells" in $$parsedSource) {
            $$parsedSource["cells"] = $$createField2_0($$parsedSource["cells"]);
        }
        return new Grid($$parsedSource as Partial<Grid>);
    }
}

/**
 * GridAxis is one dimension: a source label and its distinct category
 * ticks (sorted for stable output).
 */
export class GridAxis {
    "source": string;
    "labels": string[];

    /** Creates a new GridAxis instance. */
    constructor($$source: Partial<GridAxis> = {}) {
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("labels" in $$source)) {
            this["labels"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GridAxis instance from a string or object.
     */
    static createFrom($$source: any = {}): GridAxis {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField1_0($$parsedSource["labels"]);
        }
        return new GridAxis($$parsedSource as Partial<GridAxis>);
    }
}

/**
 * GridCell is one populated coordinate: indices into each axis, the value of
 * each measure (aligned to Grid.Measures), and each value's share (0-100) of
 * that measure's total across the grid. Pct is computed server-side so every
 * renderer reads the same figure instead of recomputing it.
 */
export class GridCell {
    "coords": number[];
    "values": number[];
    "pct": number[];

    /** Creates a new GridCell instance. */
    constructor($$source: Partial<GridCell> = {}) {
        if (!("coords" in $$source)) {
            this["coords"] = [];
        }
        if (!("values" in $$source)) {
            this["values"] = [];
        }
        if (!("pct" in $$source)) {
            this["pct"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GridCell instance from a string or object.
     */
    static createFrom($$source: any = {}): GridCell {
        const $$createField0_0 = $$createType14;
        const $$createField1_0 = $$createType15;
        const $$createField2_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("coords" in $$parsedSource) {
            $$parsedSource["coords"] = $$createField0_0($$parsedSource["coords"]);
        }
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField1_0($$parsedSource["values"]);
        }
        if ("pct" in $$parsedSource) {
            $$parsedSource["pct"] = $$createField2_0($$parsedSource["pct"]);
        }
        return new GridCell($$parsedSource as Partial<GridCell>);
    }
}

/**
 * Measure is one cell value layer: count() (rows, no source), records()
 * (distinct contributing forms, no source), a reduce over a numeric field
 * source, or percentile(source, p). records() differs from count() only on a
 * fanned-out (table-column) source, where one form yields many rows: count()
 * tallies the rows, records() tallies the distinct forms.
 */
export class Measure {
    "Op": MeasureOp;

    /**
     * nil only for count
     */
    "Source": SourceRef | null;

    /**
     * percentile p; nil otherwise
     */
    "Arg": number | null;

    /** Creates a new Measure instance. */
    constructor($$source: Partial<Measure> = {}) {
        if (!("Op" in $$source)) {
            this["Op"] = MeasureOp.$zero;
        }
        if (!("Source" in $$source)) {
            this["Source"] = null;
        }
        if (!("Arg" in $$source)) {
            this["Arg"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Measure instance from a string or object.
     */
    static createFrom($$source: any = {}): Measure {
        const $$createField1_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Source" in $$parsedSource) {
            $$parsedSource["Source"] = $$createField1_0($$parsedSource["Source"]);
        }
        return new Measure($$parsedSource as Partial<Measure>);
    }
}

/**
 * MeasureOp is the aggregation a measure applies to each cell.
 */
export enum MeasureOp {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OpCount = "count",
    OpRecords = "records",
    OpSum = "sum",
    OpAvg = "avg",
    OpMin = "min",
    OpMax = "max",
    OpMedian = "median",
    OpStddev = "stddev",
    OpPercentile = "percentile",
};

/**
 * MeasureOpDescriptor describes one measure operation: the op id plus
 * whether it needs a numeric field source and a numeric argument.
 */
export class MeasureOpDescriptor {
    "op": MeasureOp;
    "needs_source": boolean;
    "needs_arg": boolean;

    /** Creates a new MeasureOpDescriptor instance. */
    constructor($$source: Partial<MeasureOpDescriptor> = {}) {
        if (!("op" in $$source)) {
            this["op"] = MeasureOp.$zero;
        }
        if (!("needs_source" in $$source)) {
            this["needs_source"] = false;
        }
        if (!("needs_arg" in $$source)) {
            this["needs_arg"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MeasureOpDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): MeasureOpDescriptor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MeasureOpDescriptor($$parsedSource as Partial<MeasureOpDescriptor>);
    }
}

/**
 * PercentBase selects the denominator the engine uses for each cell's
 * computed percentage. It is an authored setting on the object (the builder
 * sets it, the DSL carries it), not a render-time choice.
 */
export enum PercentBase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * PctDistribution: share of the measure's total across this grid's cells
     * (categories sum to 100%). The default; an empty PercentBase means this.
     */
    PctDistribution = "distribution",

    /**
     * PctForms: share of all forms (grid Total), so e.g. partially-filled or
     * multi-value distributions read against the record count.
     */
    PctForms = "forms",

    /**
     * PctNone: no percentage computed.
     */
    PctNone = "none",
};

/**
 * SourceKind distinguishes a field source from a facet source.
 */
export enum SourceKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SourceField = "field",
    SourceFacet = "facet",
};

/**
 * SourceRef references a statistical source by key: a field (optionally a
 * table column by its option value-key) or a facet. Column is "" for a
 * scalar field or a facet.
 */
export class SourceRef {
    "Kind": SourceKind;
    "Key": string;
    "Column": string;

    /** Creates a new SourceRef instance. */
    constructor($$source: Partial<SourceRef> = {}) {
        if (!("Kind" in $$source)) {
            this["Kind"] = SourceKind.$zero;
        }
        if (!("Key" in $$source)) {
            this["Key"] = "";
        }
        if (!("Column" in $$source)) {
            this["Column"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceRef instance from a string or object.
     */
    static createFrom($$source: any = {}): SourceRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceRef($$parsedSource as Partial<SourceRef>);
    }
}

/**
 * StatConfig is the parsed statistical DSL: one or more measures (cell
 * value layers) over zero or more dimensions (axes), optionally scoped by
 * AND-ed equality filters, with a percentage base. No dimensions => a rank-0
 * scalar; one => a 1D array; two => a 2D matrix; and so on.
 * 
 * Named StatConfig (not Config) to stay unambiguous inside the stat
 * package, which already carries Result/Series.
 */
export class StatConfig {
    "Measures": Measure[];
    "Dimensions": Dimension[];
    "Filters": Filter[];

    /**
     * "" means PctDistribution
     */
    "Percent": PercentBase;

    /** Creates a new StatConfig instance. */
    constructor($$source: Partial<StatConfig> = {}) {
        if (!("Measures" in $$source)) {
            this["Measures"] = [];
        }
        if (!("Dimensions" in $$source)) {
            this["Dimensions"] = [];
        }
        if (!("Filters" in $$source)) {
            this["Filters"] = [];
        }
        if (!("Percent" in $$source)) {
            this["Percent"] = PercentBase.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): StatConfig {
        const $$createField0_0 = $$createType18;
        const $$createField1_0 = $$createType20;
        const $$createField2_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Measures" in $$parsedSource) {
            $$parsedSource["Measures"] = $$createField0_0($$parsedSource["Measures"]);
        }
        if ("Dimensions" in $$parsedSource) {
            $$parsedSource["Dimensions"] = $$createField1_0($$parsedSource["Dimensions"]);
        }
        if ("Filters" in $$parsedSource) {
            $$parsedSource["Filters"] = $$createField2_0($$parsedSource["Filters"]);
        }
        return new StatConfig($$parsedSource as Partial<StatConfig>);
    }
}

/**
 * StatObject is a named statistical object defined on a template: its
 * identifier, optional human label, and either a DSL (a plain object the
 * engine evaluates) or a Composite spec (a hop route referencing other
 * objects by name). Exactly one of DSL / Composite is set. Mirrors
 * template.Statistic without the template dependency, so the catalog can
 * travel to Vue and Lua via the Service.
 */
export class StatObject {
    "name": string;
    "label"?: string;
    "dsl": string;
    "composite"?: CompositeSpec | null;

    /** Creates a new StatObject instance. */
    constructor($$source: Partial<StatObject> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("dsl" in $$source)) {
            this["dsl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatObject instance from a string or object.
     */
    static createFrom($$source: any = {}): StatObject {
        const $$createField3_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("composite" in $$parsedSource) {
            $$parsedSource["composite"] = $$createField3_0($$parsedSource["composite"]);
        }
        return new StatObject($$parsedSource as Partial<StatObject>);
    }
}

// Private type creation functions
const $$createType0 = Grid.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = BranchGrid.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = CompositeEdgeOption.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = CompositeEdgeSpec.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = SourceRef.createFrom;
const $$createType10 = GridAxis.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = GridCell.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Array($Create.Any);
const $$createType15 = $Create.Array($Create.Any);
const $$createType16 = $Create.Nullable($$createType9);
const $$createType17 = Measure.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = Dimension.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = Filter.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = CompositeSpec.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
