// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Bin buckets a date dimension; "" means no binning (group by raw value).
 */
export enum Bin {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    BinNone = "",
    BinYear = "year",
    BinMonth = "month",
    BinDay = "day",
};

/**
 * Dimension is one group-by axis: a source, optionally date-binned, and
 * optionally capped to its Top-N categories (ranked by the first measure,
 * the tail dropped). Top 0 means all categories; valid Top is 1..20.
 */
export class Dimension {
    "Source": SourceRef;
    "Bin": Bin;
    "Top": number;

    /** Creates a new Dimension instance. */
    constructor($$source: Partial<Dimension> = {}) {
        if (!("Source" in $$source)) {
            this["Source"] = (new SourceRef());
        }
        if (!("Bin" in $$source)) {
            this["Bin"] = Bin.$zero;
        }
        if (!("Top" in $$source)) {
            this["Top"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Dimension instance from a string or object.
     */
    static createFrom($$source: any = {}): Dimension {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Source" in $$parsedSource) {
            $$parsedSource["Source"] = $$createField0_0($$parsedSource["Source"]);
        }
        return new Dimension($$parsedSource as Partial<Dimension>);
    }
}

/**
 * Filter scopes which rows count, before grouping: keep only those where
 * Source <op> Value holds. AND-chained. Equality ops match the text
 * value; comparison ops match the numeric value.
 */
export class Filter {
    "Source": SourceRef;
    "Op": FilterOp;
    "Value": string;

    /** Creates a new Filter instance. */
    constructor($$source: Partial<Filter> = {}) {
        if (!("Source" in $$source)) {
            this["Source"] = (new SourceRef());
        }
        if (!("Op" in $$source)) {
            this["Op"] = FilterOp.$zero;
        }
        if (!("Value" in $$source)) {
            this["Value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Filter instance from a string or object.
     */
    static createFrom($$source: any = {}): Filter {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Source" in $$parsedSource) {
            $$parsedSource["Source"] = $$createField0_0($$parsedSource["Source"]);
        }
        return new Filter($$parsedSource as Partial<Filter>);
    }
}

/**
 * FilterOp is a where-clause comparison operator.
 */
export enum FilterOp {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FilterEq = "eq",
    FilterNe = "ne",
    FilterLt = "lt",
    FilterLe = "le",
    FilterGt = "gt",
    FilterGe = "ge",
};

/**
 * FilterOpDescriptor describes a where-clause operator: Numeric is true
 * when its value is a number (comparison) rather than a text literal
 * (equality). The builder uses this to render the value input and to
 * offer comparisons only on numeric sources.
 */
export class FilterOpDescriptor {
    "op": FilterOp;
    "numeric": boolean;

    /** Creates a new FilterOpDescriptor instance. */
    constructor($$source: Partial<FilterOpDescriptor> = {}) {
        if (!("op" in $$source)) {
            this["op"] = FilterOp.$zero;
        }
        if (!("numeric" in $$source)) {
            this["numeric"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilterOpDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): FilterOpDescriptor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FilterOpDescriptor($$parsedSource as Partial<FilterOpDescriptor>);
    }
}

/**
 * Grid is the rank-N output of evaluating a StatConfig: one Axis per
 * dimension (in declared order), the measure labels, and sparse Cells
 * (a coordinate tuple into the axes plus one value per measure). Total is
 * the form-count denominator for percentages. No dimensions => one cell
 * with empty coords (a rank-0 scalar).
 */
export class Grid {
    "axes": GridAxis[];
    "measures": string[];
    "cells": GridCell[];
    "total": number;

    /** Creates a new Grid instance. */
    constructor($$source: Partial<Grid> = {}) {
        if (!("axes" in $$source)) {
            this["axes"] = [];
        }
        if (!("measures" in $$source)) {
            this["measures"] = [];
        }
        if (!("cells" in $$source)) {
            this["cells"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Grid instance from a string or object.
     */
    static createFrom($$source: any = {}): Grid {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("axes" in $$parsedSource) {
            $$parsedSource["axes"] = $$createField0_0($$parsedSource["axes"]);
        }
        if ("measures" in $$parsedSource) {
            $$parsedSource["measures"] = $$createField1_0($$parsedSource["measures"]);
        }
        if ("cells" in $$parsedSource) {
            $$parsedSource["cells"] = $$createField2_0($$parsedSource["cells"]);
        }
        return new Grid($$parsedSource as Partial<Grid>);
    }
}

/**
 * GridAxis is one dimension: a source label and its distinct category
 * ticks (sorted for stable output).
 */
export class GridAxis {
    "source": string;
    "labels": string[];

    /** Creates a new GridAxis instance. */
    constructor($$source: Partial<GridAxis> = {}) {
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("labels" in $$source)) {
            this["labels"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GridAxis instance from a string or object.
     */
    static createFrom($$source: any = {}): GridAxis {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField1_0($$parsedSource["labels"]);
        }
        return new GridAxis($$parsedSource as Partial<GridAxis>);
    }
}

/**
 * GridCell is one populated coordinate: indices into each axis and the
 * value of each measure (aligned to Grid.Measures).
 */
export class GridCell {
    "coords": number[];
    "values": number[];

    /** Creates a new GridCell instance. */
    constructor($$source: Partial<GridCell> = {}) {
        if (!("coords" in $$source)) {
            this["coords"] = [];
        }
        if (!("values" in $$source)) {
            this["values"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GridCell instance from a string or object.
     */
    static createFrom($$source: any = {}): GridCell {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("coords" in $$parsedSource) {
            $$parsedSource["coords"] = $$createField0_0($$parsedSource["coords"]);
        }
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField1_0($$parsedSource["values"]);
        }
        return new GridCell($$parsedSource as Partial<GridCell>);
    }
}

/**
 * Measure is one cell value layer: count() (no source), a reduce over a
 * numeric field source, or percentile(source, p).
 */
export class Measure {
    "Op": MeasureOp;

    /**
     * nil only for count
     */
    "Source": SourceRef | null;

    /**
     * percentile p; nil otherwise
     */
    "Arg": number | null;

    /** Creates a new Measure instance. */
    constructor($$source: Partial<Measure> = {}) {
        if (!("Op" in $$source)) {
            this["Op"] = MeasureOp.$zero;
        }
        if (!("Source" in $$source)) {
            this["Source"] = null;
        }
        if (!("Arg" in $$source)) {
            this["Arg"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Measure instance from a string or object.
     */
    static createFrom($$source: any = {}): Measure {
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Source" in $$parsedSource) {
            $$parsedSource["Source"] = $$createField1_0($$parsedSource["Source"]);
        }
        return new Measure($$parsedSource as Partial<Measure>);
    }
}

/**
 * MeasureOp is the aggregation a measure applies to each cell.
 */
export enum MeasureOp {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OpCount = "count",
    OpSum = "sum",
    OpAvg = "avg",
    OpMin = "min",
    OpMax = "max",
    OpMedian = "median",
    OpStddev = "stddev",
    OpPercentile = "percentile",
};

/**
 * MeasureOpDescriptor describes one measure operation: the op id plus
 * whether it needs a numeric field source and a numeric argument.
 */
export class MeasureOpDescriptor {
    "op": MeasureOp;
    "needs_source": boolean;
    "needs_arg": boolean;

    /** Creates a new MeasureOpDescriptor instance. */
    constructor($$source: Partial<MeasureOpDescriptor> = {}) {
        if (!("op" in $$source)) {
            this["op"] = MeasureOp.$zero;
        }
        if (!("needs_source" in $$source)) {
            this["needs_source"] = false;
        }
        if (!("needs_arg" in $$source)) {
            this["needs_arg"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MeasureOpDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): MeasureOpDescriptor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MeasureOpDescriptor($$parsedSource as Partial<MeasureOpDescriptor>);
    }
}

/**
 * Result is the chart-neutral output of every stat query. Categories
 * are the x-axis labels; Series are the aligned value rows; Scalars
 * carries single-number stats that don't fit the grid (count, avg,
 * median, ...). Total is the form denominator, so a plugin can render
 * percentages without a second call.
 */
export class Result {
    "kind": string;
    "categories"?: string[];
    "series"?: Series[];
    "scalars"?: { [_ in string]?: number };
    "total": number;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType10;
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("categories" in $$parsedSource) {
            $$parsedSource["categories"] = $$createField1_0($$parsedSource["categories"]);
        }
        if ("series" in $$parsedSource) {
            $$parsedSource["series"] = $$createField2_0($$parsedSource["series"]);
        }
        if ("scalars" in $$parsedSource) {
            $$parsedSource["scalars"] = $$createField3_0($$parsedSource["scalars"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

/**
 * Series is one named row of numbers aligned to a Result's Categories.
 */
export class Series {
    "name": string;
    "values": number[];

    /** Creates a new Series instance. */
    constructor($$source: Partial<Series> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("values" in $$source)) {
            this["values"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Series instance from a string or object.
     */
    static createFrom($$source: any = {}): Series {
        const $$createField1_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField1_0($$parsedSource["values"]);
        }
        return new Series($$parsedSource as Partial<Series>);
    }
}

/**
 * SourceKind distinguishes a field source from a facet source.
 */
export enum SourceKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SourceField = "field",
    SourceFacet = "facet",
};

/**
 * SourceRef references a statistical source by key: a field (optionally a
 * table column by its option value-key) or a facet. Column is "" for a
 * scalar field or a facet.
 */
export class SourceRef {
    "Kind": SourceKind;
    "Key": string;
    "Column": string;

    /** Creates a new SourceRef instance. */
    constructor($$source: Partial<SourceRef> = {}) {
        if (!("Kind" in $$source)) {
            this["Kind"] = SourceKind.$zero;
        }
        if (!("Key" in $$source)) {
            this["Key"] = "";
        }
        if (!("Column" in $$source)) {
            this["Column"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceRef instance from a string or object.
     */
    static createFrom($$source: any = {}): SourceRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceRef($$parsedSource as Partial<SourceRef>);
    }
}

/**
 * StatConfig is the parsed statistical DSL: one or more measures (cell
 * value layers) over zero or more dimensions (axes), optionally scoped by
 * AND-ed equality filters. No dimensions => a rank-0 scalar; one => a 1D
 * array; two => a 2D matrix; and so on.
 * 
 * Named StatConfig (not Config) to stay unambiguous inside the stat
 * package, which already carries Result/Series.
 */
export class StatConfig {
    "Measures": Measure[];
    "Dimensions": Dimension[];
    "Filters": Filter[];

    /** Creates a new StatConfig instance. */
    constructor($$source: Partial<StatConfig> = {}) {
        if (!("Measures" in $$source)) {
            this["Measures"] = [];
        }
        if (!("Dimensions" in $$source)) {
            this["Dimensions"] = [];
        }
        if (!("Filters" in $$source)) {
            this["Filters"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): StatConfig {
        const $$createField0_0 = $$createType13;
        const $$createField1_0 = $$createType15;
        const $$createField2_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Measures" in $$parsedSource) {
            $$parsedSource["Measures"] = $$createField0_0($$parsedSource["Measures"]);
        }
        if ("Dimensions" in $$parsedSource) {
            $$parsedSource["Dimensions"] = $$createField1_0($$parsedSource["Dimensions"]);
        }
        if ("Filters" in $$parsedSource) {
            $$parsedSource["Filters"] = $$createField2_0($$parsedSource["Filters"]);
        }
        return new StatConfig($$parsedSource as Partial<StatConfig>);
    }
}

/**
 * StatObject is a named statistical object defined on a template: its
 * identifier, optional human label, and the DSL the engine evaluates.
 * Mirrors template.Statistic without the template dependency, so the
 * catalog can travel to Vue and Lua via the Service.
 */
export class StatObject {
    "name": string;
    "label"?: string;
    "dsl": string;

    /** Creates a new StatObject instance. */
    constructor($$source: Partial<StatObject> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("dsl" in $$source)) {
            this["dsl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatObject instance from a string or object.
     */
    static createFrom($$source: any = {}): StatObject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatObject($$parsedSource as Partial<StatObject>);
    }
}

// Private type creation functions
const $$createType0 = SourceRef.createFrom;
const $$createType1 = GridAxis.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = GridCell.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = $Create.Nullable($$createType0);
const $$createType9 = Series.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Map($Create.Any, $Create.Any);
const $$createType12 = Measure.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = Dimension.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = Filter.createFrom;
const $$createType17 = $Create.Array($$createType16);
