// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound facade for the stat module. Vue calls
 * these to drive the statistics dialog; each returns a chart-neutral
 * Result the frontend (or a plugin) shapes into a chart spec. The
 * service stays thin - all aggregation lives on Manager and, beneath
 * it, the index module's SQL.
 * 
 * col is the table-column index for table-field stats; pass nil for a
 * scalar field. percentile is in [0,100]; pass nil to skip it. Wails
 * surfaces both as `number | null` on the TypeScript side.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BuilderBins is the date-bin catalog for the dimension binning picker.
 */
export function BuilderBins(): $CancellablePromise<$models.Bin[]> {
    return $Call.ByID(759425425).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * BuilderFilterOps is the where-clause operator catalog for the filter
 * picker (op + whether its value is numeric).
 */
export function BuilderFilterOps(): $CancellablePromise<$models.FilterOpDescriptor[]> {
    return $Call.ByID(453622795).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * BuilderMeasureOps is the measure catalog (op + input rules) the builder
 * renders its op picker from - backend owns the vocabulary, not the UI.
 */
export function BuilderMeasureOps(): $CancellablePromise<$models.MeasureOpDescriptor[]> {
    return $Call.ByID(61375399).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * CompileDSL serializes a StatConfig into the canonical statistical-DSL
 * string. The Statistical Insight builder dialog calls this on save; the
 * stored string is what evaluation (step 4) later parses + runs.
 */
export function CompileDSL(cfg: $models.StatConfig): $CancellablePromise<string> {
    return $Call.ByID(1028174896, cfg);
}

/**
 * CompositeOptions reports the composites (hop routes) buildable from the
 * template's named objects: each rank-1 parent and, per branch, the existing
 * children that can drill it. The builder renders only these, so the structure
 * gates what the author can wire. Backend steers the frontend.
 */
export function CompositeOptions(template: string): $CancellablePromise<$models.CompositeOption[]> {
    return $Call.ByID(1204583787, template).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * CrossTab is the pair-combination matrix between two facets (rank-2).
 */
export function CrossTab(template: string, keyA: string, keyB: string): $CancellablePromise<$models.Grid | null> {
    return $Call.ByID(721428515, template, keyA, keyB).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * Distribution counts forms by a field's (or table column's) value, as
 * a rank-1 Grid.
 */
export function Distribution(template: string, fieldKey: string, col: number | null): $CancellablePromise<$models.Grid | null> {
    return $Call.ByID(3246012510, template, fieldKey, col).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * EvaluateComposite resolves a template's named composite object (a hop
 * route) and evaluates it: the parent rank-1 grid plus a child grid per
 * drilled branch (nil for solid leaves). Errors if the name is unknown or
 * is not a composite. This is the surface the sunburst/drill renderer
 * consumes; plain objects use EvaluateObject.
 */
export function EvaluateComposite(template: string, name: string): $CancellablePromise<$models.CompositeGrid | null> {
    return $Call.ByID(138719682, template, name).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * EvaluateCompositeSpec evaluates an inline composite spec against the
 * template's saved objects (the parent and children, referenced by name,
 * must already exist). The builder uses it to preview a composite before the
 * composite object itself is saved, mirroring EvaluateDSL for plain objects.
 */
export function EvaluateCompositeSpec(template: string, spec: $models.CompositeSpec): $CancellablePromise<$models.CompositeGrid | null> {
    return $Call.ByID(4017830245, template, spec).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * EvaluateDSL evaluates a raw statistical-DSL string against the index.
 * The builder uses it to preview a statistic's output before it is saved
 * (EvaluateObject needs the object persisted to resolve it by name).
 */
export function EvaluateDSL(template: string, dsl: string): $CancellablePromise<$models.Grid | null> {
    return $Call.ByID(2268999486, template, dsl).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * EvaluateObject resolves a template's named statistical object to its
 * DSL, evaluates it against the index, and returns the rank-N Grid. This
 * is the surface the frontend renderer and the Lua binding consume.
 */
export function EvaluateObject(template: string, name: string): $CancellablePromise<$models.Grid | null> {
    return $Call.ByID(864923500, template, name).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * FacetDistribution counts set forms by a facet's selected option.
 */
export function FacetDistribution(template: string, facetKey: string): $CancellablePromise<$models.Grid | null> {
    return $Call.ByID(248037669, template, facetKey).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListObjects returns the catalog of named statistical objects defined
 * on a template (name, label, DSL). The frontend lists them and the
 * Lua binding enumerates them; either then calls EvaluateObject(name)
 * to run one. DSL is exposed for display, not required for evaluation.
 */
export function ListObjects(template: string): $CancellablePromise<$models.StatObject[]> {
    return $Call.ByID(1835086144, template).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * NumericStats reduces a numeric field / table column to summary
 * measures (min/max/sum/avg/median/stddev[/percentile]) as a rank-0 Grid.
 */
export function NumericStats(template: string, fieldKey: string, col: number | null, percentile: number | null): $CancellablePromise<$models.Grid | null> {
    return $Call.ByID(2728644434, template, fieldKey, col, percentile).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ParseDSL turns a stored statistical-DSL string back into a StatConfig
 * so the builder can re-open it for editing. Strict: an unrecognised
 * string is an error, letting the dialog show a clean "couldn't load"
 * flow rather than silently misreading.
 */
export function ParseDSL(dsl: string): $CancellablePromise<$models.StatConfig> {
    return $Call.ByID(2598631634, dsl).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * TimeSeries buckets a date field / column by period ("year" | "month"
 * | "day") and counts forms per bucket, as a rank-1 Grid.
 */
export function TimeSeries(template: string, fieldKey: string, col: number | null, period: string): $CancellablePromise<$models.Grid | null> {
    return $Call.ByID(4140051192, template, fieldKey, col, period).then(($result: any) => {
        return $$createType8($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.FilterOpDescriptor.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.MeasureOpDescriptor.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.CompositeOption.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.Grid.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $models.CompositeGrid.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $models.StatObject.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.StatConfig.createFrom;
