// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-facing surface. The identity values are
 * compile-time constants; the only state is the injected browser
 * opener used by OpenWebsite, supplied by the composition root so the
 * module stays free of os/exec (same pattern as wiki.Service).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetInfo(): $CancellablePromise<$models.Info> {
    return $Call.ByID(2975423933).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetLibraries returns the canonical credits list - the source of
 * truth for the About panel's "Special thanks to" section. Frontend
 * renders one row per entry and looks up the per-locale description
 * via i18n. Returns a fresh slice so the bound caller can't mutate
 * the package-level Libraries.
 */
export function GetLibraries(): $CancellablePromise<$models.Library[]> {
    return $Call.ByID(1753815820).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * OpenWebsite asks the host platform's default browser to load the
 * project homepage. The opener is platform-specific and lives in the
 * composition root.
 */
export function OpenWebsite(): $CancellablePromise<void> {
    return $Call.ByID(2838388132);
}

// Private type creation functions
const $$createType0 = $models.Info.createFrom;
const $$createType1 = $models.Library.createFrom;
const $$createType2 = $Create.Array($$createType1);
