// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-facing surface. Stateless on purpose — the
 * values are compile-time constants.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetInfo(): $CancellablePromise<$models.Info> {
    return $Call.ByID(2975423933).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetLibraries returns the canonical credits list — the source of
 * truth for the About panel's "Special thanks to" section. Frontend
 * renders one row per entry and looks up the per-locale description
 * via i18n. Returns a fresh slice so the bound caller can't mutate
 * the package-level Libraries.
 */
export function GetLibraries(): $CancellablePromise<$models.Library[]> {
    return $Call.ByID(1753815820).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Info.createFrom;
const $$createType1 = $models.Library.createFrom;
const $$createType2 = $Create.Array($$createType1);
