// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Cell is one output value: Text is the display string; Num carries the
 * parsed number when the value had one, so the REST consumer can emit a
 * real JSON number instead of a quoted string.
 */
export class Cell {
    "text": string;
    "num"?: number | null;

    /** Creates a new Cell instance. */
    constructor($$source: Partial<Cell> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Cell instance from a string or object.
     */
    static createFrom($$source: any = {}): Cell {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Cell($$parsedSource as Partial<Cell>);
    }
}

/**
 * Column is one projected output column: a display Header plus the
 * indexed Source it reads.
 */
export class Column {
    "header": string;
    "source": Source;

    /** Creates a new Column instance. */
    constructor($$source: Partial<Column> = {}) {
        if (!("header" in $$source)) {
            this["header"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = (new Source());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Column instance from a string or object.
     */
    static createFrom($$source: any = {}): Column {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("source" in $$parsedSource) {
            $$parsedSource["source"] = $$createField1_0($$parsedSource["source"]);
        }
        return new Column($$parsedSource as Partial<Column>);
    }
}

/**
 * Filter scopes the query to rows where Source satisfies the comparison.
 * Op is eq/ne (text) or lt/le/gt/ge (numeric); validation lives in the
 * index layer so there is one definition of the comparison semantics.
 */
export class Filter {
    "source": Source;
    "op": string;
    "value": string;

    /** Creates a new Filter instance. */
    constructor($$source: Partial<Filter> = {}) {
        if (!("source" in $$source)) {
            this["source"] = (new Source());
        }
        if (!("op" in $$source)) {
            this["op"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Filter instance from a string or object.
     */
    static createFrom($$source: any = {}): Filter {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("source" in $$parsedSource) {
            $$parsedSource["source"] = $$createField0_0($$parsedSource["source"]);
        }
        return new Filter($$parsedSource as Partial<Filter>);
    }
}

/**
 * Result is the query output: Columns are the header strings (group
 * columns plus the count header in group mode), Rows the typed cells.
 * Count is the number of result rows; Total is the template's full form
 * count, a denominator for "N of M" context.
 */
export class Result {
    "columns": string[];
    "rows": Cell[][];
    "count": number;
    "total": number;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

/**
 * Sort orders the result by a projected column (Column index into Spec
 * Columns). Numeric sorts on the parsed number, so a number column
 * orders 2 < 10 rather than lexically. Honored in row-listing mode;
 * group mode orders by group key (explicit group-mode sort is a
 * follow-up).
 */
export class Sort {
    "column": number;
    "desc": boolean;
    "numeric": boolean;

    /** Creates a new Sort instance. */
    constructor($$source: Partial<Sort> = {}) {
        if (!("column" in $$source)) {
            this["column"] = 0;
        }
        if (!("desc" in $$source)) {
            this["desc"] = false;
        }
        if (!("numeric" in $$source)) {
            this["numeric"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Sort instance from a string or object.
     */
    static createFrom($$source: any = {}): Sort {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Sort($$parsedSource as Partial<Sort>);
    }
}

/**
 * Source identifies one indexed value: a scalar field, a table column
 * (Col set to its positional form_values.col index), or a facet. Mirrors
 * the (Kind, Key, Col) shape index.ProjectCol / index.AggDim use, so the
 * translation is one-to-one.
 */
export class Source {
    /**
     * "field" | "facet"
     */
    "kind": string;
    "key": string;
    "col"?: number | null;

    /** Creates a new Source instance. */
    constructor($$source: Partial<Source> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Source instance from a string or object.
     */
    static createFrom($$source: any = {}): Source {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Source($$parsedSource as Partial<Source>);
    }
}

/**
 * Spec is a full query request. With no GroupBy it is a row listing
 * (each form/cell a row), reusing index.ProjectRows; Distinct collapses
 * the projected tuple (the flatten-list/table-and-distinct case). With
 * GroupBy it is an aggregation over index.AggregateRaw: the result
 * carries the group columns plus, when Count is set, a count of the rows
 * contributing to each group.
 */
export class Spec {
    "template": string;
    "columns": Column[];
    "filters"?: Filter[];
    "distinct"?: boolean;
    "groupBy"?: number[];
    "count"?: boolean;
    "countHeader"?: string;
    "orderBy"?: Sort[];
    "limit"?: number;

    /** Creates a new Spec instance. */
    constructor($$source: Partial<Spec> = {}) {
        if (!("template" in $$source)) {
            this["template"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Spec instance from a string or object.
     */
    static createFrom($$source: any = {}): Spec {
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType8;
        const $$createField4_0 = $$createType9;
        const $$createField7_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField1_0($$parsedSource["columns"]);
        }
        if ("filters" in $$parsedSource) {
            $$parsedSource["filters"] = $$createField2_0($$parsedSource["filters"]);
        }
        if ("groupBy" in $$parsedSource) {
            $$parsedSource["groupBy"] = $$createField4_0($$parsedSource["groupBy"]);
        }
        if ("orderBy" in $$parsedSource) {
            $$parsedSource["orderBy"] = $$createField7_0($$parsedSource["orderBy"]);
        }
        return new Spec($$parsedSource as Partial<Spec>);
    }
}

// Private type creation functions
const $$createType0 = Source.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = Cell.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = Column.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = Filter.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = Sort.createFrom;
const $$createType11 = $Create.Array($$createType10);
