// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-facing layer over Manager. The studio query panel
 * calls Run; the REST endpoint calls Manager.Run directly (it holds the
 * manager, not the service).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * FilterOps returns the comparison operators a filter may use, in display
 * order. Backend-owned (sourced from the datacore) so the query panel's
 * operator picker can't drift from what the engine accepts.
 */
export function FilterOps(): $CancellablePromise<string[]> {
    return $Call.ByID(3553049346).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Run executes a query Spec and returns the typed Result. Errors
 * (bad template, out-of-range column, invalid filter op) surface as the
 * returned error so the frontend toast shows the backend message.
 */
export function Run(spec: $models.Spec): $CancellablePromise<$models.Result> {
    return $Call.ByID(2990207941, spec).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.Result.createFrom;
