// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound facade for the vault.
 * 
 * Secret values only ever travel inward. There is no GetSecret: the frontend
 * can store, replace, delete and count credentials, but never read one back.
 * Everything that needs a value (the api-client invoker) runs in Go and reads
 * the vault directly, so a plaintext credential never crosses into JavaScript.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChangeMasterPassword re-encrypts the vault under a new password. The old one
 * is required even on an unlocked vault, so an unattended app cannot be used
 * to lock its owner out.
 */
export function ChangeMasterPassword(oldPassword: string, newPassword: string): $CancellablePromise<void> {
    return $Call.ByID(1737800295, oldPassword, newPassword);
}

/**
 * DeleteSecret removes a stored value.
 */
export function DeleteSecret(name: string): $CancellablePromise<void> {
    return $Call.ByID(1734412015, name);
}

/**
 * Dir is the vault directory, for the panel to show and for the composition
 * root to build a Resolver against.
 */
export function Dir(): $CancellablePromise<string> {
    return $Call.ByID(2639651315);
}

/**
 * HasSecret reports whether a value is stored under name, without unlocking.
 */
export function HasSecret(name: string): $CancellablePromise<boolean> {
    return $Call.ByID(376088448, name);
}

/**
 * InitializeVault creates the vault under <AppRoot>/vault and leaves it
 * unlocked. It refuses when one already exists, since overwriting would
 * discard every stored credential.
 */
export function InitializeVault(masterPassword: string): $CancellablePromise<void> {
    return $Call.ByID(1067353758, masterPassword);
}

/**
 * ListSecrets returns the stored entry names and their last-write times. No
 * values, and no unlock required.
 */
export function ListSecrets(): $CancellablePromise<$models.Entry[]> {
    return $Call.ByID(1189962913).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * LockVault zeroes the derived key. Safe to call when already locked.
 */
export function LockVault(): $CancellablePromise<void> {
    return $Call.ByID(1111961845);
}

/**
 * SetSecret stores or replaces a value under name.
 */
export function SetSecret(name: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(4002251352, name, value);
}

/**
 * UnlockVault opens the vault with the master password. A wrong password
 * returns ErrInvalidPassword and leaves the vault locked.
 */
export function UnlockVault(masterPassword: string): $CancellablePromise<void> {
    return $Call.ByID(2573759836, masterPassword);
}

/**
 * VaultPolicy returns the password and auto-lock rules the UI must enforce. It
 * is served rather than restated: a minimum hardcoded in the frontend drifts
 * the first time this one changes.
 */
export function VaultPolicy(): $CancellablePromise<$models.Policy> {
    return $Call.ByID(291413010).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * VaultStatus reports whether a vault exists, whether it is open, and how many
 * secrets it holds. Names are filenames, so the count needs no key.
 */
export function VaultStatus(): $CancellablePromise<$models.Status> {
    return $Call.ByID(1911097482).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Entry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Policy.createFrom;
const $$createType3 = $models.Status.createFrom;
