// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound facade for the vault. Secrets are addressed by
 * (category, key); the on-disk slot name is opaque and never surfaces here.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChangeMasterPassword re-encrypts the vault under a new password. The old one
 * is required even on an unlocked vault, so an unattended app cannot be used
 * to lock its owner out.
 */
export function ChangeMasterPassword(oldPassword: string, newPassword: string): $CancellablePromise<void> {
    return $Call.ByID(1737800295, oldPassword, newPassword);
}

/**
 * DeleteSecret removes the secret under (category, key).
 */
export function DeleteSecret(category: string, key: string): $CancellablePromise<void> {
    return $Call.ByID(1734412015, category, key);
}

/**
 * Dir is the vault directory, for the panel to show and for the composition
 * root to build a Resolver against.
 */
export function Dir(): $CancellablePromise<string> {
    return $Call.ByID(2639651315);
}

/**
 * HasSecret reports whether a secret is stored under (category, key). Unlike
 * the old flat store this needs the vault unlocked, and answers false rather
 * than guessing when it is not.
 */
export function HasSecret(category: string, key: string): $CancellablePromise<boolean> {
    return $Call.ByID(376088448, category, key);
}

/**
 * InitializeVault creates the vault under <AppRoot>/vault and leaves it
 * unlocked. It refuses when one already exists, since overwriting would
 * discard every stored credential.
 */
export function InitializeVault(masterPassword: string): $CancellablePromise<void> {
    return $Call.ByID(1067353758, masterPassword);
}

/**
 * ListSecrets returns every secret's identity and metadata, never its value.
 * Requires an unlocked vault.
 */
export function ListSecrets(): $CancellablePromise<$models.CatalogEntry[]> {
    return $Call.ByID(1189962913).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * LockVault zeroes the derived key. Safe to call when already locked.
 */
export function LockVault(): $CancellablePromise<void> {
    return $Call.ByID(1111961845);
}

/**
 * RevealSecret returns a stored value in plaintext.
 * 
 * Named for what it does rather than as a bland Get, because it is the one
 * method that lets a secret cross into the frontend. Nothing automated calls
 * it: the api-client invoker reads the vault directly in Go. It exists so the
 * person who owns the vault can see what they put in it, which a store you
 * cannot read back cannot be told apart from a store that lost your data.
 */
export function RevealSecret(category: string, key: string): $CancellablePromise<string> {
    return $Call.ByID(1435462901, category, key);
}

/**
 * SetSecret stores or replaces the value under (category, key).
 */
export function SetSecret(category: string, key: string, value: string, description: string): $CancellablePromise<void> {
    return $Call.ByID(4002251352, category, key, value, description);
}

/**
 * UnlockVault opens the vault with the master password. A wrong password
 * returns ErrInvalidPassword and leaves the vault locked.
 */
export function UnlockVault(masterPassword: string): $CancellablePromise<void> {
    return $Call.ByID(2573759836, masterPassword);
}

/**
 * VaultPolicy returns the password and auto-lock rules the UI must enforce. It
 * is served rather than restated: a minimum hardcoded in the frontend drifts
 * the first time this one changes.
 */
export function VaultPolicy(): $CancellablePromise<$models.Policy> {
    return $Call.ByID(291413010).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * VaultStatus reports whether a vault exists and whether it is open. The
 * counts are filled in only when unlocked, because counting means decrypting.
 */
export function VaultStatus(): $CancellablePromise<$models.Status> {
    return $Call.ByID(1911097482).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.CatalogEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Policy.createFrom;
const $$createType3 = $models.Status.createFrom;
