// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound facade for API Clients.
 * 
 * Credentials move one way: SetCredential takes a value in, and nothing hands
 * one back out. HasCredential answers the only question the panel actually has,
 * which is whether a client is configured.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteClient removes a client, its spec when nothing else uses it, and its
 * stored credential.
 */
export function DeleteClient(id: string): $CancellablePromise<void> {
    return $Call.ByID(1551634214, id);
}

/**
 * DetectResources proposes resources by reading the client's spec, for the
 * detect button in the resource editor. It takes the draft rather than an id so
 * an unsaved edit counts: whatever the draft already binds is left out of the
 * proposal, and its keys are not reused.
 */
export function DetectResources(c: $models.Connection): $CancellablePromise<$models.Detection> {
    return $Call.ByID(3487237138, c).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * FetchItem resolves one stored id back to a record.
 */
export function FetchItem(req: $models.FetchRequest): $CancellablePromise<$models.Item | null> {
    return $Call.ByID(4230382725, req).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * FetchSnapshot fetches one remote record and returns it in the shape the
 * api-client field stores: Select names the fields to keep. An error yields no
 * snapshot, so a caller keeps the copy already on disk instead of blanking it.
 */
export function FetchSnapshot(req: $models.FetchRequest): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(4176554170, req).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ForgetCredential removes a client's stored secret.
 */
export function ForgetCredential(id: string): $CancellablePromise<void> {
    return $Call.ByID(2229904506, id);
}

/**
 * GetCatalog returns the operations a client's spec offers, for the operation
 * pickers in the resource editor.
 */
export function GetCatalog(id: string): $CancellablePromise<$models.Catalog | null> {
    return $Call.ByID(318381573, id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetClient returns one client with its parsed spec.
 */
export function GetClient(id: string): $CancellablePromise<$models.ClientDetail | null> {
    return $Call.ByID(1347498253, id).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * HasCredential reports whether a secret is on file for a client. It does not
 * need the store unlocked, so the panel can show configured state before
 * prompting for a master password.
 */
export function HasCredential(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(695875047, id);
}

/**
 * ImportSpec stores an uploaded Swagger or OpenAPI document under
 * api-clients/specs/ and returns the parsed catalog. The body is base64 (or a
 * data URI), matching how the fonts and cover uploads cross the boundary.
 */
export function ImportSpec(name: string, base64Data: string): $CancellablePromise<$models.SpecInfo> {
    return $Call.ByID(2441444904, name, base64Data).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListClients returns every stored client, sorted, with a per-row OK flag.
 */
export function ListClients(): $CancellablePromise<$models.Summary[]> {
    return $Call.ByID(1491783306).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ListDialects returns the known protocol presets for the editor's picker.
 */
export function ListDialects(): $CancellablePromise<string[]> {
    return $Call.ByID(4065150377).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * ListItems runs a client's list binding. This is what a reference field's
 * picker calls, and what the editor's "try it" button calls.
 */
export function ListItems(req: $models.ListRequest): $CancellablePromise<$models.Page | null> {
    return $Call.ByID(4255165002, req).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * ListItemsModes returns the known item-container shapes, for the picker in the
 * resource editor.
 */
export function ListItemsModes(): $CancellablePromise<string[]> {
    return $Call.ByID(1019706854).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * ListKeyStyles returns the known entity-addressing strategies.
 */
export function ListKeyStyles(): $CancellablePromise<string[]> {
    return $Call.ByID(2374331071).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * ListMethods returns the HTTP methods a catalog can contain with the colours
 * their badges render in, so the operation list needs no palette of its own.
 */
export function ListMethods(): $CancellablePromise<$models.MethodDescriptor[]> {
    return $Call.ByID(3988471008).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * ListOperations returns every operation the client's document declares, with
 * what its response reads as and which resources already bind it. The draft
 * goes over rather than an id so the bound-by column tracks unsaved edits.
 */
export function ListOperations(c: $models.Connection): $CancellablePromise<$models.OperationInfo[]> {
    return $Call.ByID(3987997792, c).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * ListPaginationStyles returns the known paging strategies.
 */
export function ListPaginationStyles(): $CancellablePromise<string[]> {
    return $Call.ByID(2413398840).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * ListShapes returns the response shapes an operation row can carry, for the
 * editor's filter.
 */
export function ListShapes(): $CancellablePromise<string[]> {
    return $Call.ByID(1986071000).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * ReloadSpecs drops the parsed-spec cache, for after a spec file is edited by
 * hand outside the app.
 */
export function ReloadSpecs(): $CancellablePromise<void> {
    return $Call.ByID(359660441);
}

/**
 * SaveClient validates every binding against the spec and writes only if all
 * of them hold, so a stored client is always executable.
 */
export function SaveClient(c: $models.Connection): $CancellablePromise<void> {
    return $Call.ByID(257767296, c);
}

/**
 * SetCredential stores the secret a client authenticates with.
 */
export function SetCredential(id: string, secret: string): $CancellablePromise<void> {
    return $Call.ByID(458003311, id, secret);
}

/**
 * SpecDocument returns the uploaded document as JSON, for rendering it with
 * Swagger UI.
 */
export function SpecDocument(c: $models.Connection): $CancellablePromise<$models.SpecDocument> {
    return $Call.ByID(3960498900, c).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * SpecSource returns the uploaded document behind a client, for the Document
 * tab. The draft goes over rather than an id so a client whose upload is not
 * saved yet still shows what was just imported.
 */
export function SpecSource(c: $models.Connection): $CancellablePromise<$models.SpecSource> {
    return $Call.ByID(2394517720, c).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * SwaggerAssets returns the vendored swagger-ui files. They never change
 * between calls, so the frontend fetches them once per session.
 */
export function SwaggerAssets(): $CancellablePromise<$models.SwaggerAssetBundle> {
    return $Call.ByID(4270496547).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * TryOperation runs one operation straight from the document and returns what
 * came back, including a failing status: seeing the remote's own error is the
 * point of a console.
 */
export function TryOperation(req: $models.TryRequest): $CancellablePromise<$models.TryResult | null> {
    return $Call.ByID(2367422776, req).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * TryOperationForm describes what running an operation would need: its
 * parameters, whatever a resource already fixes for them, and whether the
 * console will run it at all.
 */
export function TryOperationForm(c: $models.Connection, operation: string): $CancellablePromise<$models.TryForm> {
    return $Call.ByID(3284087550, c, operation).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * ValidateClient reports what is wrong with a client without saving it, so the
 * editor can show problems while the user is still typing.
 */
export function ValidateClient(c: $models.Connection): $CancellablePromise<$models.ValidationError[]> {
    return $Call.ByID(503905979, c).then(($result: any) => {
        return $$createType25($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Detection.createFrom;
const $$createType1 = $models.Item.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $models.Catalog.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.ClientDetail.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.SpecInfo.createFrom;
const $$createType9 = $models.Summary.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Array($Create.Any);
const $$createType12 = $models.Page.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $models.MethodDescriptor.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $models.OperationInfo.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $models.SpecDocument.createFrom;
const $$createType19 = $models.SpecSource.createFrom;
const $$createType20 = $models.SwaggerAssetBundle.createFrom;
const $$createType21 = $models.TryResult.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = $models.TryForm.createFrom;
const $$createType24 = $models.ValidationError.createFrom;
const $$createType25 = $Create.Array($$createType24);
