// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * Aggregator is how the Manager reduces multiple Events with the same
 * (groupKey, binStart) into a single value. AggCount is the default
 * and ignores Event.Value entirely.
 */
export enum Aggregator {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AggCount = "count",
    AggSum = "sum",
    AggAvg = "avg",
    AggMin = "min",
    AggMax = "max",
};

/**
 * Point is one (timestamp, value) sample on a Series. Used when
 * Query.Bin is non-empty.
 */
export class Point {
    "ts": time$0.Time;
    "value": number;

    /** Creates a new Point instance. */
    constructor($$source: Partial<Point> = {}) {
        if (!("ts" in $$source)) {
            this["ts"] = null;
        }
        if (!("value" in $$source)) {
            this["value"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Point instance from a string or object.
     */
    static createFrom($$source: any = {}): Point {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Point($$parsedSource as Partial<Point>);
    }
}

/**
 * Query is a typed pipeline against one Source. Bin is parsed via
 * time.ParseDuration ("1h", "5m", "24h") - empty/zero means "no time
 * binning, return one scalar Total per groupKey." JSON shape is used
 * by both the Wails bridge and the HTTP handler.
 */
export class Query {
    "source": string;
    "from": time$0.Time;
    "to": time$0.Time;
    "filter"?: { [_ in string]?: string };
    "group_by"?: string[];
    "bin"?: string;
    "agg"?: Aggregator;
    "limit"?: number;

    /** Creates a new Query instance. */
    constructor($$source: Partial<Query> = {}) {
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("from" in $$source)) {
            this["from"] = null;
        }
        if (!("to" in $$source)) {
            this["to"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Query instance from a string or object.
     */
    static createFrom($$source: any = {}): Query {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("filter" in $$parsedSource) {
            $$parsedSource["filter"] = $$createField3_0($$parsedSource["filter"]);
        }
        if ("group_by" in $$parsedSource) {
            $$parsedSource["group_by"] = $$createField4_0($$parsedSource["group_by"]);
        }
        return new Query($$parsedSource as Partial<Query>);
    }
}

/**
 * Result is the Run() return value. Series ordering is stable across
 * runs (sorted by joined Key string) so frontend tile colors don't
 * flicker between refreshes.
 */
export class Result {
    "series": Series[];

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("series" in $$source)) {
            this["series"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("series" in $$parsedSource) {
            $$parsedSource["series"] = $$createField0_0($$parsedSource["series"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

/**
 * Series is the per-group slice of the result. Key holds the dim
 * values that distinguish this Series; Points are populated when
 * Query.Bin > 0; Total holds the scalar aggregate when Bin == 0.
 */
export class Series {
    "key": { [_ in string]?: string };
    "points"?: Point[];
    "total"?: number;

    /** Creates a new Series instance. */
    constructor($$source: Partial<Series> = {}) {
        if (!("key" in $$source)) {
            this["key"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Series instance from a string or object.
     */
    static createFrom($$source: any = {}): Series {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("key" in $$parsedSource) {
            $$parsedSource["key"] = $$createField0_0($$parsedSource["key"]);
        }
        if ("points" in $$parsedSource) {
            $$parsedSource["points"] = $$createField1_0($$parsedSource["points"]);
        }
        return new Series($$parsedSource as Partial<Series>);
    }
}

/**
 * SourceInfo describes one registered Source. Returned by
 * Manager.ListSources() for UI builders that want to render filter
 * and group-by pickers without hard-coding dim names.
 */
export class SourceInfo {
    "name": string;
    "kind": string;
    "dims": string[];

    /** Creates a new SourceInfo instance. */
    constructor($$source: Partial<SourceInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("dims" in $$source)) {
            this["dims"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SourceInfo {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dims" in $$parsedSource) {
            $$parsedSource["dims"] = $$createField2_0($$parsedSource["dims"]);
        }
        return new SourceInfo($$parsedSource as Partial<SourceInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = Series.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Point.createFrom;
const $$createType5 = $Create.Array($$createType4);
