// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound surface over Manager. The frontend calls
 * these methods directly (not via /api/monitor/*) so the Monitoring
 * page works regardless of whether the loopback HTTP server is on.
 * External consumers reach the same Manager through NewHandler.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListSources returns descriptors for every registered Source.
 */
export function ListSources(): $CancellablePromise<$models.SourceInfo[]> {
    return $Call.ByID(4177113720).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Run executes a query. The Query JSON shape matches the HTTP
 * /api/monitor/query endpoint.
 */
export function Run(q: $models.Query): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(2422876699, q).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SourceInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Result.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
