// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SidebarItem is the rendered output of one expression evaluation.
 * Frontends render Text as the sub-label and apply Color (CSS color)
 * + Classes (utility CSS classes from styles/expression.css). Items
 * is populated when the expression returns a list — frontends can
 * render chips/pills instead of a single label if they want.
 * 
 * All fields are JSON-encoded with omitempty so a bare `{Text:"x"}`
 * payload stays compact across the Wails surface.
 */
export class SidebarItem {
    "text": string;
    "color"?: string;
    "bg"?: string;
    "classes"?: string[];
    "items"?: string[];

    /**
     * Filename is set by EvaluateSidebar so the frontend can pair the
     * rendered label with its record without a parallel array. Empty
     * for single-shot Evaluate calls — only meaningful for the bulk
     * sidebar path.
     */
    "filename"?: string;

    /**
     * Error carries the per-row failure message when evaluation fails
     * for one record. The Manager keeps going; the frontend can show
     * a tiny `[expr error]` chip without nuking the whole list.
     */
    "error"?: string;

    /** Creates a new SidebarItem instance. */
    constructor($$source: Partial<SidebarItem> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SidebarItem instance from a string or object.
     */
    static createFrom($$source: any = {}): SidebarItem {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("classes" in $$parsedSource) {
            $$parsedSource["classes"] = $$createField3_0($$parsedSource["classes"]);
        }
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField4_0($$parsedSource["items"]);
        }
        return new SidebarItem($$parsedSource as Partial<SidebarItem>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
