// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Result is what NavigateToFormidable returns to the frontend. Success
 * false carries Error so Vue can toast the reason without redoing the
 * validation. Target is filled even on failure when the URL parsed but
 * the (template, datafile) pair didn't resolve — useful for diagnostics.
 */
export class Result {
    "success": boolean;
    "target"?: Target | null;
    "error"?: string;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("target" in $$parsedSource) {
            $$parsedSource["target"] = $$createField1_0($$parsedSource["target"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

/**
 * Target is the parsed shape of a `formidable://<template>:<datafile>#<fragment>`
 * URL. Fragment is optional and not yet acted on (mirrors original);
 * kept on the wire so future scroll-to-anchor work doesn't need a
 * migration.
 */
export class Target {
    "template": string;
    "datafile": string;
    "fragment"?: string;

    /** Creates a new Target instance. */
    constructor($$source: Partial<Target> = {}) {
        if (!("template" in $$source)) {
            this["template"] = "";
        }
        if (!("datafile" in $$source)) {
            this["datafile"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Target instance from a string or object.
     */
    static createFrom($$source: any = {}): Target {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Target($$parsedSource as Partial<Target>);
    }
}

// Private type creation functions
const $$createType0 = Target.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
