// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound facade for nav. Vue calls these from the
 * FormFieldLink component (bare-link click) and a future global click
 * delegator on the rendered HTML preview.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * NavigateToFormidable resolves a formidable://… URL, validates that
 * the template + datafile exist, persists the selection in config,
 * and emits `nav:changed`. Vue toggles the active workspace in
 * response.
 */
export function NavigateToFormidable(href: string): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(998374894, href).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ResolveFormidable performs only parsing + validation. Useful for
 * hover tooltips and the future internal HTTP server.
 */
export function ResolveFormidable(href: string): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(189578562, href).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Result.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
