// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound facade for the fonts resource. Vue calls these from
 * the Information -> Fonts panel and the slide font picker.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteFont removes a font. A factory font reappears via RestoreDefaultFonts.
 */
export function DeleteFont(name: string): $CancellablePromise<void> {
    return $Call.ByID(1799771128, name);
}

/**
 * FontFaceCSS returns @font-face rules (fonts inlined as data: URIs) so the slide
 * canvas editor can inject uploaded fonts and preview them live.
 */
export function FontFaceCSS(): $CancellablePromise<string> {
    return $Call.ByID(3725258513);
}

/**
 * ListFonts returns a descriptor per font under <AppRoot>/fonts/ (IsSeed flags a
 * factory font).
 */
export function ListFonts(): $CancellablePromise<$models.FontInfo[]> {
    return $Call.ByID(2810558868).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListUIFonts returns the interface fonts a profile can pick from: the built-in
 * stacks plus every uploaded family. Backend-owned, so the settings picker
 * renders this list rather than keeping a font list of its own.
 */
export function ListUIFonts(): $CancellablePromise<$models.UIFont[]> {
    return $Call.ByID(3890214946).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * LoadFont returns one font's bytes, base64-encoded for a JSON round-trip.
 */
export function LoadFont(name: string): $CancellablePromise<string> {
    return $Call.ByID(386054555, name);
}

/**
 * ResolveUIFont turns the profile's stored font id into the font to draw with,
 * falling back to the system stack when the id no longer resolves.
 */
export function ResolveUIFont(id: string): $CancellablePromise<$models.UIFont> {
    return $Call.ByID(651044081, id).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * RestoreDefaultFonts rewrites any factory (seed) font the user deleted.
 */
export function RestoreDefaultFonts(): $CancellablePromise<void> {
    return $Call.ByID(2603499433);
}

/**
 * SaveFont decodes a base64 (or data-URI) body and persists it under
 * <AppRoot>/fonts/<name>. Extension/traversal validation happens in the Manager.
 */
export function SaveFont(name: string, base64Data: string): $CancellablePromise<void> {
    return $Call.ByID(4046896518, name, base64Data);
}

// Private type creation functions
const $$createType0 = $models.FontInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.UIFont.createFrom;
const $$createType3 = $Create.Array($$createType2);
