// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Aggregate is the result of a numeric reduction over a field: the summary
 * computed in one pass over the coercible values, plus any value that refused
 * to coerce. With no numeric values N is 0 and Min/Max/Mean are 0.
 */
export class Aggregate {
    "N": number;
    "Sum": number;
    "Min": number;
    "Max": number;
    "Mean": number;
    "Anomalies": Anomaly[];

    /** Creates a new Aggregate instance. */
    constructor($$source: Partial<Aggregate> = {}) {
        if (!("N" in $$source)) {
            this["N"] = 0;
        }
        if (!("Sum" in $$source)) {
            this["Sum"] = 0;
        }
        if (!("Min" in $$source)) {
            this["Min"] = 0;
        }
        if (!("Max" in $$source)) {
            this["Max"] = 0;
        }
        if (!("Mean" in $$source)) {
            this["Mean"] = 0;
        }
        if (!("Anomalies" in $$source)) {
            this["Anomalies"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Aggregate instance from a string or object.
     */
    static createFrom($$source: any = {}): Aggregate {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Anomalies" in $$parsedSource) {
            $$parsedSource["Anomalies"] = $$createField5_0($$parsedSource["Anomalies"]);
        }
        return new Aggregate($$parsedSource as Partial<Aggregate>);
    }
}

/**
 * Anomaly is a value present where a numeric reduction expected a number but
 * the string would not coerce. It is surfaced, not silently dropped: a value
 * that refuses the type an operation asks for is the "something fishy" signal,
 * not noise to swallow.
 */
export class Anomaly {
    "ID": string;
    "Field": string;
    "Value": string;

    /** Creates a new Anomaly instance. */
    constructor($$source: Partial<Anomaly> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Field" in $$source)) {
            this["Field"] = "";
        }
        if (!("Value" in $$source)) {
            this["Value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Anomaly instance from a string or object.
     */
    static createFrom($$source: any = {}): Anomaly {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Anomaly($$parsedSource as Partial<Anomaly>);
    }
}

/**
 * Bucket is one value of a field and the number of identities carrying it.
 */
export class Bucket {
    "Value": string;
    "Count": number;

    /** Creates a new Bucket instance. */
    constructor($$source: Partial<Bucket> = {}) {
        if (!("Value" in $$source)) {
            this["Value"] = "";
        }
        if (!("Count" in $$source)) {
            this["Count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Bucket instance from a string or object.
     */
    static createFrom($$source: any = {}): Bucket {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Bucket($$parsedSource as Partial<Bucket>);
    }
}

/**
 * CrossCell is one cell of a cross-tab: the count of identities carrying both
 * the Row value (of the row field) and the Col value (of the column field).
 */
export class CrossCell {
    "Row": string;
    "Col": string;
    "Count": number;

    /** Creates a new CrossCell instance. */
    constructor($$source: Partial<CrossCell> = {}) {
        if (!("Row" in $$source)) {
            this["Row"] = "";
        }
        if (!("Col" in $$source)) {
            this["Col"] = "";
        }
        if (!("Count" in $$source)) {
            this["Count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CrossCell instance from a string or object.
     */
    static createFrom($$source: any = {}): CrossCell {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CrossCell($$parsedSource as Partial<CrossCell>);
    }
}

/**
 * CrossTab is a rank-2 contingency: counts binned by two fields. Rows and
 * Cols are the sorted distinct axis values; Cells holds the nonzero cells
 * sorted by row then col, so a caller can render a dense grid (zeros for
 * absent cells) from the axes.
 */
export class CrossTab {
    "Rows": string[];
    "Cols": string[];
    "Cells": CrossCell[];

    /** Creates a new CrossTab instance. */
    constructor($$source: Partial<CrossTab> = {}) {
        if (!("Rows" in $$source)) {
            this["Rows"] = [];
        }
        if (!("Cols" in $$source)) {
            this["Cols"] = [];
        }
        if (!("Cells" in $$source)) {
            this["Cells"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CrossTab instance from a string or object.
     */
    static createFrom($$source: any = {}): CrossTab {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Rows" in $$parsedSource) {
            $$parsedSource["Rows"] = $$createField0_0($$parsedSource["Rows"]);
        }
        if ("Cols" in $$parsedSource) {
            $$parsedSource["Cols"] = $$createField1_0($$parsedSource["Cols"]);
        }
        if ("Cells" in $$parsedSource) {
            $$parsedSource["Cells"] = $$createField2_0($$parsedSource["Cells"]);
        }
        return new CrossTab($$parsedSource as Partial<CrossTab>);
    }
}

/**
 * Graph is the node-link view of the tensor's reference sub-structure: nodes
 * are identities, edges are refs. This is the tensor read as a labeled
 * directed graph rather than as a table.
 */
export class Graph {
    "nodes": GraphNode[];
    "edges": GraphEdge[];
    "capped": boolean;

    /** Creates a new Graph instance. */
    constructor($$source: Partial<Graph> = {}) {
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("edges" in $$source)) {
            this["edges"] = [];
        }
        if (!("capped" in $$source)) {
            this["capped"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Graph instance from a string or object.
     */
    static createFrom($$source: any = {}): Graph {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField0_0($$parsedSource["nodes"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField1_0($$parsedSource["edges"]);
        }
        return new Graph($$parsedSource as Partial<Graph>);
    }
}

/**
 * GraphEdge is one reference: a directed edge from Source to Target labeled by
 * the field that carries the ref (the loop field, or the link field).
 */
export class GraphEdge {
    "source": string;
    "target": string;
    "field": string;

    /** Creates a new GraphEdge instance. */
    constructor($$source: Partial<GraphEdge> = {}) {
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("field" in $$source)) {
            this["field"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphEdge instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphEdge {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphEdge($$parsedSource as Partial<GraphEdge>);
    }
}

/**
 * GraphNode is one identity in the node-link view: a record (root) or a
 * sub-identity (a table/loop row, or a linked record).
 */
export class GraphNode {
    "id": string;
    "label": string;

    /**
     * "root" | "row"
     */
    "kind": string;

    /** Creates a new GraphNode instance. */
    constructor($$source: Partial<GraphNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphNode instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphNode {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphNode($$parsedSource as Partial<GraphNode>);
    }
}

/**
 * GridDim is one dimension of a raw grid: a field to group by. Field is a root
 * field key, or "facet:<key>" for a facet. DateWidth > 0 buckets the value as
 * a date prefix (4 = year, 10 = day, else month).
 */
export class GridDim {
    "Field": string;
    "DateWidth": number;

    /** Creates a new GridDim instance. */
    constructor($$source: Partial<GridDim> = {}) {
        if (!("Field" in $$source)) {
            this["Field"] = "";
        }
        if (!("DateWidth" in $$source)) {
            this["DateWidth"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GridDim instance from a string or object.
     */
    static createFrom($$source: any = {}): GridDim {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GridDim($$parsedSource as Partial<GridDim>);
    }
}

/**
 * GridFilter scopes the grid to roots whose Field satisfies the comparison.
 * Op is eq/ne (text) or lt/le/gt/ge (numeric).
 */
export class GridFilter {
    "Field": string;
    "Op": string;
    "Value": string;

    /** Creates a new GridFilter instance. */
    constructor($$source: Partial<GridFilter> = {}) {
        if (!("Field" in $$source)) {
            this["Field"] = "";
        }
        if (!("Op" in $$source)) {
            this["Op"] = "";
        }
        if (!("Value" in $$source)) {
            this["Value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GridFilter instance from a string or object.
     */
    static createFrom($$source: any = {}): GridFilter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GridFilter($$parsedSource as Partial<GridFilter>);
    }
}

/**
 * GridNum is one numeric measure column of a raw grid: a root field coerced to
 * a number per row.
 */
export class GridNum {
    "Field": string;

    /** Creates a new GridNum instance. */
    constructor($$source: Partial<GridNum> = {}) {
        if (!("Field" in $$source)) {
            this["Field"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GridNum instance from a string or object.
     */
    static createFrom($$source: any = {}): GridNum {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GridNum($$parsedSource as Partial<GridNum>);
    }
}

/**
 * GridRow is one raw row of a grid: the form it came from, its dimension
 * values in order, and its numeric measures in order.
 */
export class GridRow {
    "Form": string;
    "Dims": string[];
    "Nums": NumCell[];

    /** Creates a new GridRow instance. */
    constructor($$source: Partial<GridRow> = {}) {
        if (!("Form" in $$source)) {
            this["Form"] = "";
        }
        if (!("Dims" in $$source)) {
            this["Dims"] = [];
        }
        if (!("Nums" in $$source)) {
            this["Nums"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GridRow instance from a string or object.
     */
    static createFrom($$source: any = {}): GridRow {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Dims" in $$parsedSource) {
            $$parsedSource["Dims"] = $$createField1_0($$parsedSource["Dims"]);
        }
        if ("Nums" in $$parsedSource) {
            $$parsedSource["Nums"] = $$createField2_0($$parsedSource["Nums"]);
        }
        return new GridRow($$parsedSource as Partial<GridRow>);
    }
}

/**
 * NumCell is one numeric measure value, with OK false when the row carried no
 * coercible number (the LEFT-join NULL).
 */
export class NumCell {
    "Value": number;
    "OK": boolean;

    /** Creates a new NumCell instance. */
    constructor($$source: Partial<NumCell> = {}) {
        if (!("Value" in $$source)) {
            this["Value"] = 0;
        }
        if (!("OK" in $$source)) {
            this["OK"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NumCell instance from a string or object.
     */
    static createFrom($$source: any = {}): NumCell {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NumCell($$parsedSource as Partial<NumCell>);
    }
}

/**
 * RootSummary is one root's loop summary: its identity, the loop length (count
 * of sub-identities it links under the link field), and the numeric reduction
 * of a value field over only that root's rows.
 */
export class RootSummary {
    "ID": string;
    "Rows": number;
    "Agg": Aggregate;

    /** Creates a new RootSummary instance. */
    constructor($$source: Partial<RootSummary> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Rows" in $$source)) {
            this["Rows"] = 0;
        }
        if (!("Agg" in $$source)) {
            this["Agg"] = (new Aggregate());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RootSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): RootSummary {
        const $$createField2_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Agg" in $$parsedSource) {
            $$parsedSource["Agg"] = $$createField2_0($$parsedSource["Agg"]);
        }
        return new RootSummary($$parsedSource as Partial<RootSummary>);
    }
}

/**
 * Series is a date histogram: counts bucketed by a period (year/month/day),
 * plus any value that would not coerce to a date.
 */
export class Series {
    "Period": string;
    "Buckets": Bucket[];
    "Anomalies": Anomaly[];

    /** Creates a new Series instance. */
    constructor($$source: Partial<Series> = {}) {
        if (!("Period" in $$source)) {
            this["Period"] = "";
        }
        if (!("Buckets" in $$source)) {
            this["Buckets"] = [];
        }
        if (!("Anomalies" in $$source)) {
            this["Anomalies"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Series instance from a string or object.
     */
    static createFrom($$source: any = {}): Series {
        const $$createField1_0 = $$createType13;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Buckets" in $$parsedSource) {
            $$parsedSource["Buckets"] = $$createField1_0($$parsedSource["Buckets"]);
        }
        if ("Anomalies" in $$parsedSource) {
            $$parsedSource["Anomalies"] = $$createField2_0($$parsedSource["Anomalies"]);
        }
        return new Series($$parsedSource as Partial<Series>);
    }
}

// Private type creation functions
const $$createType0 = Anomaly.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = CrossCell.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = GraphNode.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = GraphEdge.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = NumCell.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = Aggregate.createFrom;
const $$createType12 = Bucket.createFrom;
const $$createType13 = $Create.Array($$createType12);
