// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-facing, read-only layer over the tensor. Each call
 * builds a fresh tensor from the template's live forms and runs one
 * perspective over it. It is purely additive: it reads form data the same way
 * query does and changes nothing the index or stat path relies on.
 * 
 * The optional follow argument steps one reference hop before reducing, so a
 * table or loop column is reachable (follow the loop field, then reduce its
 * rows) without a full spec language. Empty follow reduces over the root
 * records.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Aggregate is the numeric reduction of field (sum/min/max/mean + anomalies),
 * coercing on demand.
 */
export function Aggregate(template: string, follow: string, field: string): $CancellablePromise<$models.Aggregate> {
    return $Call.ByID(3706508746, template, follow, field).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AggregateRaw produces the raw grid rows (form + dim values + numeric
 * measures) that feed statistical aggregation, over root fields, facets, and
 * date-bucketed dims. The caller groups and reduces.
 */
export function AggregateRaw(template: string, dims: $models.GridDim[], nums: $models.GridNum[], filters: $models.GridFilter[]): $CancellablePromise<$models.GridRow[]> {
    return $Call.ByID(3758078644, template, dims, nums, filters).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Count is the number of records (follow empty) or loop rows (follow set).
 */
export function Count(template: string, follow: string): $CancellablePromise<number> {
    return $Call.ByID(1334053890, template, follow);
}

/**
 * CountWhere is Count over the record set narrowed by pred. The planner pushes
 * the predicate to the index, so the tensor only counts the matching records.
 * With no planner wired it falls back to narrowing in memory, same answer.
 */
export function CountWhere(template: string, follow: string, pred: $models.Predicate): $CancellablePromise<number> {
    return $Call.ByID(2896119657, template, follow, pred);
}

/**
 * Cross is the rank-2 contingency of two fields over the working set.
 */
export function Cross(template: string, follow: string, rowField: string, colField: string): $CancellablePromise<$models.CrossTab> {
    return $Call.ByID(836324753, template, follow, rowField, colField).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * DateSeries is the date histogram of field over the (optionally followed)
 * working set, bucketed by period (year/month/day).
 */
export function DateSeries(template: string, follow: string, field: string, period: string): $CancellablePromise<$models.Series> {
    return $Call.ByID(794974094, template, follow, field, period).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Distribution is the rank-1 marginal of field over the (optionally followed)
 * working set.
 */
export function Distribution(template: string, follow: string, field: string): $CancellablePromise<$models.Bucket[]> {
    return $Call.ByID(2219453917, template, follow, field).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * DistributionWhere is Distribution over the record set narrowed by pred. This
 * is the canonical seam shape: the index decides which records exist, the
 * tensor reduces them. The result equals the full Distribution with an
 * equivalent in-memory Where, just computed over fewer ingested records.
 */
export function DistributionWhere(template: string, follow: string, pred: $models.Predicate, field: string): $CancellablePromise<$models.Bucket[]> {
    return $Call.ByID(3093720208, template, follow, pred, field).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * Graph projects the template's tensor as a node-link graph (records and loop
 * rows as nodes, refs as edges) for the visual explorer. limit caps the node
 * count (0 = no cap); roots are kept before rows and dangling edges dropped.
 */
export function Graph(template: string, limit: number): $CancellablePromise<$models.Graph> {
    return $Call.ByID(2962646449, template, limit).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GraphFrom projects the subgraph reachable from one record (rootID, a node
 * id) up to depth hops, for the per-record flower and click-to-unfold.
 */
export function GraphFrom(template: string, rootID: string, depth: number): $CancellablePromise<$models.Graph> {
    return $Call.ByID(3090347177, template, rootID, depth).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * Summarize lands a per-record loop summary on each root: linkField's rows
 * reduced by valueField (empty valueField gives a plain count summary).
 */
export function Summarize(template: string, linkField: string, valueField: string): $CancellablePromise<$models.RootSummary[]> {
    return $Call.ByID(934877232, template, linkField, valueField).then(($result: any) => {
        return $$createType9($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Aggregate.createFrom;
const $$createType1 = $models.GridRow.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.CrossTab.createFrom;
const $$createType4 = $models.Series.createFrom;
const $$createType5 = $models.Bucket.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.Graph.createFrom;
const $$createType8 = $models.RootSummary.createFrom;
const $$createType9 = $Create.Array($$createType8);
