// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Has-result for "is there an entry for this account" queries.
 * Wails-bindable; a bare bool would also work but a struct future-
 * proofs metadata like the timestamp of last update.
 */
export class LookupResult {
    "found": boolean;

    /** Creates a new LookupResult instance. */
    constructor($$source: Partial<LookupResult> = {}) {
        if (!("found" in $$source)) {
            this["found"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LookupResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LookupResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LookupResult($$parsedSource as Partial<LookupResult>);
    }
}
