// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound surface of the credential Manager.
 * Same shape as Manager - the split exists for parity with other
 * modules and to give us a place to hang request-scoped concerns
 * (logging, audit trail) later without leaking them into domain
 * code.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete removes the entry for account. Idempotent.
 */
export function Delete(account: string): $CancellablePromise<void> {
    return $Call.ByID(610615988, account);
}

/**
 * Has returns whether a non-empty secret is present for account.
 * Bound through a struct so future metadata (created_at etc.) can
 * land without breaking the Wails signature.
 */
export function Has(account: string): $CancellablePromise<$models.LookupResult> {
    return $Call.ByID(3714933349, account).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Set stores secret under account. Empty values are rejected.
 */
export function Set(account: string, secret: string): $CancellablePromise<void> {
    return $Call.ByID(227026205, account, secret);
}

// Private type creation functions
const $$createType0 = $models.LookupResult.createFrom;
