//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as log$0 from "../../../../petervdpas/formidable2/internal/log/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gigot$0 from "../../../../petervdpas/formidable2/internal/modules/collaboration/gigot/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as journal$0 from "../../../../petervdpas/formidable2/internal/modules/journal/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nav$0 from "../../../../petervdpas/formidable2/internal/modules/nav/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "gigot:sync_progress": $$createType0,
        "journal:changed": $$createType1,
        "log:entry": $$createType2,
        "nav:changed": $$createType4,
    }));
}

// Private type creation functions
const $$createType0 = gigot$0.SyncProgress.createFrom;
const $$createType1 = journal$0.Entry.createFrom;
const $$createType2 = log$0.Entry.createFrom;
const $$createType3 = nav$0.Target.createFrom;
const $$createType4 = $Create.Nullable($$createType3);

configure();
