// Command pdf-poc is a Stage 0 throwaway proof-of-concept for the
// picoloom-based PDF export pipeline. It converts a fixed markdown
// string to PDF and writes it to /tmp/poc.pdf, exercising:
//
//   - go.mod resolution for picoloom v2 + go-rod
//   - go-rod's Chrome probe (system browser or managed download)
//   - picoloom.Converter end-to-end (Markdown -> HTML -> PDF)
//
// To be deleted once Stage 0 is signed off — see design/pdf-export.md.
package main

import (
	"context"
	"fmt"
	"os"
	"time"

	picoloom "github.com/alnah/picoloom/v2"
)

const markdown = `---
title: picoloom PoC
---

# Formidable PDF export PoC

This PDF is generated by ` + "`cmd/pdf-poc`" + ` to prove that
[picoloom v2](https://github.com/alnah/picoloom) integrates cleanly
into the Formidable2 build.

## What this exercises

- ` + "`picoloom.NewConverter`" + ` construction (default options)
- go-rod's Chrome resolution (` + "`ROD_BROWSER_BIN`" + ` -> system paths -> managed download)
- Markdown -> HTML -> PDF conversion via headless Chrome
- **Image rendering** — both ` + "`data:`" + ` URLs and ` + "`SourceDir`" + `-relative paths

## Image via SourceDir-relative path

![Formidable logo](formidable.png)

## Image via inline data URL (1x1 red PNG)

![Tiny red dot](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=)

## Sample content

| Column A | Column B |
|----------|----------|
| picoloom | v2.1.2   |
| go-rod   | v0.116.2 |

` + "```go" + `
package main

func main() {
    println("hello, picoloom")
}
` + "```" + `

> Block quote works, footnotes[^1] work, lists work.

[^1]: Footnote rendered by picoloom's markdown pipeline.
`

func main() {
	const outPath = "/tmp/poc.pdf"

	fmt.Println("pdf-poc: constructing picoloom.Converter (first run downloads ~55 MB Chromium if no system Chrome found)...")
	tConv := time.Now()
	conv, err := picoloom.NewConverter()
	if err != nil {
		die("NewConverter: %v", err)
	}
	defer conv.Close()
	fmt.Printf("pdf-poc: converter ready in %s\n", time.Since(tConv).Round(time.Millisecond))

	fmt.Println("pdf-poc: converting markdown to PDF...")
	tRender := time.Now()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()
	res, err := conv.Convert(ctx, picoloom.Input{
		Markdown:  markdown,
		SourceDir: "/home/peter/Projects/Formidable2/Examples/storage/basic/images",
	})
	if err != nil {
		die("Convert: %v", err)
	}
	fmt.Printf("pdf-poc: render done in %s — HTML %d bytes, PDF %d bytes\n",
		time.Since(tRender).Round(time.Millisecond), len(res.HTML), len(res.PDF))

	if err := os.WriteFile(outPath, res.PDF, 0o644); err != nil {
		die("write %s: %v", outPath, err)
	}
	fmt.Printf("pdf-poc: wrote %s\n", outPath)
}

func die(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "pdf-poc: "+format+"\n", args...)
	os.Exit(1)
}
