// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * APIMap is one column projected from the source template into the
 * host form's api-field row at fetch time.
 * 
 *   - Key: source-template field key (must reference a level-0 field).
 *     The same key is used as the column name in the host form's
 *     stored row. Required.
 *   - Label: optional display header for that column. When empty, the
 *     editor / wiki falls back to the source field's Label.
 * 
 * Type is intentionally absent - it is derived live from the source
 * template (`source.Fields[Key].Type`). Storing it here would invite
 * drift if the source template's field type changes.
 */
export class APIMap {
    "key": string;
    "label"?: string;

    /** Creates a new APIMap instance. */
    constructor($$source: Partial<APIMap> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIMap instance from a string or object.
     */
    static createFrom($$source: any = {}): APIMap {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APIMap($$parsedSource as Partial<APIMap>);
    }
}

/**
 * Abilities is the per-type ability vector. Each bool gates a single
 * attribute in the field-edit modal AND in backend save-time
 * enforcement. true = enabled (modal row visible, value preserved on
 * save); false = disabled (row hidden, Normalize strips, validator
 * flags any non-zero).
 */
export class Abilities {
    "key": boolean;
    "type": boolean;
    "label": boolean;
    "description": boolean;
    "default": boolean;
    "options": boolean;
    "summary_field": boolean;
    "primary_key": boolean;
    "expression_item": boolean;
    "two_column": boolean;
    "collapsible": boolean;
    "readonly": boolean;
    "format": boolean;

    /** Creates a new Abilities instance. */
    constructor($$source: Partial<Abilities> = {}) {
        if (!("key" in $$source)) {
            this["key"] = false;
        }
        if (!("type" in $$source)) {
            this["type"] = false;
        }
        if (!("label" in $$source)) {
            this["label"] = false;
        }
        if (!("description" in $$source)) {
            this["description"] = false;
        }
        if (!("default" in $$source)) {
            this["default"] = false;
        }
        if (!("options" in $$source)) {
            this["options"] = false;
        }
        if (!("summary_field" in $$source)) {
            this["summary_field"] = false;
        }
        if (!("primary_key" in $$source)) {
            this["primary_key"] = false;
        }
        if (!("expression_item" in $$source)) {
            this["expression_item"] = false;
        }
        if (!("two_column" in $$source)) {
            this["two_column"] = false;
        }
        if (!("collapsible" in $$source)) {
            this["collapsible"] = false;
        }
        if (!("readonly" in $$source)) {
            this["readonly"] = false;
        }
        if (!("format" in $$source)) {
            this["format"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Abilities instance from a string or object.
     */
    static createFrom($$source: any = {}): Abilities {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Abilities($$parsedSource as Partial<Abilities>);
    }
}

/**
 * Descriptor is the {name, yaml, storageLocation} bundle returned by
 * GetDescriptor. Mirrors templateManager.getTemplateDescriptor.
 */
export class Descriptor {
    "name": string;
    "yaml": Template | null;
    "storageLocation": string;

    /** Creates a new Descriptor instance. */
    constructor($$source: Partial<Descriptor> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("yaml" in $$source)) {
            this["yaml"] = null;
        }
        if (!("storageLocation" in $$source)) {
            this["storageLocation"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Descriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): Descriptor {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("yaml" in $$parsedSource) {
            $$parsedSource["yaml"] = $$createField1_0($$parsedSource["yaml"]);
        }
        return new Descriptor($$parsedSource as Partial<Descriptor>);
    }
}

/**
 * Facet is one named dimension of meta classification on a template:
 * a stable Key (used as the FormMeta.Facets map key), an Icon (a
 * FontAwesome key rendered next to the chosen pill), and a list of
 * mutually-exclusive Options to pick from on each record.
 * 
 * Each facet on a record carries a required `set` bool plus an
 * optional `selected` label - see storage.FacetState. Filter chips
 * in the storage view auto-derive from a template's facets but only
 * render when at least one record actually has `set: true` for the
 * facet's key.
 * 
 * Templates may declare up to 16 facets, each with up to 16 options.
 */
export class Facet {
    "key": string;
    "icon": string;
    "options": FacetOption[];

    /** Creates a new Facet instance. */
    constructor($$source: Partial<Facet> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("options" in $$source)) {
            this["options"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Facet instance from a string or object.
     */
    static createFrom($$source: any = {}): Facet {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField2_0($$parsedSource["options"]);
        }
        return new Facet($$parsedSource as Partial<Facet>);
    }
}

/**
 * FacetIconSpec carries the minimal data needed to render one
 * FontAwesome glyph as inline SVG: the path's `viewBox` (icons have
 * different aspects) and the geometry in `Path`'s `d` attribute. No
 * `xmlns` and no fill - both layers (wiki + Vue) wrap this in their
 * own colour-aware shell.
 */
export class FacetIconSpec {
    "viewBox": string;
    "path": string;

    /** Creates a new FacetIconSpec instance. */
    constructor($$source: Partial<FacetIconSpec> = {}) {
        if (!("viewBox" in $$source)) {
            this["viewBox"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FacetIconSpec instance from a string or object.
     */
    static createFrom($$source: any = {}): FacetIconSpec {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FacetIconSpec($$parsedSource as Partial<FacetIconSpec>);
    }
}

/**
 * FacetMeta is the wire-shape returned to the frontend so it can
 * render the editor without hardcoding ANY backend constraint. The
 * frontend reads this once at boot via Service.FacetMeta and treats
 * the backend as the single source of truth for:
 *   - max counts (MaxFacets, MaxOptionsPerFacet)
 *   - palettes (Colors, Icons - ordered for display)
 *   - validation patterns (KeyPattern, LabelPattern - compiled in JS)
 * 
 * Adding a new backend-owned facet rule means extending this struct;
 * the frontend stays a thin renderer.
 */
export class FacetMeta {
    "max_facets": number;
    "max_options_per_facet": number;
    "colors": string[];
    "icons": string[];
    "icon_svgs": { [_ in string]?: FacetIconSpec };
    "key_pattern": string;
    "label_pattern": string;

    /** Creates a new FacetMeta instance. */
    constructor($$source: Partial<FacetMeta> = {}) {
        if (!("max_facets" in $$source)) {
            this["max_facets"] = 0;
        }
        if (!("max_options_per_facet" in $$source)) {
            this["max_options_per_facet"] = 0;
        }
        if (!("colors" in $$source)) {
            this["colors"] = [];
        }
        if (!("icons" in $$source)) {
            this["icons"] = [];
        }
        if (!("icon_svgs" in $$source)) {
            this["icon_svgs"] = {};
        }
        if (!("key_pattern" in $$source)) {
            this["key_pattern"] = "";
        }
        if (!("label_pattern" in $$source)) {
            this["label_pattern"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FacetMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): FacetMeta {
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("colors" in $$parsedSource) {
            $$parsedSource["colors"] = $$createField2_0($$parsedSource["colors"]);
        }
        if ("icons" in $$parsedSource) {
            $$parsedSource["icons"] = $$createField3_0($$parsedSource["icons"]);
        }
        if ("icon_svgs" in $$parsedSource) {
            $$parsedSource["icon_svgs"] = $$createField4_0($$parsedSource["icon_svgs"]);
        }
        return new FacetMeta($$parsedSource as Partial<FacetMeta>);
    }
}

/**
 * FacetOption is one selectable label within a facet. Label is the
 * user-visible identifier (also used as the value stored in
 * FormMeta.Facets[key].Selected); Color names a token from the
 * shared 16-token palette. Colors may repeat across labels.
 */
export class FacetOption {
    "label": string;
    "color": string;

    /** Creates a new FacetOption instance. */
    constructor($$source: Partial<FacetOption> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FacetOption instance from a string or object.
     */
    static createFrom($$source: any = {}): FacetOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FacetOption($$parsedSource as Partial<FacetOption>);
    }
}

/**
 * Field describes one input in a template. Type-specific properties
 * (run_mode, options, collection, etc.) sit alongside the common ones -
 * downstream consumers ignore irrelevant fields.
 */
export class Field {
    /**
     * Common
     */
    "key": string;
    "type": string;
    "label": string;
    "description": string;

    /**
     * I18n is the optional base key for plugin field translation.
     * When set, the renderer resolves `<plugin-namespace>.<I18n>.<sub>`
     * for sub-keys `label`, `description`, `placeholder` via the
     * active locale, falling back to the literal Label/Description
     * on miss. Templates don't need this (user-authored labels are
     * the literal source); it's foremost a plugin-form.json signal.
     */
    "i18n"?: string;
    "summary_field"?: string;
    "expression_item": boolean;
    "level_scope": number;
    "two_column": boolean;
    "collapsible"?: boolean | null;
    "readonly": boolean;
    "default": any;
    "options": any[];
    "primary_key"?: boolean;

    /**
     * textarea-specific
     */
    "format"?: string;

    /**
     * api-specific. Collection is the source template (filename or
     * name). Map is the column list - each entry projects one
     * level-0 source field into the host form's row at fetch time.
     * Type is not stored; it is resolved live from the source
     * template (`source.Fields[Map[i].Key].Type`) so a source-side
     * rename or type change can't drift a stale cache.
     */
    "collection"?: string;
    "map"?: APIMap[];

    /** Creates a new Field instance. */
    constructor($$source: Partial<Field> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("expression_item" in $$source)) {
            this["expression_item"] = false;
        }
        if (!("level_scope" in $$source)) {
            this["level_scope"] = 0;
        }
        if (!("two_column" in $$source)) {
            this["two_column"] = false;
        }
        if (!("readonly" in $$source)) {
            this["readonly"] = false;
        }
        if (!("default" in $$source)) {
            this["default"] = null;
        }
        if (!("options" in $$source)) {
            this["options"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Field instance from a string or object.
     */
    static createFrom($$source: any = {}): Field {
        const $$createField12_0 = $$createType7;
        const $$createField16_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField12_0($$parsedSource["options"]);
        }
        if ("map" in $$parsedSource) {
            $$parsedSource["map"] = $$createField16_0($$parsedSource["map"]);
        }
        return new Field($$parsedSource as Partial<Field>);
    }
}

/**
 * FieldDescriptor is the per-type record. MetaOnly flags marker types
 * (looper, loopstart, loopstop) that don't carry a stored value but
 * still participate in validation. OptionsShape is non-nil when the
 * type's options array has a fixed arity (e.g. boolean = exactly two
 * rows for the True/False labels) - the frontend's OptionsEditor
 * gates add/remove on this and pre-fills with the supplied defaults.
 */
export class FieldDescriptor {
    "id": string;
    "meta_only": boolean;
    "abilities": Abilities;
    "options_shape"?: FixedOptionsShape | null;

    /** Creates a new FieldDescriptor instance. */
    constructor($$source: Partial<FieldDescriptor> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("meta_only" in $$source)) {
            this["meta_only"] = false;
        }
        if (!("abilities" in $$source)) {
            this["abilities"] = (new Abilities());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FieldDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): FieldDescriptor {
        const $$createField2_0 = $$createType10;
        const $$createField3_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("abilities" in $$parsedSource) {
            $$parsedSource["abilities"] = $$createField2_0($$parsedSource["abilities"]);
        }
        if ("options_shape" in $$parsedSource) {
            $$parsedSource["options_shape"] = $$createField3_0($$parsedSource["options_shape"]);
        }
        return new FieldDescriptor($$parsedSource as Partial<FieldDescriptor>);
    }
}

/**
 * FieldUnit is the runtime tree shape the template editor renders.
 * It folds a matched loopstart/loopstop pair (and everything between
 * them) into a single indivisible unit so the UI cannot reorder a row
 * across the loop boundary and create an orphan marker.
 * 
 * The flat []Field shape on disk is still the source of truth; this
 * type is a view over it. BuildFieldTree produces the view,
 * FlattenFieldTree returns to the flat form. Orphan loopstart /
 * loopstop rows (no matching partner) are emitted as plain field
 * units so backend validation can still flag them - silently
 * dropping data would be worse than rendering a broken pair.
 * 
 * The struct is one shape with a Kind discriminator + nullable
 * payload fields so the Wails-generated TypeScript stays simple.
 */
export class FieldUnit {
    "kind": string;
    "field"?: Field | null;
    "start"?: Field | null;
    "stop"?: Field | null;
    "items"?: FieldUnit[];

    /** Creates a new FieldUnit instance. */
    constructor($$source: Partial<FieldUnit> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FieldUnit instance from a string or object.
     */
    static createFrom($$source: any = {}): FieldUnit {
        const $$createField1_0 = $$createType14;
        const $$createField2_0 = $$createType14;
        const $$createField3_0 = $$createType14;
        const $$createField4_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("field" in $$parsedSource) {
            $$parsedSource["field"] = $$createField1_0($$parsedSource["field"]);
        }
        if ("start" in $$parsedSource) {
            $$parsedSource["start"] = $$createField2_0($$parsedSource["start"]);
        }
        if ("stop" in $$parsedSource) {
            $$parsedSource["stop"] = $$createField3_0($$parsedSource["stop"]);
        }
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField4_0($$parsedSource["items"]);
        }
        return new FieldUnit($$parsedSource as Partial<FieldUnit>);
    }
}

/**
 * FixedOptionRow is one row in a FixedOptionsShape - a structurally
 * fixed slot in a field's options array (e.g. True / False rows for
 * a bool field). Defaults populate the cells when the user first
 * picks the field type or when an existing options array arrives
 * short of the configured arity. LabelKey is the i18n key for the
 * row's gutter caption.
 */
export class FixedOptionRow {
    "label_key": string;
    "defaults": { [_ in string]?: any };

    /** Creates a new FixedOptionRow instance. */
    constructor($$source: Partial<FixedOptionRow> = {}) {
        if (!("label_key" in $$source)) {
            this["label_key"] = "";
        }
        if (!("defaults" in $$source)) {
            this["defaults"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FixedOptionRow instance from a string or object.
     */
    static createFrom($$source: any = {}): FixedOptionRow {
        const $$createField1_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("defaults" in $$parsedSource) {
            $$parsedSource["defaults"] = $$createField1_0($$parsedSource["defaults"]);
        }
        return new FixedOptionRow($$parsedSource as Partial<FixedOptionRow>);
    }
}

/**
 * FixedOptionsShape declares the options array's fixed arity for a
 * field type. nil/empty Rows = free-form (add/remove enabled).
 */
export class FixedOptionsShape {
    "rows": FixedOptionRow[];

    /** Creates a new FixedOptionsShape instance. */
    constructor($$source: Partial<FixedOptionsShape> = {}) {
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FixedOptionsShape instance from a string or object.
     */
    static createFrom($$source: any = {}): FixedOptionsShape {
        const $$createField0_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField0_0($$parsedSource["rows"]);
        }
        return new FixedOptionsShape($$parsedSource as Partial<FixedOptionsShape>);
    }
}

/**
 * GeneratorOptions carries the per-shape sub-choices the dialog
 * surfaces. Bag-of-bools so adding a new option doesn't require
 * signature changes throughout the call chain (Service ↔ generator ↔
 * Wails binding).
 * 
 * Defaults match the dialog's defaults: linked URL for images, auto-
 * wrapped loop iterations, lazy api-card output (one-liner per api
 * field).
 */
export class GeneratorOptions {
    "img_mode": ImgMode;
    "wrap_loops": boolean;

    /**
     * ExpandAPI flips api-field output between two visible shapes:
     *   false → `{{apiSection "key"}}`        (lazy one-liner)
     *   true  → per-column `- **<label>**: {{apiBlock "key" "col"}}`
     * Same "visible toggle" rule as ImgMode/WrapLoops - the choice
     * must materialise in the generated source so the user can see
     * what they picked at a glance.
     */
    "expand_api": boolean;

    /** Creates a new GeneratorOptions instance. */
    constructor($$source: Partial<GeneratorOptions> = {}) {
        if (!("img_mode" in $$source)) {
            this["img_mode"] = ImgMode.$zero;
        }
        if (!("wrap_loops" in $$source)) {
            this["wrap_loops"] = false;
        }
        if (!("expand_api" in $$source)) {
            this["expand_api"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeneratorOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): GeneratorOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GeneratorOptions($$parsedSource as Partial<GeneratorOptions>);
    }
}

/**
 * ImgMode selects how image fields are emitted.
 * 
 * 	url    - `![Label]({{imageURL "key"}})`. Resolved at render time
 * 	         per the consumer's render.Manager (slideout, wiki, …).
 * 	inline - `![Label]({{imageBase64 "key"}})`. Bytes inlined as a
 * 	         `data:<mime>;base64,…` URL. For self-contained exports.
 */
export enum ImgMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ImgURL = "url",
    ImgInline = "inline",
};

/**
 * ItemField is one row in the "possible item fields" picker (top-level
 * non-loop text fields, used to choose a collection's primary identifier).
 */
export class ItemField {
    "key": string;
    "label": string;

    /** Creates a new ItemField instance. */
    constructor($$source: Partial<ItemField> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ItemField instance from a string or object.
     */
    static createFrom($$source: any = {}): ItemField {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ItemField($$parsedSource as Partial<ItemField>);
    }
}

/**
 * ListItemTypeDescriptor names one entry the Edit Field modal's
 * `list` preset offers in its item-type dropdown. Same rationale as
 * TableColumnTypeDescriptor - captured here even though Go doesn't
 * interpret the strings yet, so the future home is ready.
 */
export class ListItemTypeDescriptor {
    "name": string;
    "sub_row"?: SubRow | null;

    /** Creates a new ListItemTypeDescriptor instance. */
    constructor($$source: Partial<ListItemTypeDescriptor> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListItemTypeDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): ListItemTypeDescriptor {
        const $$createField1_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sub_row" in $$parsedSource) {
            $$parsedSource["sub_row"] = $$createField1_0($$parsedSource["sub_row"]);
        }
        return new ListItemTypeDescriptor($$parsedSource as Partial<ListItemTypeDescriptor>);
    }
}

/**
 * LoadManyResult is one slot in LoadMany's response. Template is nil
 * when the file was missing or unparseable - Error carries the
 * per-row failure message. Filename is always stamped so callers can
 * pair the result back to its input slot even when Template is nil.
 */
export class LoadManyResult {
    "filename": string;
    "template"?: Template | null;
    "error"?: string;

    /** Creates a new LoadManyResult instance. */
    constructor($$source: Partial<LoadManyResult> = {}) {
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoadManyResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LoadManyResult {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("template" in $$parsedSource) {
            $$parsedSource["template"] = $$createField1_0($$parsedSource["template"]);
        }
        return new LoadManyResult($$parsedSource as Partial<LoadManyResult>);
    }
}

/**
 * PDFConfig is the per-template PDF export defaults: a theme/style
 * selector plus a cover-page block. Both are optional and feed the
 * `manifest` layer in pdf.Merge (precedence: document frontmatter >
 * form meta > template manifest > global config).
 * 
 * Style accepts the same values as picoloom's WithStyle option:
 * a built-in theme name ("default", "technical", …), a filesystem
 * path to a custom .css, or raw CSS content.
 */
export class PDFConfig {
    "style"?: string;
    "cover"?: PDFCoverConfig | null;

    /** Creates a new PDFConfig instance. */
    constructor($$source: Partial<PDFConfig> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PDFConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): PDFConfig {
        const $$createField1_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cover" in $$parsedSource) {
            $$parsedSource["cover"] = $$createField1_0($$parsedSource["cover"]);
        }
        return new PDFConfig($$parsedSource as Partial<PDFConfig>);
    }
}

/**
 * PDFCoverConfig mirrors pdf.CoverFM's shape so the template manifest
 * can carry default cover values that document frontmatter can
 * override. Field tags match the document-frontmatter casing so
 * authors get one consistent vocabulary across both layers.
 */
export class PDFCoverConfig {
    "enabled"?: boolean | null;
    "template"?: string;
    "template_path"?: string;
    "title"?: string;
    "subtitle"?: string;
    "logo"?: string;
    "author"?: string;
    "authorTitle"?: string;
    "organization"?: string;
    "date"?: string;
    "version"?: string;
    "clientName"?: string;
    "projectName"?: string;
    "documentType"?: string;
    "documentID"?: string;
    "description"?: string;
    "department"?: string;

    /** Creates a new PDFCoverConfig instance. */
    constructor($$source: Partial<PDFCoverConfig> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PDFCoverConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): PDFCoverConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PDFCoverConfig($$parsedSource as Partial<PDFCoverConfig>);
    }
}

/**
 * Shape selects an output style for the markdown-template generator.
 */
export enum Shape {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ShapeReport = "report",
    ShapeMinimal = "minimal",
    ShapeTable = "table",
    ShapeFrontmatter = "frontmatter",
};

/**
 * ShapeInfo is the catalog record for the dialog's shape picker.
 */
export class ShapeInfo {
    "id": Shape;
    "label": string;
    "description": string;

    /** Creates a new ShapeInfo instance. */
    constructor($$source: Partial<ShapeInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = Shape.$zero;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShapeInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ShapeInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShapeInfo($$parsedSource as Partial<ShapeInfo>);
    }
}

/**
 * SubRow declares an extra editor row that appears below the main
 * option row when its triggering dropdown column's current value is
 * this one. The user's input is stored as a single pipe-delimited
 * string at row[RowKey] so the form renderer's parseChoices works
 * unchanged. Either populate Entries (fixed-arity, one input per
 * entry) OR leave it nil for a free-form add/remove pair editor.
 * LabelKey + PlaceholderKey are i18n keys.
 */
export class SubRow {
    "row_key": string;
    "label_key"?: string;
    "placeholder_key"?: string;
    "max_entries"?: number;
    "entries"?: SubRowEntry[];

    /** Creates a new SubRow instance. */
    constructor($$source: Partial<SubRow> = {}) {
        if (!("row_key" in $$source)) {
            this["row_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubRow instance from a string or object.
     */
    static createFrom($$source: any = {}): SubRow {
        const $$createField4_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField4_0($$parsedSource["entries"]);
        }
        return new SubRow($$parsedSource as Partial<SubRow>);
    }
}

/**
 * SubRowEntry is one fixed slot inside a SubRow. Each entry locks a
 * canonical Value (e.g. "true" / "false" for a bool column) - the
 * user only edits the human-readable label. LabelKey is the i18n
 * key for the gutter caption shown next to the locked value.
 */
export class SubRowEntry {
    "label_key": string;
    "value": string;
    "placeholder_key"?: string;

    /** Creates a new SubRowEntry instance. */
    constructor($$source: Partial<SubRowEntry> = {}) {
        if (!("label_key" in $$source)) {
            this["label_key"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubRowEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): SubRowEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SubRowEntry($$parsedSource as Partial<SubRowEntry>);
    }
}

/**
 * TableColumnTypeDescriptor names one column type the Edit Field
 * modal's `table` preset offers in its column-type dropdown. Today
 * these strings are pure UI vocabulary - the Go side does not yet
 * validate table cell data against them - but the registry lives
 * here so a future server-side validation pass has a single source
 * of truth to read.
 */
export class TableColumnTypeDescriptor {
    "name": string;
    "sub_row"?: SubRow | null;

    /** Creates a new TableColumnTypeDescriptor instance. */
    constructor($$source: Partial<TableColumnTypeDescriptor> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableColumnTypeDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): TableColumnTypeDescriptor {
        const $$createField1_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sub_row" in $$parsedSource) {
            $$parsedSource["sub_row"] = $$createField1_0($$parsedSource["sub_row"]);
        }
        return new TableColumnTypeDescriptor($$parsedSource as Partial<TableColumnTypeDescriptor>);
    }
}

/**
 * Template is the on-disk shape of a template YAML file.
 * 
 * AuthorName / AuthorEmail mirror the per-record author identity that
 * storage/<tpl>/<n>.meta.json carries in its meta envelope. They sit at
 * the YAML root (templates have no separate meta block) and are
 * auto-filled from config.author_name / config.author_email by
 * SaveTemplate when the caller leaves them empty. Purpose: PullWithStash
 * can name "who last touched this template" without walking git log,
 * matching how it identifies record overrides.
 */
export class Template {
    "name": string;
    "filename": string;
    "author_name"?: string;
    "author_email"?: string;
    "item_field": string;
    "markdown_template": string;
    "sidebar_expression": string;
    "enable_collection": boolean;
    "pdf"?: PDFConfig | null;
    "facets": Facet[];
    "fields": Field[];
    "needs_resave": boolean;

    /** Creates a new Template instance. */
    constructor($$source: Partial<Template> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("item_field" in $$source)) {
            this["item_field"] = "";
        }
        if (!("markdown_template" in $$source)) {
            this["markdown_template"] = "";
        }
        if (!("sidebar_expression" in $$source)) {
            this["sidebar_expression"] = "";
        }
        if (!("enable_collection" in $$source)) {
            this["enable_collection"] = false;
        }
        if (!("facets" in $$source)) {
            this["facets"] = [];
        }
        if (!("fields" in $$source)) {
            this["fields"] = [];
        }
        if (!("needs_resave" in $$source)) {
            this["needs_resave"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Template instance from a string or object.
     */
    static createFrom($$source: any = {}): Template {
        const $$createField8_0 = $$createType27;
        const $$createField9_0 = $$createType29;
        const $$createField10_0 = $$createType30;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pdf" in $$parsedSource) {
            $$parsedSource["pdf"] = $$createField8_0($$parsedSource["pdf"]);
        }
        if ("facets" in $$parsedSource) {
            $$parsedSource["facets"] = $$createField9_0($$parsedSource["facets"]);
        }
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField10_0($$parsedSource["fields"]);
        }
        return new Template($$parsedSource as Partial<Template>);
    }
}

/**
 * ValidationError is one issue found by Validate.
 */
export class ValidationError {
    "type": string;
    "message"?: string;
    "key"?: string;
    "keys"?: string[];
    "field"?: Field | null;
    "index"?: number;
    "detail"?: { [_ in string]?: any };

    /** Creates a new ValidationError instance. */
    constructor($$source: Partial<ValidationError> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidationError instance from a string or object.
     */
    static createFrom($$source: any = {}): ValidationError {
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType14;
        const $$createField6_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keys" in $$parsedSource) {
            $$parsedSource["keys"] = $$createField3_0($$parsedSource["keys"]);
        }
        if ("field" in $$parsedSource) {
            $$parsedSource["field"] = $$createField4_0($$parsedSource["field"]);
        }
        if ("detail" in $$parsedSource) {
            $$parsedSource["detail"] = $$createField6_0($$parsedSource["detail"]);
        }
        return new ValidationError($$parsedSource as Partial<ValidationError>);
    }
}

// Private type creation functions
const $$createType0 = Template.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = FacetOption.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = FacetIconSpec.createFrom;
const $$createType6 = $Create.Map($Create.Any, $$createType5);
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = APIMap.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = Abilities.createFrom;
const $$createType11 = FixedOptionsShape.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = Field.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = FieldUnit.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $Create.Map($Create.Any, $Create.Any);
const $$createType18 = FixedOptionRow.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = SubRow.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = PDFCoverConfig.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = SubRowEntry.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = PDFConfig.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = Facet.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = $Create.Array($$createType13);
