// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * APIMap is one entry in an api field's map[].
 */
export class APIMap {
    "key": string;
    "path"?: string;
    "mode"?: string;

    /** Creates a new APIMap instance. */
    constructor($$source: Partial<APIMap> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APIMap instance from a string or object.
     */
    static createFrom($$source: any = {}): APIMap {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APIMap($$parsedSource as Partial<APIMap>);
    }
}

/**
 * Descriptor is the {name, yaml, storageLocation} bundle returned by
 * GetDescriptor. Mirrors templateManager.getTemplateDescriptor.
 */
export class Descriptor {
    "name": string;
    "yaml": Template | null;
    "storageLocation": string;

    /** Creates a new Descriptor instance. */
    constructor($$source: Partial<Descriptor> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("yaml" in $$source)) {
            this["yaml"] = null;
        }
        if (!("storageLocation" in $$source)) {
            this["storageLocation"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Descriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): Descriptor {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("yaml" in $$parsedSource) {
            $$parsedSource["yaml"] = $$createField1_0($$parsedSource["yaml"]);
        }
        return new Descriptor($$parsedSource as Partial<Descriptor>);
    }
}

/**
 * Field describes one input in a template. Type-specific properties
 * (run_mode, options, collection, etc.) sit alongside the common ones —
 * downstream consumers ignore irrelevant fields.
 */
export class Field {
    /**
     * Common
     */
    "key": string;
    "type": string;
    "label": string;
    "description": string;
    "summary_field"?: string;
    "expression_item": boolean;
    "two_column": boolean;
    "collapsible"?: boolean | null;
    "readonly": boolean;
    "default": any;
    "options": any[];
    "primary_key"?: boolean;

    /**
     * textarea-specific
     */
    "format"?: string;

    /**
     * latex-specific
     */
    "rows"?: number | null;
    "use_fenced"?: boolean | null;
    "placeholder"?: string;

    /**
     * code-specific
     */
    "run_mode"?: string;
    "allow_run"?: boolean | null;
    "hide_field"?: boolean | null;
    "input_mode"?: string;
    "api_mode"?: string;
    "api_pick"?: string[];

    /**
     * api-specific
     */
    "collection"?: string;
    "id"?: string;
    "map"?: APIMap[];
    "use_picker"?: boolean | null;
    "allowed_ids"?: string[];

    /** Creates a new Field instance. */
    constructor($$source: Partial<Field> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("expression_item" in $$source)) {
            this["expression_item"] = false;
        }
        if (!("two_column" in $$source)) {
            this["two_column"] = false;
        }
        if (!("readonly" in $$source)) {
            this["readonly"] = false;
        }
        if (!("default" in $$source)) {
            this["default"] = null;
        }
        if (!("options" in $$source)) {
            this["options"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Field instance from a string or object.
     */
    static createFrom($$source: any = {}): Field {
        const $$createField10_0 = $$createType2;
        const $$createField21_0 = $$createType3;
        const $$createField24_0 = $$createType5;
        const $$createField26_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField10_0($$parsedSource["options"]);
        }
        if ("api_pick" in $$parsedSource) {
            $$parsedSource["api_pick"] = $$createField21_0($$parsedSource["api_pick"]);
        }
        if ("map" in $$parsedSource) {
            $$parsedSource["map"] = $$createField24_0($$parsedSource["map"]);
        }
        if ("allowed_ids" in $$parsedSource) {
            $$parsedSource["allowed_ids"] = $$createField26_0($$parsedSource["allowed_ids"]);
        }
        return new Field($$parsedSource as Partial<Field>);
    }
}

/**
 * FieldTypeDef declares a known field type and the optional Field
 * properties it forbids. `MetaOnly` flags the marker types (looper,
 * loopstart, loopstop) that don't carry a stored value but still
 * participate in validation.
 * 
 * JSON tags are present because FieldTypeDef is also the Wails-facing
 * shape returned by Service.FieldTypes — the frontend uses it as the
 * single source of truth for "what types exist and what they forbid".
 */
export class FieldTypeDef {
    "id": string;
    "meta_only": boolean;
    "forbidden_attributes": string[];

    /** Creates a new FieldTypeDef instance. */
    constructor($$source: Partial<FieldTypeDef> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("meta_only" in $$source)) {
            this["meta_only"] = false;
        }
        if (!("forbidden_attributes" in $$source)) {
            this["forbidden_attributes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FieldTypeDef instance from a string or object.
     */
    static createFrom($$source: any = {}): FieldTypeDef {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("forbidden_attributes" in $$parsedSource) {
            $$parsedSource["forbidden_attributes"] = $$createField2_0($$parsedSource["forbidden_attributes"]);
        }
        return new FieldTypeDef($$parsedSource as Partial<FieldTypeDef>);
    }
}

/**
 * ImgMode selects how image fields are emitted.
 * 
 * 	url    — `![Label]({{imageURL "key"}})`. The runtime helper resolves
 * 	         to whatever the consumer's render.Manager is wired to
 * 	         (slideout: /api/images/<stem>/<file>; wiki: /storage/...).
 * 	inline — `![Label]({{imageBase64 "key"}})`. The bytes are inlined as
 * 	         a `data:<mime>;base64,…` URL at render time. Use for
 * 	         self-contained exports (single-file HTML/PDF/wiki import).
 */
export enum ImgMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ImgURL = "url",
    ImgInline = "inline",
};

/**
 * ImgModeInfo is the corresponding catalog entry for image modes.
 */
export class ImgModeInfo {
    "id": ImgMode;
    "label": string;
    "description": string;

    /** Creates a new ImgModeInfo instance. */
    constructor($$source: Partial<ImgModeInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = ImgMode.$zero;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImgModeInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ImgModeInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImgModeInfo($$parsedSource as Partial<ImgModeInfo>);
    }
}

/**
 * ItemField is one row in the "possible item fields" picker (top-level
 * non-loop text fields, used to choose a collection's primary identifier).
 */
export class ItemField {
    "key": string;
    "label": string;

    /** Creates a new ItemField instance. */
    constructor($$source: Partial<ItemField> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ItemField instance from a string or object.
     */
    static createFrom($$source: any = {}): ItemField {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ItemField($$parsedSource as Partial<ItemField>);
    }
}

/**
 * Shape selects an output style for the markdown-template generator.
 * 
 * Why a string-typed enum: the value crosses the Wails boundary and is
 * chosen by the user in a Vue dialog. Bare strings keep the binding
 * simple — no per-shape constructor on the frontend.
 */
export enum Shape {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ShapeReport = "report",
    ShapeMinimal = "minimal",
    ShapeTable = "table",
    ShapeFrontmatter = "frontmatter",
};

/**
 * ShapeInfo is a UI-facing record so the frontend doesn't have to
 * hardcode shape labels — vue-i18n would also work but the dialog has
 * a small static set, so descriptions live next to the implementation.
 */
export class ShapeInfo {
    "id": Shape;
    "label": string;
    "description": string;

    /** Creates a new ShapeInfo instance. */
    constructor($$source: Partial<ShapeInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = Shape.$zero;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShapeInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ShapeInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShapeInfo($$parsedSource as Partial<ShapeInfo>);
    }
}

/**
 * Template is the on-disk shape of a template YAML file.
 */
export class Template {
    "name": string;
    "filename": string;
    "item_field": string;
    "markdown_template": string;
    "sidebar_expression": string;
    "enable_collection": boolean;
    "fields": Field[];

    /** Creates a new Template instance. */
    constructor($$source: Partial<Template> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("item_field" in $$source)) {
            this["item_field"] = "";
        }
        if (!("markdown_template" in $$source)) {
            this["markdown_template"] = "";
        }
        if (!("sidebar_expression" in $$source)) {
            this["sidebar_expression"] = "";
        }
        if (!("enable_collection" in $$source)) {
            this["enable_collection"] = false;
        }
        if (!("fields" in $$source)) {
            this["fields"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Template instance from a string or object.
     */
    static createFrom($$source: any = {}): Template {
        const $$createField6_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField6_0($$parsedSource["fields"]);
        }
        return new Template($$parsedSource as Partial<Template>);
    }
}

/**
 * ValidationError is one issue found by Validate.
 */
export class ValidationError {
    "type": string;
    "message"?: string;
    "key"?: string;
    "keys"?: string[];
    "field"?: Field | null;
    "index"?: number;
    "detail"?: { [_ in string]?: any };

    /** Creates a new ValidationError instance. */
    constructor($$source: Partial<ValidationError> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidationError instance from a string or object.
     */
    static createFrom($$source: any = {}): ValidationError {
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType8;
        const $$createField6_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keys" in $$parsedSource) {
            $$parsedSource["keys"] = $$createField3_0($$parsedSource["keys"]);
        }
        if ("field" in $$parsedSource) {
            $$parsedSource["field"] = $$createField4_0($$parsedSource["field"]);
        }
        if ("detail" in $$parsedSource) {
            $$parsedSource["detail"] = $$createField6_0($$parsedSource["detail"]);
        }
        return new ValidationError($$parsedSource as Partial<ValidationError>);
    }
}

// Private type creation functions
const $$createType0 = Template.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = APIMap.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = Field.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Nullable($$createType6);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
