// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the api layer over Manager. Method names mirror old
 * `window.api.templates.*` IPC group (camelCase'd → PascalCase).
 * 
 * Composition note: the storageLocation passed to GetDescriptor is
 * supplied by the composition root, which knows about config's VFS.
 * Keeps this module independent of config.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteTemplate(name: string): $CancellablePromise<void> {
    return $Call.ByID(2279610857, name);
}

export function EnsureTemplateDirectory(): $CancellablePromise<void> {
    return $Call.ByID(2374943147);
}

export function GetItemFields(name: string): $CancellablePromise<$models.ItemField[]> {
    return $Call.ByID(2544545530, name).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetTemplateDescriptor(name: string): $CancellablePromise<$models.Descriptor> {
    return $Call.ByID(3235934315, name).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListTemplates(): $CancellablePromise<string[]> {
    return $Call.ByID(3379098355).then(($result: any) => {
        return $$createType3($result);
    });
}

export function LoadTemplate(name: string): $CancellablePromise<$models.Template | null> {
    return $Call.ByID(2817786054, name).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SaveTemplate(name: string, t: $models.Template | null): $CancellablePromise<void> {
    return $Call.ByID(204227971, name, t);
}

export function SeedBasicIfEmpty(): $CancellablePromise<void> {
    return $Call.ByID(361458899);
}

export function ValidateTemplate(t: $models.Template | null): $CancellablePromise<$models.ValidationError[]> {
    return $Call.ByID(1604219816, t).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ItemField.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Descriptor.createFrom;
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $models.Template.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.ValidationError.createFrom;
const $$createType7 = $Create.Array($$createType6);
