// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * FixOutcome is the per-form summary of what changed.
 */
export class FixOutcome {
    "filename": string;
    "applied": number;
    "skipped": number;
    "saved": boolean;
    "notes"?: string[];

    /** Creates a new FixOutcome instance. */
    constructor($$source: Partial<FixOutcome> = {}) {
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("applied" in $$source)) {
            this["applied"] = 0;
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = 0;
        }
        if (!("saved" in $$source)) {
            this["saved"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FixOutcome instance from a string or object.
     */
    static createFrom($$source: any = {}): FixOutcome {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("notes" in $$parsedSource) {
            $$parsedSource["notes"] = $$createField4_0($$parsedSource["notes"]);
        }
        return new FixOutcome($$parsedSource as Partial<FixOutcome>);
    }
}

/**
 * FixPlan is the bundle the frontend submits to Fix.
 */
export class FixPlan {
    "items": FixPlanItem[];

    /** Creates a new FixPlan instance. */
    constructor($$source: Partial<FixPlan> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FixPlan instance from a string or object.
     */
    static createFrom($$source: any = {}): FixPlan {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new FixPlan($$parsedSource as Partial<FixPlan>);
    }
}

/**
 * FixPlanItem maps one issue kind to one strategy (at most one item per kind).
 */
export class FixPlanItem {
    "kind": IssueKind;
    "strategy": FixStrategy;

    /** Creates a new FixPlanItem instance. */
    constructor($$source: Partial<FixPlanItem> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = IssueKind.$zero;
        }
        if (!("strategy" in $$source)) {
            this["strategy"] = FixStrategy.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FixPlanItem instance from a string or object.
     */
    static createFrom($$source: any = {}): FixPlanItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FixPlanItem($$parsedSource as Partial<FixPlanItem>);
    }
}

/**
 * FixResult is the aggregate Fix response; ScannedAfter is a fresh analyze count so the UI can show "Y remain".
 */
export class FixResult {
    "forms_touched": number;
    "forms_saved": number;
    "applied": number;
    "skipped": number;
    "scanned_after": number;
    "outcomes"?: FixOutcome[];

    /** Creates a new FixResult instance. */
    constructor($$source: Partial<FixResult> = {}) {
        if (!("forms_touched" in $$source)) {
            this["forms_touched"] = 0;
        }
        if (!("forms_saved" in $$source)) {
            this["forms_saved"] = 0;
        }
        if (!("applied" in $$source)) {
            this["applied"] = 0;
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = 0;
        }
        if (!("scanned_after" in $$source)) {
            this["scanned_after"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FixResult instance from a string or object.
     */
    static createFrom($$source: any = {}): FixResult {
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("outcomes" in $$parsedSource) {
            $$parsedSource["outcomes"] = $$createField5_0($$parsedSource["outcomes"]);
        }
        return new FixResult($$parsedSource as Partial<FixResult>);
    }
}

/**
 * FixStrategy names a concrete repair action; the set is closed and unknown strategies fail at Fix-time.
 */
export enum FixStrategy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * FixStrip removes an orphaned data key (extra_field).
     */
    FixStrip = "strip",

    /**
     * FixFillDefault writes the per-type default for a missing field.
     */
    FixFillDefault = "fill_default",

    /**
     * FixCoerce converts a wrong-typed value to the declared type; failures are reported skipped.
     */
    FixCoerce = "coerce",

    /**
     * FixClear wipes a populated-but-wrong value back to the per-type default.
     */
    FixClear = "clear",

    /**
     * FixMintUUID generates a fresh meta.id (meta_missing on guid templates).
     */
    FixMintUUID = "mint_uuid",

    /**
     * FixSyncGuid writes meta.id (canonical) into the guid data field.
     */
    FixSyncGuid = "sync_guid",

    /**
     * FixRestamp overwrites a bad timestamp with now, or clears a stale facet label (same intent: make it valid).
     */
    FixRestamp = "restamp",

    /**
     * FixSeedFacet writes the facet field's default onto a form whose disk is missing that facet (facet_unseeded).
     */
    FixSeedFacet = "seed_facet",

    /**
     * FixSkip leaves the issue alone; the sentinel for kinds with no in-app repair (unreadable).
     */
    FixSkip = "skip",
};

/**
 * FormReport groups every issue in one form; Filename is the .meta.json basename.
 */
export class FormReport {
    "filename": string;
    "issues": Issue[];

    /** Creates a new FormReport instance. */
    constructor($$source: Partial<FormReport> = {}) {
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("issues" in $$source)) {
            this["issues"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FormReport instance from a string or object.
     */
    static createFrom($$source: any = {}): FormReport {
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField1_0($$parsedSource["issues"]);
        }
        return new FormReport($$parsedSource as Partial<FormReport>);
    }
}

/**
 * Issue is one problem in one form; Path is a data location ("key" / "loopKey[idx].field") or a meta key.
 */
export class Issue {
    "kind": IssueKind;
    "path"?: string;
    "detail"?: string;

    /**
     * Value is the offending value as a literal string, for the user to see (e.g. hand-fixed date anomalies).
     */
    "value"?: string;

    /**
     * Suggest is a resolved value the fixer writes verbatim (e.g. the conformant ISO for an inferred date column).
     */
    "suggest"?: string;

    /** Creates a new Issue instance. */
    constructor($$source: Partial<Issue> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = IssueKind.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Issue instance from a string or object.
     */
    static createFrom($$source: any = {}): Issue {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Issue($$parsedSource as Partial<Issue>);
    }
}

/**
 * IssueKind enumerates structural problems in a stored form; the string values are stable wire identifiers.
 */
export enum IssueKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * IssueMissingField: template declares a key with no data entry (form predates the field).
     */
    IssueMissingField = "missing_field",

    /**
     * IssueExtraField: data has a key the template no longer declares (renamed/deleted field).
     */
    IssueExtraField = "extra_field",

    /**
     * IssueTypeMismatch: the value isn't assignable to the field's declared type.
     */
    IssueTypeMismatch = "type_mismatch",

    /**
     * IssueBadDateFormat: a non-ISO date. For table date columns only conforming values get this, with the
     * resolved ISO in Suggest so the fixer converts deterministically (no re-guessing).
     */
    IssueBadDateFormat = "bad_date_format",

    /**
     * IssueDateAnomaly: a table date cell that doesn't fit the column's inferred format. No safe auto-conversion:
     * surfaced for manual fix (Clear/Skip, not Coerce).
     */
    IssueDateAnomaly = "date_anomaly",

    /**
     * IssueMetaMissing: a required meta key is empty.
     */
    IssueMetaMissing = "meta_missing",

    /**
     * IssueMetaBadFormat: meta.created/updated isn't a parseable RFC3339 timestamp.
     */
    IssueMetaBadFormat = "meta_bad_format",

    /**
     * IssueGuidUnsynced: the data guid field disagrees with meta.id. Suggest carries meta.id so the fix is verbatim.
     */
    IssueGuidUnsynced = "guid_unsynced",

    /**
     * IssueDuplicateGuid: this record's guid is shared by another record in the collection (a cross-record
     * check, not per-form). The alphabetically-first holder is canonical; the rest are flagged. Value carries
     * the duplicated guid. The fix mints a fresh guid (meta.id + the data guid field). Edges that referenced
     * the ambiguous guid can't be auto-reattributed, so prevention at save is the real guard; this heals drift.
     */
    IssueDuplicateGuid = "duplicate_guid",

    /**
     * IssueUnreadable: the form file couldn't be loaded or parsed; emitted as the single issue.
     */
    IssueUnreadable = "unreadable",

    /**
     * IssueFacetNoDefault: a facet bound to a virtual field that declares no default. Template-level
     * and informational: forms without an explicit selection stay empty, with no default to auto-fill.
     */
    IssueFacetNoDefault = "facet_no_default",

    /**
     * IssueFacetUnseeded: a form's disk is missing a facet the template defaults. Suggest carries the
     * default so the fixer seeds it; detected via the raw form, since a sanitized load would seed it
     * in memory and hide the gap.
     */
    IssueFacetUnseeded = "facet_unseeded",
};

/**
 * Report is the result of AnalyzeTemplate; only forms with issues appear in Forms.
 * TemplateIssues are template-level, informational findings (not per-form drift) and
 * are kept out of IssueCount so a clean-forms template isn't reported dirty.
 */
export class Report {
    "template": string;
    "form_count": number;
    "issue_count": number;
    "scanned_at": time$0.Time;
    "forms"?: FormReport[];
    "template_issues"?: Issue[];

    /** Creates a new Report instance. */
    constructor($$source: Partial<Report> = {}) {
        if (!("template" in $$source)) {
            this["template"] = "";
        }
        if (!("form_count" in $$source)) {
            this["form_count"] = 0;
        }
        if (!("issue_count" in $$source)) {
            this["issue_count"] = 0;
        }
        if (!("scanned_at" in $$source)) {
            this["scanned_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Report instance from a string or object.
     */
    static createFrom($$source: any = {}): Report {
        const $$createField4_0 = $$createType8;
        const $$createField5_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("forms" in $$parsedSource) {
            $$parsedSource["forms"] = $$createField4_0($$parsedSource["forms"]);
        }
        if ("template_issues" in $$parsedSource) {
            $$parsedSource["template_issues"] = $$createField5_0($$parsedSource["template_issues"]);
        }
        return new Report($$parsedSource as Partial<Report>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = FixPlanItem.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = FixOutcome.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = Issue.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = FormReport.createFrom;
const $$createType8 = $Create.Array($$createType7);
