// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound facade over Manager. Held by app.App
 * and registered as a Wails service in main.go.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * List returns every discovered plugin, sorted by id.
 */
export function List(): $CancellablePromise<$models.ListResult[]> {
    return $Call.ByID(2326066151).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Refresh re-scans the plugins folder. Returns the new list so
 * Vue can update without a follow-up call.
 */
export function Refresh(): $CancellablePromise<$models.ListResult[]> {
    return $Call.ByID(2866253602).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Run invokes a command. ctx is an optional plain-JSON table that
 * arrives in Lua as the function's single argument. Errors are
 * classified rather than returned directly so the frontend can
 * branch deterministically: a missing plugin / unknown command /
 * load error / runtime error each get a distinct kind.
 */
export function Run(pluginID: string, commandID: string, ctx: { [_ in string]?: any }): $CancellablePromise<$models.RunResultDTO> {
    return $Call.ByID(2749798520, pluginID, commandID, ctx).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ListResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.RunResultDTO.createFrom;
