// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound facade over Manager. Held by app.App
 * and registered as a Wails service in main.go.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create scaffolds a new plugin folder and returns the new list.
 * Errors map to the editor sentinels (ErrManifestInvalid,
 * ErrPluginExists) — the caller surfaces them as i18n'd toasts.
 */
export function Create(id: string): $CancellablePromise<$models.ListResult[]> {
    return $Call.ByID(2899368391, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Delete removes the plugin folder and KV file, returning the
 * updated list.
 */
export function Delete(id: string): $CancellablePromise<$models.ListResult[]> {
    return $Call.ByID(3327307900, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetForm returns the raw form.json text for an existing plugin.
 * If form.json is missing (legacy or hand-edited folder), returns
 * the default empty-array placeholder so callers don't have to
 * special-case the absence.
 */
export function GetForm(id: string): $CancellablePromise<string> {
    return $Call.ByID(3310235139, id);
}

/**
 * GetSource returns the plugin's main.lua content. Used by the
 * workspace to populate the Lua editor when a plugin is selected.
 */
export function GetSource(id: string): $CancellablePromise<string> {
    return $Call.ByID(4259078820, id);
}

/**
 * List returns every discovered plugin, sorted by id.
 */
export function List(): $CancellablePromise<$models.ListResult[]> {
    return $Call.ByID(2326066151).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Refresh re-scans the plugins folder. Returns the new list so
 * Vue can update without a follow-up call.
 */
export function Refresh(): $CancellablePromise<$models.ListResult[]> {
    return $Call.ByID(2866253602).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Run invokes a command. ctx is an optional plain-JSON table that
 * arrives in Lua as the function's single argument. Errors are
 * classified rather than returned directly so the frontend can
 * branch deterministically: a missing plugin / unknown command /
 * load error / runtime error each get a distinct kind.
 */
export function Run(pluginID: string, commandID: string, ctx: { [_ in string]?: any }): $CancellablePromise<$models.RunResultDTO> {
    return $Call.ByID(2749798520, pluginID, commandID, ctx).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Save writes plugin.json + main.lua + form.json for an existing
 * plugin and returns the updated list. formJSON is the raw text
 * of the field schema; pass "" to leave form.json untouched.
 */
export function Save(id: string, manifest: $models.Manifest, luaSource: string, formJSON: string): $CancellablePromise<$models.ListResult[]> {
    return $Call.ByID(2781827402, id, manifest, luaSource, formJSON).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ListResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.RunResultDTO.createFrom;
