// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Cardinality is the shape of a relation. The three the user specified.
 */
export enum Cardinality {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OneToOne = "one-to-one",
    OneToMany = "one-to-many",
    ManyToOne = "many-to-one",
    ManyToMany = "many-to-many",

    /**
     * defaultCardinality is the cardinality a freshly added relation starts on.
     */
    defaultCardinality = "one-to-many",
};

/**
 * CardinalityOption pairs a cardinality value with its i18n label key and whether it is the default
 * pick for a NEW relation, so the frontend keeps no value->key mapping and no default of its own
 * (backend steers the labels and the default, like field-type descriptors carry their own metadata).
 * SourceMany is whether the source side may link many targets under this cardinality, so the
 * api-field UI reads single-vs-multi from the backend instead of re-deriving the rule.
 */
export class CardinalityOption {
    "value": Cardinality;
    "label_key": string;
    "default"?: boolean;
    "source_many": boolean;

    /** Creates a new CardinalityOption instance. */
    constructor($$source: Partial<CardinalityOption> = {}) {
        if (!("value" in $$source)) {
            this["value"] = Cardinality.$zero;
        }
        if (!("label_key" in $$source)) {
            this["label_key"] = "";
        }
        if (!("source_many" in $$source)) {
            this["source_many"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CardinalityOption instance from a string or object.
     */
    static createFrom($$source: any = {}): CardinalityOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CardinalityOption($$parsedSource as Partial<CardinalityOption>);
    }
}

/**
 * Conflict is a pair stored on both sides whose cardinalities are not each other's inverse.
 */
export class Conflict {
    "a": string;
    "a_cardinality": Cardinality;
    "b": string;
    "b_cardinality": Cardinality;

    /** Creates a new Conflict instance. */
    constructor($$source: Partial<Conflict> = {}) {
        if (!("a" in $$source)) {
            this["a"] = "";
        }
        if (!("a_cardinality" in $$source)) {
            this["a_cardinality"] = Cardinality.$zero;
        }
        if (!("b" in $$source)) {
            this["b"] = "";
        }
        if (!("b_cardinality" in $$source)) {
            this["b_cardinality"] = Cardinality.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Conflict instance from a string or object.
     */
    static createFrom($$source: any = {}): Conflict {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Conflict($$parsedSource as Partial<Conflict>);
    }
}

/**
 * Counterpart is one recreated relation half (written into Template, pointing at To).
 */
export class Counterpart {
    "template": string;
    "to": string;
    "cardinality": Cardinality;

    /** Creates a new Counterpart instance. */
    constructor($$source: Partial<Counterpart> = {}) {
        if (!("template" in $$source)) {
            this["template"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }
        if (!("cardinality" in $$source)) {
            this["cardinality"] = Cardinality.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Counterpart instance from a string or object.
     */
    static createFrom($$source: any = {}): Counterpart {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Counterpart($$parsedSource as Partial<Counterpart>);
    }
}

/**
 * Edge is one record-to-record link: a source record id to a target record id (the actual
 * relating, by id, never stored in form data).
 */
export class Edge {
    "from": string;
    "to": string;

    /** Creates a new Edge instance. */
    constructor($$source: Partial<Edge> = {}) {
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Edge instance from a string or object.
     */
    static createFrom($$source: any = {}): Edge {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Edge($$parsedSource as Partial<Edge>);
    }
}

/**
 * ReconcileReport is the outcome of a self-heal pass.
 */
export class ReconcileReport {
    /**
     * Created lists relation counterparts that were missing and got recreated from the surviving
     * side (with that side's edges reversed onto the new half).
     */
    "created": Counterpart[];

    /**
     * EdgesHealed counts reversed edges added to bring the two sides' edge sets back into agreement.
     */
    "edges_healed": number;

    /**
     * Conflicts lists pairs present on both sides whose cardinalities disagree. These are left
     * untouched: with no owner there is no safe way to pick a winner, so they are surfaced for the
     * user to resolve (doctor-style: heal the unambiguous, flag the outliers).
     */
    "conflicts": Conflict[];

    /** Creates a new ReconcileReport instance. */
    constructor($$source: Partial<ReconcileReport> = {}) {
        if (!("created" in $$source)) {
            this["created"] = [];
        }
        if (!("edges_healed" in $$source)) {
            this["edges_healed"] = 0;
        }
        if (!("conflicts" in $$source)) {
            this["conflicts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReconcileReport instance from a string or object.
     */
    static createFrom($$source: any = {}): ReconcileReport {
        const $$createField0_0 = $$createType1;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("created" in $$parsedSource) {
            $$parsedSource["created"] = $$createField0_0($$parsedSource["created"]);
        }
        if ("conflicts" in $$parsedSource) {
            $$parsedSource["conflicts"] = $$createField2_0($$parsedSource["conflicts"]);
        }
        return new ReconcileReport($$parsedSource as Partial<ReconcileReport>);
    }
}

/**
 * Relation is one declared relation from a template to another template, plus its edges. It is
 * identified entirely by its target: the source is the owning file, and there is at most one
 * relation per from -> to pair, so no name is needed. Inverse marks which side of the pair is the
 * derived mirror; the two halves always carry opposite Inverse values (see the mirroring in
 * SetRelations and Reconcile).
 */
export class Relation {
    "to": string;
    "cardinality": Cardinality;
    "inverse"?: boolean;
    "edges"?: Edge[];

    /** Creates a new Relation instance. */
    constructor($$source: Partial<Relation> = {}) {
        if (!("to" in $$source)) {
            this["to"] = "";
        }
        if (!("cardinality" in $$source)) {
            this["cardinality"] = Cardinality.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Relation instance from a string or object.
     */
    static createFrom($$source: any = {}): Relation {
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField3_0($$parsedSource["edges"]);
        }
        return new Relation($$parsedSource as Partial<Relation>);
    }
}

// Private type creation functions
const $$createType0 = Counterpart.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Conflict.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Edge.createFrom;
const $$createType5 = $Create.Array($$createType4);
