// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Cardinality is the shape of a relation. The three the user specified.
 */
export enum Cardinality {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OneToOne = "one-to-one",
    OneToMany = "one-to-many",
    ManyToMany = "many-to-many",
};

/**
 * Edge is one record-to-record link: a source record id to a target record id (the actual
 * relating, by id, never stored in form data).
 */
export class Edge {
    "from": string;
    "to": string;

    /** Creates a new Edge instance. */
    constructor($$source: Partial<Edge> = {}) {
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Edge instance from a string or object.
     */
    static createFrom($$source: any = {}): Edge {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Edge($$parsedSource as Partial<Edge>);
    }
}

/**
 * Relation is one declared relation from a template to another template, plus its edges.
 */
export class Relation {
    "name": string;
    "to": string;
    "cardinality": Cardinality;
    "edges"?: Edge[];

    /** Creates a new Relation instance. */
    constructor($$source: Partial<Relation> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }
        if (!("cardinality" in $$source)) {
            this["cardinality"] = Cardinality.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Relation instance from a string or object.
     */
    static createFrom($$source: any = {}): Relation {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField3_0($$parsedSource["edges"]);
        }
        return new Relation($$parsedSource as Partial<Relation>);
    }
}

// Private type creation functions
const $$createType0 = Edge.createFrom;
const $$createType1 = $Create.Array($$createType0);
