// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-facing surface over Manager: get and set a template's relations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddEdge links two records through the relation from template to `to`.
 */
export function AddEdge(template: string, to: string, edge: $models.Edge): $CancellablePromise<void> {
    return $Call.ByID(4126420296, template, to, edge);
}

/**
 * GetRelations returns the relations declared by a template.
 */
export function GetRelations(template: string): $CancellablePromise<$models.Relation[]> {
    return $Call.ByID(105264407, template).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RemoveEdge unlinks two records from the relation from template to `to`.
 */
export function RemoveEdge(template: string, to: string, edge: $models.Edge): $CancellablePromise<void> {
    return $Call.ByID(1742361031, template, to, edge);
}

/**
 * SetRelations replaces and persists a template's relations.
 */
export function SetRelations(template: string, relations: $models.Relation[]): $CancellablePromise<void> {
    return $Call.ByID(1453491451, template, relations);
}

// Private type creation functions
const $$createType0 = $models.Relation.createFrom;
const $$createType1 = $Create.Array($$createType0);
