// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-facing surface over Manager: get and set a template's relations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddEdge links a source record to a target record (and mirrors the reversed edge).
 */
export function AddEdge(source: string, target: string, edge: $models.Edge): $CancellablePromise<void> {
    return $Call.ByID(4126420296, source, target, edge);
}

/**
 * Cardinalities returns the cardinality picker options (value + label key) for
 * the editor, so the frontend keeps no value->label mapping of its own.
 */
export function Cardinalities(): $CancellablePromise<$models.CardinalityOption[]> {
    return $Call.ByID(2310858626).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetRelations returns the relations declared by a template.
 */
export function GetRelations(template: string): $CancellablePromise<$models.Relation[]> {
    return $Call.ByID(105264407, template).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Reconcile runs a self-heal pass: recreate missing counterparts and report cardinality conflicts.
 */
export function Reconcile(): $CancellablePromise<$models.ReconcileReport> {
    return $Call.ByID(2004044918).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * RemoveEdge unlinks a source record from a target record (and removes the mirror).
 */
export function RemoveEdge(source: string, target: string, edge: $models.Edge): $CancellablePromise<void> {
    return $Call.ByID(1742361031, source, target, edge);
}

/**
 * SetRelations replaces and persists a template's relations.
 */
export function SetRelations(template: string, relations: $models.Relation[]): $CancellablePromise<void> {
    return $Call.ByID(1453491451, template, relations);
}

// Private type creation functions
const $$createType0 = $models.CardinalityOption.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Relation.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.ReconcileReport.createFrom;
