// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * ActivateOpts carries the activation choices the user made in the
 * Information-page dialog.
 * 
 *   - BrowserBin: when set, skip probing and use this path directly.
 *     When empty, the prober runs and the first candidate is picked.
 * 
 * Formidable does not bundle or download Chrome — if no candidate
 * is found, the user must install one (or point ROD_BROWSER_BIN at
 * one) themselves.
 */
export class ActivateOpts {
    "browser_bin"?: string;

    /** Creates a new ActivateOpts instance. */
    constructor($$source: Partial<ActivateOpts> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActivateOpts instance from a string or object.
     */
    static createFrom($$source: any = {}): ActivateOpts {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActivateOpts($$parsedSource as Partial<ActivateOpts>);
    }
}

/**
 * ChromeCandidate is one entry returned by ProbeChrome — a Chrome/
 * Chromium binary the activation flow can adopt. Version is best-
 * effort (resolved by running `<path> --version`) and may be empty
 * when the binary refuses to run or the call times out.
 */
export class ChromeCandidate {
    "path": string;
    "source": Source;
    "version"?: string;

    /** Creates a new ChromeCandidate instance. */
    constructor($$source: Partial<ChromeCandidate> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = Source.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChromeCandidate instance from a string or object.
     */
    static createFrom($$source: any = {}): ChromeCandidate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChromeCandidate($$parsedSource as Partial<ChromeCandidate>);
    }
}

/**
 * CoverDescriptor is one entry in the cover-picker dropdown. Returned
 * by ListCovers; consumed by the frontend.
 * 
 *   - Name: filename stem (the value users put in `cover.template:`).
 *   - Label: human-readable display name from the magic-line `name:`
 *     field, or capitalised Name when absent.
 *   - Description: from the magic-line `description:` field, or "".
 *   - OK: false when ValidateCover errored — the picker may still
 *     surface the entry, but flagged.
 */
export class CoverDescriptor {
    "name": string;
    "label": string;
    "description": string;
    "ok": boolean;

    /** Creates a new CoverDescriptor instance. */
    constructor($$source: Partial<CoverDescriptor> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CoverDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): CoverDescriptor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CoverDescriptor($$parsedSource as Partial<CoverDescriptor>);
    }
}

/**
 * CoverIssue is one finding from the validator. Codes are stable for
 * the lifetime of CurrentCoverSchemaVersion so the frontend can pin
 * translations / per-issue help.
 */
export class CoverIssue {
    "severity": CoverIssueSeverity;
    "code": string;
    "message": string;

    /** Creates a new CoverIssue instance. */
    constructor($$source: Partial<CoverIssue> = {}) {
        if (!("severity" in $$source)) {
            this["severity"] = CoverIssueSeverity.$zero;
        }
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CoverIssue instance from a string or object.
     */
    static createFrom($$source: any = {}): CoverIssue {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CoverIssue($$parsedSource as Partial<CoverIssue>);
    }
}

/**
 * CoverIssueSeverity gates whether ValidateCover.OK flips to false.
 * Errors block render/save; warnings are advisory and surface in the
 * UI as soft hints.
 */
export enum CoverIssueSeverity {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CoverIssueError = "error",
    CoverIssueWarning = "warning",
};

/**
 * CoverTokenInfo carries the metadata parsed out of the magic comment.
 * Name and Description are optional and purely informational — only
 * Version participates in validation.
 */
export class CoverTokenInfo {
    "version": number;
    "name"?: string;
    "description"?: string;

    /** Creates a new CoverTokenInfo instance. */
    constructor($$source: Partial<CoverTokenInfo> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CoverTokenInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CoverTokenInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CoverTokenInfo($$parsedSource as Partial<CoverTokenInfo>);
    }
}

/**
 * CoverValidation is the validator's structured result. OK is the
 * errors.Is-style "should we proceed" gate; Issues carries every
 * finding (warnings included) for the UI to display.
 */
export class CoverValidation {
    "ok": boolean;
    "token"?: CoverTokenInfo | null;
    "issues"?: CoverIssue[];

    /** Creates a new CoverValidation instance. */
    constructor($$source: Partial<CoverValidation> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CoverValidation instance from a string or object.
     */
    static createFrom($$source: any = {}): CoverValidation {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("token" in $$parsedSource) {
            $$parsedSource["token"] = $$createField1_0($$parsedSource["token"]);
        }
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField2_0($$parsedSource["issues"]);
        }
        return new CoverValidation($$parsedSource as Partial<CoverValidation>);
    }
}

/**
 * ExportOpts shapes the per-call options ExportPDF accepts. Empty
 * values fall back to the merged manifest + form-meta + global-config
 * defaults.
 * 
 *   - OutputPath: absolute or context-relative; default "<form>.pdf"
 *     next to the form.
 *   - Style: picoloom theme name or path to a custom CSS file.
 *   - CoverTemplate: name of a cover from the on-disk library at
 *     <AppRoot>/pdf/covers/. Empty = use whatever the merged
 *     frontmatter / template manifest resolves to (which may itself
 *     be empty → picoloom's default cover). Wired by the export
 *     dialog's Cover picker for per-export overrides.
 */
export class ExportOpts {
    "output_path"?: string;
    "style"?: string;
    "cover_template"?: string;

    /**
     * DisableCover forces a render with no cover page even when the
     * merged frontmatter / template manifest supplies one. Wins over
     * CoverTemplate. The "No cover" entry in the export dialog's
     * dropdown sets this flag.
     */
    "disable_cover"?: boolean;

    /**
     * DisableTheme forces a render with no WithStyle option (picoloom's
     * built-in default CSS) even when the merged frontmatter / template
     * manifest supplies a Style. Wins over both Style and the merge
     * layers. The "No theme" entry in the dialog's dropdown sets this.
     */
    "disable_theme"?: boolean;

    /** Creates a new ExportOpts instance. */
    constructor($$source: Partial<ExportOpts> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportOpts instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportOpts {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportOpts($$parsedSource as Partial<ExportOpts>);
    }
}

/**
 * ExportTelemetry is the in-memory record of a single Export call,
 * captured at the same moment its slog event fires. Success records
 * carry Path + Bytes; failure records carry Code + Stage + Err. The
 * shared identity fields (Template, Datafile, DurationMs, At) plus
 * the effective Theme/Cover/HasCover apply to both.
 * 
 * The PDF doctor sub-panel reads these via Service.LastExport. Stable
 * shape — JSON tags are part of the Wails contract.
 */
export class ExportTelemetry {
    "at": time$0.Time;
    "template": string;
    "datafile": string;
    "duration_ms": number;
    "theme"?: string;
    "cover"?: string;
    "has_cover": boolean;

    /**
     * Success-only.
     */
    "path"?: string;
    "bytes"?: number;

    /**
     * Failure-only.
     */
    "code"?: string;
    "stage"?: string;
    "err"?: string;

    /** Creates a new ExportTelemetry instance. */
    constructor($$source: Partial<ExportTelemetry> = {}) {
        if (!("at" in $$source)) {
            this["at"] = null;
        }
        if (!("template" in $$source)) {
            this["template"] = "";
        }
        if (!("datafile" in $$source)) {
            this["datafile"] = "";
        }
        if (!("duration_ms" in $$source)) {
            this["duration_ms"] = 0;
        }
        if (!("has_cover" in $$source)) {
            this["has_cover"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportTelemetry instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportTelemetry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportTelemetry($$parsedSource as Partial<ExportTelemetry>);
    }
}

/**
 * ExportTelemetrySnapshot is the doctor's read of "what is the engine
 * doing lately?". Both fields may be nil (fresh process, no exports
 * yet) or non-nil (process has seen both successful + failed exports).
 */
export class ExportTelemetrySnapshot {
    "last_success"?: ExportTelemetry | null;
    "last_failure"?: ExportTelemetry | null;

    /** Creates a new ExportTelemetrySnapshot instance. */
    constructor($$source: Partial<ExportTelemetrySnapshot> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportTelemetrySnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportTelemetrySnapshot {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("last_success" in $$parsedSource) {
            $$parsedSource["last_success"] = $$createField0_0($$parsedSource["last_success"]);
        }
        if ("last_failure" in $$parsedSource) {
            $$parsedSource["last_failure"] = $$createField1_0($$parsedSource["last_failure"]);
        }
        return new ExportTelemetrySnapshot($$parsedSource as Partial<ExportTelemetrySnapshot>);
    }
}

/**
 * ProbeResult is what ProbeChrome returns to the activation dialog.
 * Candidates is ordered: env-var override (if any), then system
 * matches in the platform's standard search list, then managed-cache
 * matches. Empty means no Chrome was found — the dialog should offer
 * the managed-download path (Phase D).
 */
export class ProbeResult {
    "candidates": ChromeCandidate[];

    /** Creates a new ProbeResult instance. */
    constructor($$source: Partial<ProbeResult> = {}) {
        if (!("candidates" in $$source)) {
            this["candidates"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProbeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ProbeResult {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("candidates" in $$parsedSource) {
            $$parsedSource["candidates"] = $$createField0_0($$parsedSource["candidates"]);
        }
        return new ProbeResult($$parsedSource as Partial<ProbeResult>);
    }
}

/**
 * ResolvedExportDefaults reveals what Theme + Cover Manager.Export
 * would pick for the (template, datafile) pair if the user accepts
 * the dialog's default options. The dialog uses this to label the
 * "(use frontmatter / template default)" entry with the concrete
 * value that will actually be applied — so a template whose frontmatter
 * has no `style:` shows up as "(no theme — picoloom built-in)" instead
 * of pretending a frontmatter override exists.
 * 
 * Empty Theme / CoverTemplate strings mean "no override in any merge
 * layer — picoloom's own built-in default will be used at render time".
 * CoverDisabled distinguishes that-from "frontmatter said cover.enabled:
 * false" so the dialog can show a more specific label.
 */
export class ResolvedExportDefaults {
    "theme": string;
    "cover_template": string;
    "cover_disabled"?: boolean;

    /** Creates a new ResolvedExportDefaults instance. */
    constructor($$source: Partial<ResolvedExportDefaults> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("cover_template" in $$source)) {
            this["cover_template"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolvedExportDefaults instance from a string or object.
     */
    static createFrom($$source: any = {}): ResolvedExportDefaults {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResolvedExportDefaults($$parsedSource as Partial<ResolvedExportDefaults>);
    }
}

/**
 * Result is the bound shape ExportPDF returns. The PDF bytes are not
 * in the result — they go straight to disk via system.SaveFile. The
 * frontend uses Path to surface an "Open" link in the success toast.
 */
export class Result {
    "path": string;
    "bytes": number;
    "duration_ms": time$0.Duration;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }
        if (!("duration_ms" in $$source)) {
            this["duration_ms"] = time$0.Duration.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Result($$parsedSource as Partial<Result>);
    }
}

/**
 * Source describes where the active Chrome/Chromium binary came from.
 * Values are stable and used in both the Status struct and persisted
 * config — do not rename without a migration.
 */
export enum Source {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * SourceUnset is the inactive state — no browser bound, no
     * activation attempted. Default for fresh profiles.
     */
    SourceUnset = "unset",

    /**
     * SourceSystem means the user pointed activation at an existing
     * system binary (e.g. /usr/bin/chromium). Updates ride the OS
     * package manager.
     */
    SourceSystem = "system",

    /**
     * SourceManaged means activation triggered go-rod's download and
     * the binary lives under ~/.cache/rod/browser/<revision>/.
     * Updates require an explicit re-download.
     */
    SourceManaged = "managed",
};

/**
 * Status is the live snapshot of the PDF engine. Safe to call before
 * or after activation; zero value means inactive.
 * 
 * ExportDir is the per-machine "where renders land" preference. It is
 * independent of activation — the user can set or change it while
 * inactive, and Deactivate does not wipe it. Empty string means
 * "no default — Stage 4 will fall back to placing PDFs next to the
 * form" (see design/pdf-export.md, Stage 4 output path resolution).
 */
export class Status {
    "active": boolean;
    "browser_bin": string;
    "source": Source;
    "version": string;
    "activated_at": time$0.Time;
    "export_dir": string;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("active" in $$source)) {
            this["active"] = false;
        }
        if (!("browser_bin" in $$source)) {
            this["browser_bin"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = Source.$zero;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("activated_at" in $$source)) {
            this["activated_at"] = null;
        }
        if (!("export_dir" in $$source)) {
            this["export_dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status($$parsedSource as Partial<Status>);
    }
}

/**
 * ThemeDescriptor is one entry in the dialog's Theme dropdown. The
 * Name is the canonical key passed to picoloom.WithStyle (and the
 * value stored in frontmatter `style:`); the frontend's i18n layer
 * maps Name → human label via `pdf.export.dialog.theme.<name>` keys.
 * 
 * Listed by Service.ListThemes. Picoloom v2 does not enumerate its
 * bundled styles, so the Go side keeps the canonical list. When
 * picoloom adds a style (or exposes its registry), refresh `builtinThemes`
 * in service.go to match — there is no other place to update.
 */
export class ThemeDescriptor {
    "name": string;

    /** Creates a new ThemeDescriptor instance. */
    constructor($$source: Partial<ThemeDescriptor> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeDescriptor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeDescriptor($$parsedSource as Partial<ThemeDescriptor>);
    }
}

// Private type creation functions
const $$createType0 = CoverTokenInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = CoverIssue.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = ExportTelemetry.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = ChromeCandidate.createFrom;
const $$createType7 = $Create.Array($$createType6);
