// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * ActivateOpts carries the activation choices the user made in the
 * Information-page dialog.
 * 
 *   - BrowserBin: when set, skip probing and use this path directly.
 *     When empty, the prober runs and the first candidate is picked.
 * 
 * Formidable does not bundle or download Chrome — if no candidate
 * is found, the user must install one (or point ROD_BROWSER_BIN at
 * one) themselves.
 */
export class ActivateOpts {
    "browser_bin"?: string;

    /** Creates a new ActivateOpts instance. */
    constructor($$source: Partial<ActivateOpts> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActivateOpts instance from a string or object.
     */
    static createFrom($$source: any = {}): ActivateOpts {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActivateOpts($$parsedSource as Partial<ActivateOpts>);
    }
}

/**
 * ChromeCandidate is one entry returned by ProbeChrome — a Chrome/
 * Chromium binary the activation flow can adopt. Version is best-
 * effort (resolved by running `<path> --version`) and may be empty
 * when the binary refuses to run or the call times out.
 */
export class ChromeCandidate {
    "path": string;
    "source": Source;
    "version"?: string;

    /** Creates a new ChromeCandidate instance. */
    constructor($$source: Partial<ChromeCandidate> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = Source.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChromeCandidate instance from a string or object.
     */
    static createFrom($$source: any = {}): ChromeCandidate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChromeCandidate($$parsedSource as Partial<ChromeCandidate>);
    }
}

/**
 * ExportOpts shapes the per-call options ExportPDF accepts. Empty
 * values fall back to the merged manifest + form-meta + global-config
 * defaults (Stage 3 builds that pipeline). Stage 1 ignores it.
 * 
 *   - OutputPath: absolute or context-relative; default "<form>.pdf"
 *     next to the form.
 *   - Style: picoloom theme name or path to a custom CSS file.
 */
export class ExportOpts {
    "output_path"?: string;
    "style"?: string;

    /** Creates a new ExportOpts instance. */
    constructor($$source: Partial<ExportOpts> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportOpts instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportOpts {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportOpts($$parsedSource as Partial<ExportOpts>);
    }
}

/**
 * ProbeResult is what ProbeChrome returns to the activation dialog.
 * Candidates is ordered: env-var override (if any), then system
 * matches in the platform's standard search list, then managed-cache
 * matches. Empty means no Chrome was found — the dialog should offer
 * the managed-download path (Phase D).
 */
export class ProbeResult {
    "candidates": ChromeCandidate[];

    /** Creates a new ProbeResult instance. */
    constructor($$source: Partial<ProbeResult> = {}) {
        if (!("candidates" in $$source)) {
            this["candidates"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProbeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ProbeResult {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("candidates" in $$parsedSource) {
            $$parsedSource["candidates"] = $$createField0_0($$parsedSource["candidates"]);
        }
        return new ProbeResult($$parsedSource as Partial<ProbeResult>);
    }
}

/**
 * Result is the bound shape ExportPDF returns. The PDF bytes are not
 * in the result — they go straight to disk via system.SaveFile. The
 * frontend uses Path to surface an "Open" link in the success toast.
 */
export class Result {
    "path": string;
    "bytes": number;
    "duration_ms": time$0.Duration;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }
        if (!("duration_ms" in $$source)) {
            this["duration_ms"] = time$0.Duration.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Result($$parsedSource as Partial<Result>);
    }
}

/**
 * Source describes where the active Chrome/Chromium binary came from.
 * Values are stable and used in both the Status struct and persisted
 * config — do not rename without a migration.
 */
export enum Source {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * SourceUnset is the inactive state — no browser bound, no
     * activation attempted. Default for fresh profiles.
     */
    SourceUnset = "unset",

    /**
     * SourceSystem means the user pointed activation at an existing
     * system binary (e.g. /usr/bin/chromium). Updates ride the OS
     * package manager.
     */
    SourceSystem = "system",

    /**
     * SourceManaged means activation triggered go-rod's download and
     * the binary lives under ~/.cache/rod/browser/<revision>/.
     * Updates require an explicit re-download.
     */
    SourceManaged = "managed",
};

/**
 * Status is the live snapshot of the PDF engine. Safe to call before
 * or after activation; zero value means inactive.
 * 
 * ExportDir is the per-machine "where renders land" preference. It is
 * independent of activation — the user can set or change it while
 * inactive, and Deactivate does not wipe it. Empty string means
 * "no default — Stage 4 will fall back to placing PDFs next to the
 * form" (see design/pdf-export.md, Stage 4 output path resolution).
 */
export class Status {
    "active": boolean;
    "browser_bin": string;
    "source": Source;
    "version": string;
    "activated_at": time$0.Time;
    "export_dir": string;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("active" in $$source)) {
            this["active"] = false;
        }
        if (!("browser_bin" in $$source)) {
            this["browser_bin"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = Source.$zero;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("activated_at" in $$source)) {
            this["activated_at"] = null;
        }
        if (!("export_dir" in $$source)) {
            this["export_dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status($$parsedSource as Partial<Status>);
    }
}

// Private type creation functions
const $$createType0 = ChromeCandidate.createFrom;
const $$createType1 = $Create.Array($$createType0);
