// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound surface over Manager. There is no HTTP
 * peer; PDF generation stays Wails-only.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Activate adopts a Chrome binary for PDF export.
 */
export function Activate(opts: $models.ActivateOpts): $CancellablePromise<$models.Status> {
    return $Call.ByID(1226937439, opts).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AssetServerAddr returns the asset server's host:port, or "" when none
 * is wired or it is closed.
 */
export function AssetServerAddr(): $CancellablePromise<string> {
    return $Call.ByID(3571308458);
}

/**
 * BuildFrontmatter renders an InjectConfig into a YAML frontmatter block.
 */
export function BuildFrontmatter(cfg: $models.InjectConfig): $CancellablePromise<string> {
    return $Call.ByID(3336258372, cfg);
}

/**
 * Deactivate releases the bound Chrome binary, keeping any managed download.
 */
export function Deactivate(): $CancellablePromise<void> {
    return $Call.ByID(3089033884);
}

/**
 * DeleteCover removes a cover; see Manager.DeleteCover for the seed
 * reset behaviour.
 */
export function DeleteCover(name: string): $CancellablePromise<void> {
    return $Call.ByID(1910310356, name);
}

/**
 * DeleteCoverImage removes an image; seeds reappear via the next boot's
 * scaffold (phrase as "Reset" for those).
 */
export function DeleteCoverImage(name: string): $CancellablePromise<void> {
    return $Call.ByID(1752088097, name);
}

/**
 * ExportCoverArchive zips a cover and its image refs into zipPath.
 */
export function ExportCoverArchive(name: string, zipPath: string): $CancellablePromise<$models.ExportCoverArchiveResult> {
    return $Call.ByID(1073298831, name, zipPath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ExportPDF renders the form to a PDF on disk; see Manager.Export.
 */
export function ExportPDF(templateFilename: string, datafile: string, opts: $models.ExportOpts): $CancellablePromise<$models.Result> {
    return $Call.ByID(691812250, templateFilename, datafile, opts).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetDirectivesDoc returns the directives reference markdown for
 * locale, falling back to English.
 */
export function GetDirectivesDoc(locale: string): $CancellablePromise<string> {
    return $Call.ByID(1327533002, locale);
}

/**
 * GetStatus returns the live engine state.
 */
export function GetStatus(): $CancellablePromise<$models.Status> {
    return $Call.ByID(3795685764).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportCoverArchive materialises a cover archive from zipPath; refuses
 * to clobber unless overwrite=true.
 */
export function ImportCoverArchive(zipPath: string, overwrite: boolean): $CancellablePromise<$models.ImportCoverArchiveResult> {
    return $Call.ByID(4211656816, zipPath, overwrite).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * InjectFrontmatter prepends the canonical scaffold to a markdown body,
 * or returns ErrFrontmatterAlreadyPresent.
 * 
 * Deprecated: prefer BuildFrontmatter(InjectConfig); this survives only
 * for callers that want the full commented placeholder scaffold.
 */
export function InjectFrontmatter(markdown: string): $CancellablePromise<string> {
    return $Call.ByID(65038787, markdown);
}

/**
 * LastExport returns the most recent success + failure telemetry.
 */
export function LastExport(): $CancellablePromise<$models.ExportTelemetrySnapshot> {
    return $Call.ByID(824932320).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ListCoverImages returns descriptors for every image under
 * <AppRoot>/pdf/covers/images/; seeds are flagged.
 */
export function ListCoverImages(): $CancellablePromise<$models.CoverImageDescriptor[]> {
    return $Call.ByID(948120903).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ListCovers returns descriptors for every cover under <AppRoot>/pdf/covers/.
 */
export function ListCovers(): $CancellablePromise<$models.CoverDescriptor[]> {
    return $Call.ByID(476206190).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListFooterPositions returns picoloom's canonical footer-position set.
 */
export function ListFooterPositions(): $CancellablePromise<$models.FooterPositionDescriptor[]> {
    return $Call.ByID(1619218275).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ListPageOrientations returns picoloom's canonical orientation set.
 */
export function ListPageOrientations(): $CancellablePromise<$models.OrientationDescriptor[]> {
    return $Call.ByID(4037347146).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * ListPageSizes returns picoloom's page-size set in dropdown order.
 */
export function ListPageSizes(): $CancellablePromise<$models.PageSizeDescriptor[]> {
    return $Call.ByID(3746256793).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * ListThemes returns the picoloom bundled style set in display order.
 */
export function ListThemes(): $CancellablePromise<$models.ThemeDescriptor[]> {
    return $Call.ByID(2644176728).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * LoadCover returns the raw cover HTML for editing (no validation).
 */
export function LoadCover(name: string): $CancellablePromise<string> {
    return $Call.ByID(2607383821, name);
}

/**
 * LoadCoverImage returns one image's bytes base64-encoded for the JSON
 * Wails surface.
 */
export function LoadCoverImage(name: string): $CancellablePromise<string> {
    return $Call.ByID(2402547314, name);
}

/**
 * MigrateFrontmatter rewrites an eisvogel/pandoc block into picoloom v2
 * shape; see MigrateFrontmatter for the contract.
 */
export function MigrateFrontmatter(markdown: string): $CancellablePromise<$models.FrontmatterMigration> {
    return $Call.ByID(470664647, markdown).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * ProbeChrome lists every Chrome/Chromium binary the activation flow
 * could adopt; empty Candidates means none was found.
 */
export function ProbeChrome(): $CancellablePromise<$models.ProbeResult> {
    return $Call.ByID(4169509082).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * ResolveExportDefaults previews the Theme + Cover Export would pick;
 * see Manager.ResolveExportDefaults.
 */
export function ResolveExportDefaults(templateFilename: string, datafile: string): $CancellablePromise<$models.ResolvedExportDefaults> {
    return $Call.ByID(2533436814, templateFilename, datafile).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * SaveCover validates and persists cover HTML; see Manager.SaveCover.
 */
export function SaveCover(name: string, html: string): $CancellablePromise<void> {
    return $Call.ByID(2359601362, name, html);
}

/**
 * SaveCoverImage decodes a base64 (or data-URI) body and persists it
 * under <AppRoot>/pdf/covers/images/<name>.
 */
export function SaveCoverImage(name: string, base64Data: string): $CancellablePromise<void> {
    return $Call.ByID(490032087, name, base64Data);
}

/**
 * SetExportDir sets the per-machine export folder; see Manager.SetExportDir.
 */
export function SetExportDir(path: string): $CancellablePromise<$models.Status> {
    return $Call.ByID(847655379, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ValidateCoverHTML dry-runs cover validation without touching disk.
 */
export function ValidateCoverHTML(html: string): $CancellablePromise<$models.CoverValidation> {
    return $Call.ByID(1327021382, html).then(($result: any) => {
        return $$createType20($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Status.createFrom;
const $$createType1 = $models.ExportCoverArchiveResult.createFrom;
const $$createType2 = $models.Result.createFrom;
const $$createType3 = $models.ImportCoverArchiveResult.createFrom;
const $$createType4 = $models.ExportTelemetrySnapshot.createFrom;
const $$createType5 = $models.CoverImageDescriptor.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.CoverDescriptor.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.FooterPositionDescriptor.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.OrientationDescriptor.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.PageSizeDescriptor.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $models.ThemeDescriptor.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $models.FrontmatterMigration.createFrom;
const $$createType18 = $models.ProbeResult.createFrom;
const $$createType19 = $models.ResolvedExportDefaults.createFrom;
const $$createType20 = $models.CoverValidation.createFrom;
