// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound surface over Manager. The Information
 * workspace activation panel and any "Export as PDF" trigger call
 * these methods directly — there is no HTTP handler peer, PDF
 * generation stays Wails-only (see types.go).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Activate is the user's "yes, set up PDF export" action. Stage 1
 * always returns ErrPDFNotActivated; Stage 2 wires probing +
 * managed-download flow.
 */
export function Activate(opts: $models.ActivateOpts): $CancellablePromise<$models.Status> {
    return $Call.ByID(1226937439, opts).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Deactivate releases the bound Chrome binary without deleting any
 * managed download. Stage 1 always returns ErrPDFNotActivated.
 */
export function Deactivate(): $CancellablePromise<void> {
    return $Call.ByID(3089033884);
}

/**
 * ExportPDF renders the form identified by formGUID. Stage 1 always
 * returns ErrPDFNotActivated; Stage 4 wires the render → picoloom →
 * system.SaveFile pipeline.
 */
export function ExportPDF(formGUID: string, opts: $models.ExportOpts): $CancellablePromise<$models.Result> {
    return $Call.ByID(691812250, formGUID, opts).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetStatus returns the live engine state. Cheap; safe to poll from
 * the Information page status row.
 */
export function GetStatus(): $CancellablePromise<$models.Status> {
    return $Call.ByID(3795685764).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Status.createFrom;
const $$createType1 = $models.Result.createFrom;
