// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound surface over Manager. The Information
 * workspace activation panel and any "Export as PDF" trigger call
 * these methods directly — there is no HTTP handler peer, PDF
 * generation stays Wails-only (see types.go).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Activate is the user's "yes, set up PDF export" action. Stage 1
 * always returns ErrPDFNotActivated; Stage 2 wires probing +
 * managed-download flow.
 */
export function Activate(opts: $models.ActivateOpts): $CancellablePromise<$models.Status> {
    return $Call.ByID(1226937439, opts).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * BuildFrontmatter renders a typed InjectConfig (collected by the
 * Inject dialog's toggles + dropdowns + text inputs) into a YAML
 * frontmatter block. Each block the user enabled becomes a sub-block
 * in the output, in canonical order, with empty fields skipped. The
 * frontend prepends the result to its markdown_template draft.
 */
export function BuildFrontmatter(cfg: $models.InjectConfig): $CancellablePromise<string> {
    return $Call.ByID(3336258372, cfg);
}

/**
 * Deactivate releases the bound Chrome binary without deleting any
 * managed download. Stage 1 always returns ErrPDFNotActivated.
 */
export function Deactivate(): $CancellablePromise<void> {
    return $Call.ByID(3089033884);
}

/**
 * DeleteCover removes a user-added or seed cover from disk. Seed
 * covers (classic/banner/corporate) reappear at next boot via the
 * scaffold — the frontend should phrase this as "Reset" rather than
 * "Delete" for those entries. Refuses reserved names with
 * ErrCoverNotFound. Missing files are not an error.
 */
export function DeleteCover(name: string): $CancellablePromise<void> {
    return $Call.ByID(1910310356, name);
}

/**
 * ExportPDF renders the (templateFilename, datafile) form to a PDF
 * on disk. Pipeline: render markdown → parse + merge frontmatter →
 * build picoloom.Input → convert → atomic write. Returns
 * ErrPDFNotActivated when the engine is inactive; otherwise wraps
 * any downstream error with context. See pdf.Manager.Export for the
 * full contract.
 */
export function ExportPDF(templateFilename: string, datafile: string, opts: $models.ExportOpts): $CancellablePromise<$models.Result> {
    return $Call.ByID(691812250, templateFilename, datafile, opts).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetDirectivesDoc returns the embedded markdown reference for the
 * picoloom frontmatter directives in the requested locale. Unknown
 * locale falls back to English. Static content — safe to call any
 * time, cheap, no I/O beyond the embedded FS.
 */
export function GetDirectivesDoc(locale: string): $CancellablePromise<string> {
    return $Call.ByID(1327533002, locale);
}

/**
 * GetStatus returns the live engine state. Cheap; safe to poll from
 * the Information page status row.
 */
export function GetStatus(): $CancellablePromise<$models.Status> {
    return $Call.ByID(3795685764).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * InjectFrontmatter prepends the canonical picoloom v2 scaffold to a
 * markdown body. Refuses with ErrFrontmatterAlreadyPresent when an
 * existing `---` block is detected — the user should run
 * MigrateFrontmatter in that case. The frontend inserts the result
 * into the template editor; the user saves the template manually.
 * 
 * Deprecated for new callers — prefer BuildFrontmatter(InjectConfig)
 * + your own prepend logic for full control over which blocks/values
 * land in the output. This helper survives because some callers want
 * the full canonical fully-commented placeholder scaffold.
 */
export function InjectFrontmatter(markdown: string): $CancellablePromise<string> {
    return $Call.ByID(65038787, markdown);
}

/**
 * LastExport returns the most recent success + failure ExportTelemetry
 * records held in memory by the Manager. Both fields may be nil when
 * the process is fresh. Powers the PDF doctor sub-panel on the
 * Information page.
 */
export function LastExport(): $CancellablePromise<$models.ExportTelemetrySnapshot> {
    return $Call.ByID(824932320).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListCovers returns descriptors for every cover discovered under
 * <AppRoot>/pdf/covers/. Powers the cover-picker dropdown in the
 * export dialog: scanned live on every call so user-added .html
 * files appear without restart.
 */
export function ListCovers(): $CancellablePromise<$models.CoverDescriptor[]> {
    return $Call.ByID(476206190).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ListFooterPositions returns picoloom's canonical footer-position set.
 */
export function ListFooterPositions(): $CancellablePromise<$models.FooterPositionDescriptor[]> {
    return $Call.ByID(1619218275).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ListPageOrientations returns picoloom's canonical orientation set.
 */
export function ListPageOrientations(): $CancellablePromise<$models.OrientationDescriptor[]> {
    return $Call.ByID(4037347146).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListPageSizes returns picoloom's canonical page-size set in
 * dropdown order. Frontend reads this via the same pattern as
 * ListThemes / ListLocales — never hardcoded.
 */
export function ListPageSizes(): $CancellablePromise<$models.PageSizeDescriptor[]> {
    return $Call.ByID(3746256793).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ListThemes returns the canonical picoloom bundled style set in
 * stable display order. The frontend uses this to populate the Theme
 * dropdown — it must NOT keep its own hardcoded list. Pure function,
 * safe regardless of activation state.
 */
export function ListThemes(): $CancellablePromise<$models.ThemeDescriptor[]> {
    return $Call.ByID(2644176728).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * LoadCover returns the raw HTML for an existing cover. Skips
 * validation so the editor can load a broken file and let the user
 * fix it; the frontend should call ValidateCoverHTML on the loaded
 * content to surface issues. Reserved names return ErrCoverNotFound.
 */
export function LoadCover(name: string): $CancellablePromise<string> {
    return $Call.ByID(2607383821, name);
}

/**
 * MigrateFrontmatter rewrites an existing eisvogel/pandoc-style
 * frontmatter block into picoloom v2 shape. Returns the rewritten
 * markdown alongside structured metadata (which keys were mapped,
 * which landed in the legacy block, warnings) so the frontend can
 * render a preview before applying.
 */
export function MigrateFrontmatter(markdown: string): $CancellablePromise<$models.FrontmatterMigration> {
    return $Call.ByID(470664647, markdown).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * ProbeChrome lists every Chrome/Chromium binary the activation
 * flow could adopt — env-var override, then system paths in their
 * platform's conventional order, then the latest managed-cache
 * pick. Empty Candidates means no Chrome was found; the dialog
 * should offer the managed-download path (Phase D).
 */
export function ProbeChrome(): $CancellablePromise<$models.ProbeResult> {
    return $Call.ByID(4169509082).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * ResolveExportDefaults previews the Theme + Cover that Manager.Export
 * would pick for (template, datafile) under the dialog's default
 * options. The dialog reads this on open and labels its default
 * dropdown entry with the concrete value — so users know whether
 * the template's frontmatter actually supplies a theme/cover or whether
 * the picoloom built-in defaults kick in. Read-only; safe regardless
 * of activation state.
 */
export function ResolveExportDefaults(templateFilename: string, datafile: string): $CancellablePromise<$models.ResolvedExportDefaults> {
    return $Call.ByID(2533436814, templateFilename, datafile).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * SaveCover persists user-authored cover HTML. Validates first; on
 * any error-severity issue, refuses to write and returns
 * ErrCoverInvalid wrapped with structured issue codes. On success
 * the cover becomes discoverable via ListCovers immediately.
 */
export function SaveCover(name: string, html: string): $CancellablePromise<void> {
    return $Call.ByID(2359601362, name, html);
}

/**
 * SetExportDir adopts a per-machine "where PDFs land" preference.
 * Empty path clears the preference. Non-empty paths must be
 * absolute + existent + a directory — otherwise the service
 * returns ErrInvalidExportDir, which the frontend should surface
 * as a user-correctable error (typically a re-pick via the native
 * folder picker). Independent of activation state.
 */
export function SetExportDir(path: string): $CancellablePromise<$models.Status> {
    return $Call.ByID(847655379, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ValidateCoverHTML lets the frontend dry-run validation (e.g. on
 * every keystroke in a cover editor) without writing to disk. Pure
 * function — no I/O, no side effects.
 */
export function ValidateCoverHTML(html: string): $CancellablePromise<$models.CoverValidation> {
    return $Call.ByID(1327021382, html).then(($result: any) => {
        return $$createType16($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Status.createFrom;
const $$createType1 = $models.Result.createFrom;
const $$createType2 = $models.ExportTelemetrySnapshot.createFrom;
const $$createType3 = $models.CoverDescriptor.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.FooterPositionDescriptor.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.OrientationDescriptor.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.PageSizeDescriptor.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.ThemeDescriptor.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.FrontmatterMigration.createFrom;
const $$createType14 = $models.ProbeResult.createFrom;
const $$createType15 = $models.ResolvedExportDefaults.createFrom;
const $$createType16 = $models.CoverValidation.createFrom;
