// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FileFilter narrows what the native picker shows. Pattern uses the
 * platform-native glob (e.g. `*.json`); on macOS the Wails layer
 * translates this into UTI/extensions internally.
 */
export class FileFilter {
    "displayName": string;
    "pattern": string;

    /** Creates a new FileFilter instance. */
    constructor($$source: Partial<FileFilter> = {}) {
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileFilter instance from a string or object.
     */
    static createFrom($$source: any = {}): FileFilter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileFilter($$parsedSource as Partial<FileFilter>);
    }
}
