// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AuditEntry records who and when, for FormMeta.Created (locked at first save) and Updated (re-stamped each save).
 * On read, legacy flat author/timestamp fields are migrated in; on write only the nested shape is emitted.
 */
export class AuditEntry {
    "at": string;
    "name": string;
    "email": string;

    /** Creates a new AuditEntry instance. */
    constructor($$source: Partial<AuditEntry> = {}) {
        if (!("at" in $$source)) {
            this["at"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuditEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): AuditEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuditEntry($$parsedSource as Partial<AuditEntry>);
    }
}

/**
 * FacetState is the per-record state for one facet: Set (stamped?) plus an optional Selected option label.
 */
export class FacetState {
    "set": boolean;
    "selected"?: string;

    /** Creates a new FacetState instance. */
    constructor($$source: Partial<FacetState> = {}) {
        if (!("set" in $$source)) {
            this["set"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FacetState instance from a string or object.
     */
    static createFrom($$source: any = {}): FacetState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FacetState($$parsedSource as Partial<FacetState>);
    }
}

/**
 * Form is the on-disk shape of a `.meta.json` file.
 */
export class Form {
    "meta": FormMeta;
    "data": { [_ in string]?: any };

    /** Creates a new Form instance. */
    constructor($$source: Partial<Form> = {}) {
        if (!("meta" in $$source)) {
            this["meta"] = (new FormMeta());
        }
        if (!("data" in $$source)) {
            this["data"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Form instance from a string or object.
     */
    static createFrom($$source: any = {}): Form {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField0_0($$parsedSource["meta"]);
        }
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField1_0($$parsedSource["data"]);
        }
        return new Form($$parsedSource as Partial<Form>);
    }
}

/**
 * FormMeta carries identity + audit fields; Tags are deduped+sorted, Facets is keyed by Template.Facets[i].Key.
 */
export class FormMeta {
    "id": string;
    "template": string;
    "created": AuditEntry;
    "updated": AuditEntry;
    "facets"?: { [_ in string]?: FacetState };
    "tags": string[];

    /** Creates a new FormMeta instance. */
    constructor($$source: Partial<FormMeta> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("template" in $$source)) {
            this["template"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = (new AuditEntry());
        }
        if (!("updated" in $$source)) {
            this["updated"] = (new AuditEntry());
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FormMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): FormMeta {
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("created" in $$parsedSource) {
            $$parsedSource["created"] = $$createField2_0($$parsedSource["created"]);
        }
        if ("updated" in $$parsedSource) {
            $$parsedSource["updated"] = $$createField3_0($$parsedSource["updated"]);
        }
        if ("facets" in $$parsedSource) {
            $$parsedSource["facets"] = $$createField4_0($$parsedSource["facets"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField5_0($$parsedSource["tags"]);
        }
        return new FormMeta($$parsedSource as Partial<FormMeta>);
    }
}

/**
 * FormSummary is one ExtendedListForms row; Title falls back to filename when item_field is unset/empty.
 */
export class FormSummary {
    "filename": string;
    "meta": FormMeta;
    "title": string;
    "expressionItems": { [_ in string]?: any };

    /** Creates a new FormSummary instance. */
    constructor($$source: Partial<FormSummary> = {}) {
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("meta" in $$source)) {
            this["meta"] = (new FormMeta());
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("expressionItems" in $$source)) {
            this["expressionItems"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FormSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): FormSummary {
        const $$createField1_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField1_0($$parsedSource["meta"]);
        }
        if ("expressionItems" in $$parsedSource) {
            $$parsedSource["expressionItems"] = $$createField3_0($$parsedSource["expressionItems"]);
        }
        return new FormSummary($$parsedSource as Partial<FormSummary>);
    }
}

/**
 * MigrateResult reports the outcome of MigrateTemplateMeta; migrated files keep their original authorship,
 * already-new files are skipped untouched, and per-file errors land in Errors without aborting the pass.
 */
export class MigrateResult {
    "total": number;
    "migrated": number;
    "skipped": number;
    "errors"?: string[];

    /** Creates a new MigrateResult instance. */
    constructor($$source: Partial<MigrateResult> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("migrated" in $$source)) {
            this["migrated"] = 0;
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MigrateResult instance from a string or object.
     */
    static createFrom($$source: any = {}): MigrateResult {
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField3_0($$parsedSource["errors"]);
        }
        return new MigrateResult($$parsedSource as Partial<MigrateResult>);
    }
}

/**
 * SaveResult is the success/path/error shape used across SFR-backed modules.
 */
export class SaveResult {
    "success": boolean;
    "path"?: string;
    "error"?: string;

    /** Creates a new SaveResult instance. */
    constructor($$source: Partial<SaveResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveResult($$parsedSource as Partial<SaveResult>);
    }
}

// Private type creation functions
const $$createType0 = FormMeta.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = AuditEntry.createFrom;
const $$createType3 = FacetState.createFrom;
const $$createType4 = $Create.Map($Create.Any, $$createType3);
const $$createType5 = $Create.Array($Create.Any);
