// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the api layer over Manager. Mirrors the Electron
 * `window.api.forms.*` IPC group:
 *   - forms-ensure-dir       → EnsureFormDir
 *   - list-forms             → ListForms
 *   - extended-list-forms    → ExtendedListForms
 *   - load-form              → LoadForm
 *   - save-form              → SaveForm
 *   - delete-form            → DeleteForm
 *   - save-image-file        → SaveImageFile
 *   - csv-import-row         → ImportCsvRow (alias for SaveForm with raw envelope)
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteForm(templateFilename: string, datafile: string): $CancellablePromise<void> {
    return $Call.ByID(1928536102, templateFilename, datafile);
}

export function EnsureFormDir(templateFilename: string): $CancellablePromise<void> {
    return $Call.ByID(1010574690, templateFilename);
}

export function ExtendedListForms(templateFilename: string): $CancellablePromise<$models.FormSummary[]> {
    return $Call.ByID(1556263945, templateFilename).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ImportCsvRow is the storage-side of the old `csv-import-row` IPC.
 * The frontend pre-parsed CSV and now wants each row stored as a form.
 */
export function ImportCsvRow(templateFilename: string, datafile: string, data: { [_ in string]?: any }): $CancellablePromise<$models.SaveResult> {
    return $Call.ByID(53007830, templateFilename, datafile, data).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListForms(templateFilename: string): $CancellablePromise<string[]> {
    return $Call.ByID(3104794654, templateFilename).then(($result: any) => {
        return $$createType3($result);
    });
}

export function LoadForm(templateFilename: string, datafile: string): $CancellablePromise<$models.Form | null> {
    return $Call.ByID(1569422289, templateFilename, datafile).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SaveForm(templateFilename: string, datafile: string, data: { [_ in string]?: any }): $CancellablePromise<$models.SaveResult> {
    return $Call.ByID(1505214792, templateFilename, datafile, data).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SaveImageFile(templateFilename: string, name: string, content: string): $CancellablePromise<$models.SaveResult> {
    return $Call.ByID(1105206989, templateFilename, name, content).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.FormSummary.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.SaveResult.createFrom;
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $models.Form.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
