// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails layer over Manager.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteForm(templateFilename: string, datafile: string): $CancellablePromise<void> {
    return $Call.ByID(1928536102, templateFilename, datafile);
}

/**
 * DeleteImageFile removes the named image (missing file is a no-op).
 */
export function DeleteImageFile(templateFilename: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1324306651, templateFilename, name);
}

export function EnsureFormDir(templateFilename: string): $CancellablePromise<void> {
    return $Call.ByID(1010574690, templateFilename);
}

export function ExtendedListForms(templateFilename: string): $CancellablePromise<$models.FormSummary[]> {
    return $Call.ByID(1556263945, templateFilename).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ImportCsvRow stores one pre-parsed CSV row as a form.
 */
export function ImportCsvRow(templateFilename: string, datafile: string, data: { [_ in string]?: any }): $CancellablePromise<$models.SaveResult> {
    return $Call.ByID(53007830, templateFilename, datafile, data).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListForms(templateFilename: string): $CancellablePromise<string[]> {
    return $Call.ByID(3104794654, templateFilename).then(($result: any) => {
        return $$createType3($result);
    });
}

export function LoadForm(templateFilename: string, datafile: string): $CancellablePromise<$models.Form | null> {
    return $Call.ByID(1569422289, templateFilename, datafile).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * LoadImageFile returns the named image as a base64 data URL.
 */
export function LoadImageFile(templateFilename: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(2646918510, templateFilename, name);
}

/**
 * MigrateTemplateMeta rewrites every legacy-shaped form under the template into the new audit-block shape.
 */
export function MigrateTemplateMeta(templateFilename: string): $CancellablePromise<$models.MigrateResult> {
    return $Call.ByID(53088703, templateFilename).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * SaveForm passes Background because Wails IPC has no request context; stamp() falls back to the AuthorProvider.
 */
export function SaveForm(templateFilename: string, datafile: string, data: { [_ in string]?: any }): $CancellablePromise<$models.SaveResult> {
    return $Call.ByID(1505214792, templateFilename, datafile, data).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SaveImageFile(templateFilename: string, name: string, content: string): $CancellablePromise<$models.SaveResult> {
    return $Call.ByID(1105206989, templateFilename, name, content).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SearchForms runs a full-text query, returning matching summaries ranked by relevance (empty query: no rows).
 */
export function SearchForms(templateFilename: string, query: string): $CancellablePromise<$models.FormSummary[]> {
    return $Call.ByID(3000744366, templateFilename, query).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * TemplateStorageDir returns the absolute path of this template's storage folder.
 */
export function TemplateStorageDir(templateFilename: string): $CancellablePromise<string> {
    return $Call.ByID(3941961345, templateFilename);
}

// Private type creation functions
const $$createType0 = $models.FormSummary.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.SaveResult.createFrom;
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $models.Form.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.MigrateResult.createFrom;
