// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound surface of the config module — what the
 * Vue SPA can actually call. Deliberately narrow:
 * 
 *   - Profile config read/write (the Settings UI)
 *   - Profile management (the Profiles workspace)
 * 
 * The richer Manager surface (VirtualStructure scan, per-template
 * storage info, cache invalidation hooks) is intentionally NOT exposed
 * here. Those primitives are for backend-internal consumers — most
 * notably the future opt-in internal HTTP server (wiki view + REST
 * collections API + OpenAPI), which will use Manager directly.
 * 
 * The frontend covers what little it needs of the file tree through
 * the focused per-module services (template.Service.ListTemplates,
 * storage.Service.ListForms, etc.). Adding a VFS hop on top would
 * duplicate scanning and create two ways to ask the same question.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CurrentProfileFilename(): $CancellablePromise<string> {
    return $Call.ByID(491981415);
}

export function DeleteUserProfile(profileFilename: string): $CancellablePromise<$models.ProfileResult> {
    return $Call.ByID(123880977, profileFilename).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ExportUserProfile(profileFilename: string, targetPath: string, overwrite: boolean): $CancellablePromise<$models.ProfileResult> {
    return $Call.ByID(2426118422, profileFilename, targetPath, overwrite).then(($result: any) => {
        return $$createType0($result);
    });
}

export function HasUserProfiles(): $CancellablePromise<boolean> {
    return $Call.ByID(3861580185);
}

export function ImportUserProfile(sourcePath: string, profileFilename: string, overwrite: boolean): $CancellablePromise<$models.ProfileResult> {
    return $Call.ByID(2301543843, sourcePath, profileFilename, overwrite).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListUserProfiles(): $CancellablePromise<$models.ProfileEntry[]> {
    return $Call.ByID(2914409361).then(($result: any) => {
        return $$createType2($result);
    });
}

export function LoadUserConfig(): $CancellablePromise<$models.Config | null> {
    return $Call.ByID(1287623297).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SwitchUserProfile(profileFilename: string): $CancellablePromise<$models.Config | null> {
    return $Call.ByID(3657031668, profileFilename).then(($result: any) => {
        return $$createType4($result);
    });
}

export function UpdateUserConfig(partial: { [_ in string]?: any }): $CancellablePromise<$models.Config | null> {
    return $Call.ByID(2208258468, partial).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ProfileResult.createFrom;
const $$createType1 = $models.ProfileEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.Config.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
