// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the api layer over Manager. Methods map 1:1 with the old
 * Electron `window.api.config.*` IPC group (camelCase'd → PascalCase).
 * 
 * Wails-only: no handlers.go in this module. Raw config is too sensitive
 * for the loopback HTTP API surface.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CurrentProfileFilename(): $CancellablePromise<string> {
    return $Call.ByID(491981415);
}

export function DeleteUserProfile(profileFilename: string): $CancellablePromise<$models.ProfileResult> {
    return $Call.ByID(123880977, profileFilename).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DirtyVirtualStructure(): $CancellablePromise<void> {
    return $Call.ByID(474194876);
}

export function ExportUserProfile(profileFilename: string, targetPath: string, overwrite: boolean): $CancellablePromise<$models.ProfileResult> {
    return $Call.ByID(2426118422, profileFilename, targetPath, overwrite).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetContextPath(): $CancellablePromise<string> {
    return $Call.ByID(2768905420);
}

export function GetSingleTemplateEntry(templateName: string): $CancellablePromise<$models.SingleTemplateEntry | null> {
    return $Call.ByID(1207119350, templateName).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetStorageFolder(): $CancellablePromise<string> {
    return $Call.ByID(2800240425);
}

export function GetTemplateImageFiles(templateFilename: string): $CancellablePromise<string[]> {
    return $Call.ByID(1104901134, templateFilename).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetTemplateMetaFiles(templateFilename: string): $CancellablePromise<string[]> {
    return $Call.ByID(3198522342, templateFilename).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetTemplateStorageFolder(templateFilename: string): $CancellablePromise<string> {
    return $Call.ByID(451072131, templateFilename);
}

export function GetTemplateStorageInfo(templateFilename: string): $CancellablePromise<$models.TemplateStorageFolder | null> {
    return $Call.ByID(557953811, templateFilename).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetTemplatesFolder(): $CancellablePromise<string> {
    return $Call.ByID(804264695);
}

export function GetVirtualStructure(): $CancellablePromise<$models.VirtualStructure | null> {
    return $Call.ByID(3974804984).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ImportUserProfile(sourcePath: string, profileFilename: string, overwrite: boolean): $CancellablePromise<$models.ProfileResult> {
    return $Call.ByID(2301543843, sourcePath, profileFilename, overwrite).then(($result: any) => {
        return $$createType0($result);
    });
}

export function InvalidateConfigCache(): $CancellablePromise<void> {
    return $Call.ByID(1350027699);
}

export function ListUserProfiles(): $CancellablePromise<$models.ProfileEntry[]> {
    return $Call.ByID(2914409361).then(($result: any) => {
        return $$createType9($result);
    });
}

export function LoadUserConfig(): $CancellablePromise<$models.Config | null> {
    return $Call.ByID(1287623297).then(($result: any) => {
        return $$createType11($result);
    });
}

export function SwitchUserProfile(profileFilename: string): $CancellablePromise<$models.Config | null> {
    return $Call.ByID(3657031668, profileFilename).then(($result: any) => {
        return $$createType11($result);
    });
}

export function UpdateUserConfig(partial: { [_ in string]?: any }): $CancellablePromise<$models.Config | null> {
    return $Call.ByID(2208258468, partial).then(($result: any) => {
        return $$createType11($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ProfileResult.createFrom;
const $$createType1 = $models.SingleTemplateEntry.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $models.TemplateStorageFolder.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.VirtualStructure.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.ProfileEntry.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.Config.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
