// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound facade, surfacing only the picker-side
 * api-field readers. The rest of Manager stays internal: it's wiki-shaped
 * and the wiki HTTP server and api Handler read it directly. Narrow
 * per-need methods get added here one at a time.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * APIFieldTitle returns the collapsed-card title for a referenced record: the
 * first mapped column's value, with the collection title and guid as fallbacks.
 * columnKeys are the api field's map keys in author order.
 */
export function APIFieldTitle(sourceTemplate: string, guid: string, columnKeys: string[]): $CancellablePromise<$models.APIFieldTitleResult> {
    return $Call.ByID(648809365, sourceTemplate, guid, columnKeys).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * FetchAPIFieldRow projects one source-collection record into a flat row
 * keyed by columnKeys. On error Row is nil and Kind is non-empty.
 */
export function FetchAPIFieldRow(sourceTemplate: string, guid: string, columnKeys: string[]): $CancellablePromise<$models.APIFieldRowResult> {
    return $Call.ByID(213094529, sourceTemplate, guid, columnKeys).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListCollectionItems returns a collection template's records (id + title +
 * filename) for record pickers such as the relation linker. Empty when the
 * template isn't a collection. Backend owns the list; the frontend renders it.
 */
export function ListCollectionItems(template: string): $CancellablePromise<$models.CollectionItem[]> {
    return $Call.ByID(299093919, template).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListCollectionTemplates returns the collection-enabled templates an
 * api-typed field can reference; the api-field editor's dropdown source.
 */
export function ListCollectionTemplates(): $CancellablePromise<$models.TemplateSummary[]> {
    return $Call.ByID(1984870392).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ResolveAPIFieldLink returns the formidable://<template>:<datafile> deep link
 * for a referenced record, so the form-side "Go to record" uses the same backend
 * builder as the rendered card.
 */
export function ResolveAPIFieldLink(sourceTemplate: string, guid: string): $CancellablePromise<$models.APIFieldLinkResult> {
    return $Call.ByID(2200325791, sourceTemplate, guid).then(($result: any) => {
        return $$createType6($result);
    });
}

// Private type creation functions
const $$createType0 = $models.APIFieldTitleResult.createFrom;
const $$createType1 = $models.APIFieldRowResult.createFrom;
const $$createType2 = $models.CollectionItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.TemplateSummary.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.APIFieldLinkResult.createFrom;
