// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound facade, surfacing only the picker-side
 * api-field readers. The rest of Manager stays internal: it's wiki-shaped
 * and the wiki HTTP server and api Handler read it directly. Narrow
 * per-need methods get added here one at a time.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * FetchAPIFieldRow projects one source-collection record into a flat row
 * keyed by columnKeys. On error Row is nil and Kind is non-empty.
 */
export function FetchAPIFieldRow(sourceTemplate: string, guid: string, columnKeys: string[]): $CancellablePromise<$models.APIFieldRowResult> {
    return $Call.ByID(213094529, sourceTemplate, guid, columnKeys).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListCollectionItems returns a collection template's records (id + title +
 * filename) for record pickers such as the relation linker. Empty when the
 * template isn't a collection. Backend owns the list; the frontend renders it.
 */
export function ListCollectionItems(template: string): $CancellablePromise<$models.CollectionItem[]> {
    return $Call.ByID(299093919, template).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListCollectionTemplates returns the collection-enabled templates an
 * api-typed field can reference; the api-field editor's dropdown source.
 */
export function ListCollectionTemplates(): $CancellablePromise<$models.TemplateSummary[]> {
    return $Call.ByID(1984870392).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * RefetchAPIFieldRow re-fetches the current row and returns it with the
 * Drift against stored; a nil/empty stored counts every non-nil column as drift.
 */
export function RefetchAPIFieldRow(sourceTemplate: string, guid: string, columnKeys: string[], stored: { [_ in string]?: any }): $CancellablePromise<$models.APIFieldRefetchResultDTO> {
    return $Call.ByID(189740832, sourceTemplate, guid, columnKeys, stored).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $models.APIFieldRowResult.createFrom;
const $$createType1 = $models.CollectionItem.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.TemplateSummary.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.APIFieldRefetchResultDTO.createFrom;
