// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound surface for the code formatter. One
 * method: Format(lang, src). The frontend CodeEditor calls this on its
 * Format button instead of running prettier in the webview, so the
 * YAML inside markdown frontmatter blocks gets a real parser pass
 * (yaml.v3) and doesn't depend on what survived the paste.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Format reformats src according to lang. Errors are returned as
 * strings via Wails - the frontend toasts ErrMalformed cases so the
 * user can fix the source rather than silently shipping broken YAML.
 */
export function Format(lang: string, src: string): $CancellablePromise<string> {
    return $Call.ByID(3409542880, lang, src);
}
