// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FieldSpec is the Wails-friendly subset of template.Field needed by the
 * CSV mapping UI. The dialog passes this from the template it already
 * has cached on the frontend, so the backend doesn't reload templates.
 */
export class FieldSpec {
    "key": string;
    "type": string;
    "label": string;
    "options": any[];

    /** Creates a new FieldSpec instance. */
    constructor($$source: Partial<FieldSpec> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("options" in $$source)) {
            this["options"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FieldSpec instance from a string or object.
     */
    static createFrom($$source: any = {}): FieldSpec {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField3_0($$parsedSource["options"]);
        }
        return new FieldSpec($$parsedSource as Partial<FieldSpec>);
    }
}

/**
 * PreviewResult is the parsed shape returned by Preview. Mirrors the JS
 * `{headers, rows, rowCount, error}` so frontend handlers don't need
 * to branch on shape.
 */
export class PreviewResult {
    "headers": string[];
    "rows": string[][];
    "rowCount": number;
    "error"?: string;

    /** Creates a new PreviewResult instance. */
    constructor($$source: Partial<PreviewResult> = {}) {
        if (!("headers" in $$source)) {
            this["headers"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("rowCount" in $$source)) {
            this["rowCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PreviewResult {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField0_0($$parsedSource["headers"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        return new PreviewResult($$parsedSource as Partial<PreviewResult>);
    }
}

/**
 * SuggestedMapping is one row of auto-suggested CSV → field assignments.
 * Empty FieldKey means "no auto-match found"; the user is expected to
 * pick a target manually (or leave it unmapped).
 */
export class SuggestedMapping {
    "header": string;
    "fieldKey": string;

    /** Creates a new SuggestedMapping instance. */
    constructor($$source: Partial<SuggestedMapping> = {}) {
        if (!("header" in $$source)) {
            this["header"] = "";
        }
        if (!("fieldKey" in $$source)) {
            this["fieldKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SuggestedMapping instance from a string or object.
     */
    static createFrom($$source: any = {}): SuggestedMapping {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SuggestedMapping($$parsedSource as Partial<SuggestedMapping>);
    }
}

/**
 * WriteResult mirrors the JS shape.
 */
export class WriteResult {
    "success": boolean;
    "error"?: string;

    /** Creates a new WriteResult instance. */
    constructor($$source: Partial<WriteResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WriteResult instance from a string or object.
     */
    static createFrom($$source: any = {}): WriteResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WriteResult($$parsedSource as Partial<WriteResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Array($$createType1);
