// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails surface over Manager. HTTP export endpoints (Epic 8
 * collections API) call the manager directly, so no handlers.go lives here.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyTransform runs one transform rule against a single cell value.
 * mode is "preview" or "storage"; only meaningful for split-table.
 */
export function ApplyTransform(value: string, rule: string, param: string, mode: string): $CancellablePromise<string> {
    return $Call.ByID(1798641220, value, rule, param, mode);
}

/**
 * BuildImportForms reconstructs entries from parsed CSV rows, the inverse of
 * Export. An aligned plan regroups the export's multiplied rows back into one
 * entry per group with its nested list/table rebuilt.
 */
export function BuildImportForms(plan: $models.ImportPlan, headers: string[], rows: string[][], fields: $models.FieldSpec[]): $CancellablePromise<$models.ImportForm[]> {
    return $Call.ByID(4214359296, plan, headers, rows, fields).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CoercePreview returns a display-shaped string for the typed value.
 */
export function CoercePreview(raw: string, fieldType: string, options: any[]): $CancellablePromise<string> {
    return $Call.ByID(3240398603, raw, fieldType, options);
}

/**
 * CoerceTableRows coerces a 2D string array (from a paste-data dialog on a
 * table field) into a 2D typed array matching the column specs. Dropdown
 * columns match by value or label.
 */
export function CoerceTableRows(cols: $models.TableColumn[], rows: string[][]): $CancellablePromise<any[][]> {
    return $Call.ByID(2925409190, cols, rows).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * CoerceValue returns the typed value Coerce would produce for a CSV
 * cell about to be written into a form field.
 */
export function CoerceValue(raw: string, fieldType: string, options: any[]): $CancellablePromise<any> {
    return $Call.ByID(3498704254, raw, fieldType, options);
}

/**
 * ExcludedFieldTypes returns the set of field types the import dialog
 * must hide from the target-field dropdown.
 */
export function ExcludedFieldTypes(): $CancellablePromise<string[]> {
    return $Call.ByID(3131073099).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Export resolves fields, lists forms, loads each, and builds the row grid.
 * The frontend then hands Rows to Write.
 */
export function Export(templateFilename: string, plan: $models.ExportPlan): $CancellablePromise<$models.ExportResult> {
    return $Call.ByID(2563447778, templateFilename, plan).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ExportSchema returns the default column plan, alignable fields, and source
 * options for an alignment choice, derived from the template's field schema.
 */
export function ExportSchema(templateFilename: string, alignSource: string): $CancellablePromise<$models.ExportSchema> {
    return $Call.ByID(4146878669, templateFilename, alignSource).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * FormatValue is the export-side counterpart to CoerceValue: turn a
 * stored typed value back into a CSV-friendly string.
 */
export function FormatValue(val: any, fieldType: string): $CancellablePromise<string> {
    return $Call.ByID(4136857020, val, fieldType);
}

/**
 * MappableFields filters out field types that cannot participate in
 * a CSV mapping (image, code, api, loopstart/loopstop).
 */
export function MappableFields(fields: $models.FieldSpec[]): $CancellablePromise<$models.FieldSpec[]> {
    return $Call.ByID(113676927, fields).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * MappableFieldsForTemplate returns the template's CSV-mappable field specs,
 * excluded types stripped backend-side.
 */
export function MappableFieldsForTemplate(templateFilename: string): $CancellablePromise<$models.FieldSpec[]> {
    return $Call.ByID(3036908716, templateFilename).then(($result: any) => {
        return $$createType8($result);
    });
}

export function Preview(filePath: string, delimiter: string): $CancellablePromise<$models.PreviewResult> {
    return $Call.ByID(1142599248, filePath, delimiter).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * PreviewExport returns the single data row the dialog shows under each
 * column, built from the template's first stored form.
 */
export function PreviewExport(templateFilename: string, plan: $models.ExportPlan): $CancellablePromise<$models.PreviewRowResult> {
    return $Call.ByID(617446806, templateFilename, plan).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * PreviewSheet returns the header + rows of one .xlsx sheet in the same shape
 * as Preview, so the dialog's mapping pipeline is identical for CSV and Excel.
 */
export function PreviewSheet(filePath: string, sheet: string): $CancellablePromise<$models.PreviewResult> {
    return $Call.ByID(1054972531, filePath, sheet).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * SheetNames lists the sheets of an .xlsx workbook, in workbook order, so the
 * import dialog can offer a sheet picker for Excel sources.
 */
export function SheetNames(filePath: string): $CancellablePromise<string[]> {
    return $Call.ByID(2199450293, filePath).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * SuggestMappings is the auto-mapper for the import dialog. Empty
 * FieldKey in a row means "no match found".
 */
export function SuggestMappings(headers: string[], fields: $models.FieldSpec[]): $CancellablePromise<$models.SuggestedMapping[]> {
    return $Call.ByID(1554962185, headers, fields).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * TransformRules returns the ordered list of supported rule keys for
 * the transform-selector dropdown. Frontend resolves labels via i18n.
 */
export function TransformRules(): $CancellablePromise<string[]> {
    return $Call.ByID(1932744663).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Write(filePath: string, rows: string[][], delimiter: string, quoteAll: boolean): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(614530563, filePath, rows, delimiter, quoteAll).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * WriteExcel serializes the export grid to an .xlsx file with one sheet, the
 * Excel-output counterpart to Write.
 */
export function WriteExcel(filePath: string, rows: string[][], sheet: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(3855575998, filePath, rows, sheet).then(($result: any) => {
        return $$createType13($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ImportForm.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $models.ExportResult.createFrom;
const $$createType6 = $models.ExportSchema.createFrom;
const $$createType7 = $models.FieldSpec.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.PreviewResult.createFrom;
const $$createType10 = $models.PreviewRowResult.createFrom;
const $$createType11 = $models.SuggestedMapping.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.WriteResult.createFrom;
