// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the api layer over Manager. Methods map to the old Electron
 * `window.api.csv.*` IPC group:
 *   - csv-preview     → Preview
 *   - csv-write       → Write
 * 
 * `csv-import-row` is intentionally NOT in this module - the Electron
 * app already routed it to formManager.saveForm. Storage import (F-302)
 * will own that route.
 * 
 * Wails-only: HTTP export endpoints (Epic 8 collections API) call into
 * this manager directly; no `handlers.go` lives here.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyTransform runs one transform rule against a single cell value.
 * mode is "preview" or "storage"; only meaningful for split-table.
 */
export function ApplyTransform(value: string, rule: string, param: string, mode: string): $CancellablePromise<string> {
    return $Call.ByID(1798641220, value, rule, param, mode);
}

/**
 * BuildPreviewRows is the export-dialog's live preview helper. It runs
 * the same row-building pipeline as Export but on caller-supplied
 * entries (typically one) - no storage round trip. Always includes the
 * header row at index 0.
 */
export function BuildPreviewRows(plan: $models.ExportPlan, entries: { [_ in string]?: any }[], fields: $models.FieldSpec[]): $CancellablePromise<string[][]> {
    return $Call.ByID(1765116917, plan, entries, fields).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CoercePreview returns a display-shaped string for the typed value.
 */
export function CoercePreview(raw: string, fieldType: string, options: any[]): $CancellablePromise<string> {
    return $Call.ByID(3240398603, raw, fieldType, options);
}

/**
 * CoerceTableRows coerces a 2D string array (from a paste-data dialog
 * on a table field) into a 2D typed array matching the column specs.
 * Reuses Coerce per cell; dropdown columns match by value or label.
 */
export function CoerceTableRows(cols: $models.TableColumn[], rows: string[][]): $CancellablePromise<any[][]> {
    return $Call.ByID(2925409190, cols, rows).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * CoerceValue returns the typed value Coerce would produce for a CSV
 * cell about to be written into a form field.
 */
export function CoerceValue(raw: string, fieldType: string, options: any[]): $CancellablePromise<any> {
    return $Call.ByID(3498704254, raw, fieldType, options);
}

/**
 * ExcludedFieldTypes returns the set of field types the import dialog
 * must hide from the target-field dropdown.
 */
export function ExcludedFieldTypes(): $CancellablePromise<string[]> {
    return $Call.ByID(3131073099).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Export is the one-call export pipeline: list forms, load each, build
 * the row grid. The frontend then hands Rows to Write(filePath, ...).
 */
export function Export(templateFilename: string, plan: $models.ExportPlan, fields: $models.FieldSpec[]): $CancellablePromise<$models.ExportResult> {
    return $Call.ByID(2563447778, templateFilename, plan, fields).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * FormatValue is the export-side counterpart to CoerceValue: turn a
 * stored typed value back into a CSV-friendly string.
 */
export function FormatValue(val: any, fieldType: string): $CancellablePromise<string> {
    return $Call.ByID(4136857020, val, fieldType);
}

/**
 * MappableFields filters out field types that cannot participate in
 * a CSV mapping (image, code, api, loopstart/loopstop).
 */
export function MappableFields(fields: $models.FieldSpec[]): $CancellablePromise<$models.FieldSpec[]> {
    return $Call.ByID(113676927, fields).then(($result: any) => {
        return $$createType6($result);
    });
}

export function Preview(filePath: string, delimiter: string): $CancellablePromise<$models.PreviewResult> {
    return $Call.ByID(1142599248, filePath, delimiter).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * SuggestMappings is the auto-mapper for the import dialog. Empty
 * FieldKey in a row means "no match found".
 */
export function SuggestMappings(headers: string[], fields: $models.FieldSpec[]): $CancellablePromise<$models.SuggestedMapping[]> {
    return $Call.ByID(1554962185, headers, fields).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * TransformRules returns the ordered list of supported rule keys for
 * the transform-selector dropdown. Frontend resolves labels via i18n.
 */
export function TransformRules(): $CancellablePromise<string[]> {
    return $Call.ByID(1932744663).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Write(filePath: string, rows: string[][], delimiter: string): $CancellablePromise<$models.WriteResult> {
    return $Call.ByID(614530563, filePath, rows, delimiter).then(($result: any) => {
        return $$createType10($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.ExportResult.createFrom;
const $$createType5 = $models.FieldSpec.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.PreviewResult.createFrom;
const $$createType8 = $models.SuggestedMapping.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.WriteResult.createFrom;
