// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Branches summarizes local branches plus the active one.
 */
export class Branches {
    /**
     * Current is the active branch name; "" when detached.
     */
    "current": string;
    "locals": string[];

    /** Creates a new Branches instance. */
    constructor($$source: Partial<Branches> = {}) {
        if (!("current" in $$source)) {
            this["current"] = "";
        }
        if (!("locals" in $$source)) {
            this["locals"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Branches instance from a string or object.
     */
    static createFrom($$source: any = {}): Branches {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("locals" in $$parsedSource) {
            $$parsedSource["locals"] = $$createField1_0($$parsedSource["locals"]);
        }
        return new Branches($$parsedSource as Partial<Branches>);
    }
}

/**
 * CloneOptions describes a clone request. URL and Dest are required;
 * Branch picks an initial checkout (empty = remote's default HEAD).
 * 
 * PAT is the Personal Access Token used as the password in HTTP Basic
 * auth (with username "x-access-token" — the GitHub-PAT convention,
 * also accepted by Gitea/GitLab/Bitbucket as long as the username is
 * non-empty). Empty PAT means anonymous (public repos / SSH).
 * 
 * IMPORTANT: PAT is read-only at the call site and never persisted by
 * the manager. The frontend keeps it transient — pasted into the
 * clone form, sent over the Wails bridge once, and discarded as soon
 * as the response returns. SSH-based auth lives in a follow-up.
 */
export class CloneOptions {
    "url": string;
    "dest": string;
    "branch": string;
    "pat": string;

    /** Creates a new CloneOptions instance. */
    constructor($$source: Partial<CloneOptions> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("dest" in $$source)) {
            this["dest"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("pat" in $$source)) {
            this["pat"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloneOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): CloneOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloneOptions($$parsedSource as Partial<CloneOptions>);
    }
}

/**
 * CloneResult is the success envelope: the worktree we cloned into
 * and the commit HEAD now points at. The frontend uses Dest to flip
 * git_root once a clone completes.
 */
export class CloneResult {
    "dest": string;
    "head": string;

    /** Creates a new CloneResult instance. */
    constructor($$source: Partial<CloneResult> = {}) {
        if (!("dest" in $$source)) {
            this["dest"] = "";
        }
        if (!("head" in $$source)) {
            this["head"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloneResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CloneResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloneResult($$parsedSource as Partial<CloneResult>);
    }
}

/**
 * Commit is a JSON-friendly view of a git commit. Time is RFC3339
 * in the commit author's stored offset.
 */
export class Commit {
    "hash": string;
    "short": string;
    "author": string;
    "email": string;
    "time": string;
    "subject": string;

    /** Creates a new Commit instance. */
    constructor($$source: Partial<Commit> = {}) {
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("short" in $$source)) {
            this["short"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = "";
        }
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Commit instance from a string or object.
     */
    static createFrom($$source: any = {}): Commit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Commit($$parsedSource as Partial<Commit>);
    }
}

/**
 * Remote is one configured remote with all its push/fetch URLs.
 */
export class Remote {
    "name": string;
    "urls": string[];

    /** Creates a new Remote instance. */
    constructor($$source: Partial<Remote> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("urls" in $$source)) {
            this["urls"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Remote instance from a string or object.
     */
    static createFrom($$source: any = {}): Remote {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("urls" in $$parsedSource) {
            $$parsedSource["urls"] = $$createField1_0($$parsedSource["urls"]);
        }
        return new Remote($$parsedSource as Partial<Remote>);
    }
}

/**
 * RemoteInfo wraps the configured remotes for the repo.
 */
export class RemoteInfo {
    "remotes": Remote[];

    /** Creates a new RemoteInfo instance. */
    constructor($$source: Partial<RemoteInfo> = {}) {
        if (!("remotes" in $$source)) {
            this["remotes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteInfo {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("remotes" in $$parsedSource) {
            $$parsedSource["remotes"] = $$createField0_0($$parsedSource["remotes"]);
        }
        return new RemoteInfo($$parsedSource as Partial<RemoteInfo>);
    }
}

/**
 * Status is a JSON-friendly snapshot of a repository's working tree
 * + HEAD position. Mirrors the subset of `git status` that the
 * Collaboration overview surfaces; richer info (per-file diff hunks
 * etc.) lives in dedicated calls.
 */
export class Status {
    /**
     * Branch is the current local branch name (e.g. "main").
     * Empty when HEAD is detached.
     */
    "branch": string;

    /**
     * Tracking is the configured upstream ref name (e.g.
     * "refs/remotes/origin/main"), or "" if none / detached.
     */
    "tracking": string;

    /**
     * Detached reports HEAD-not-on-a-branch.
     */
    "detached": boolean;

    /**
     * Clean is true when the worktree has no modifications,
     * untracked files, or staged changes.
     */
    "clean": boolean;
    "modified": string[];
    "untracked": string[];
    "staged": string[];
    "deleted": string[];
    "renamed": string[];
    "conflicted": string[];

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("tracking" in $$source)) {
            this["tracking"] = "";
        }
        if (!("detached" in $$source)) {
            this["detached"] = false;
        }
        if (!("clean" in $$source)) {
            this["clean"] = false;
        }
        if (!("modified" in $$source)) {
            this["modified"] = [];
        }
        if (!("untracked" in $$source)) {
            this["untracked"] = [];
        }
        if (!("staged" in $$source)) {
            this["staged"] = [];
        }
        if (!("deleted" in $$source)) {
            this["deleted"] = [];
        }
        if (!("renamed" in $$source)) {
            this["renamed"] = [];
        }
        if (!("conflicted" in $$source)) {
            this["conflicted"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("modified" in $$parsedSource) {
            $$parsedSource["modified"] = $$createField4_0($$parsedSource["modified"]);
        }
        if ("untracked" in $$parsedSource) {
            $$parsedSource["untracked"] = $$createField5_0($$parsedSource["untracked"]);
        }
        if ("staged" in $$parsedSource) {
            $$parsedSource["staged"] = $$createField6_0($$parsedSource["staged"]);
        }
        if ("deleted" in $$parsedSource) {
            $$parsedSource["deleted"] = $$createField7_0($$parsedSource["deleted"]);
        }
        if ("renamed" in $$parsedSource) {
            $$parsedSource["renamed"] = $$createField8_0($$parsedSource["renamed"]);
        }
        if ("conflicted" in $$parsedSource) {
            $$parsedSource["conflicted"] = $$createField9_0($$parsedSource["conflicted"]);
        }
        return new Status($$parsedSource as Partial<Status>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Remote.createFrom;
const $$createType2 = $Create.Array($$createType1);
