// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound surface of the Git collaboration
 * backend. Wraps Manager and adds one cross-cutting concern: when
 * the frontend calls Push or Fetch without a PAT, the Service
 * auto-resolves it from the OS keychain via the injected
 * CredentialReader.
 * 
 * The keychain is intentionally NOT exposed to the frontend (see
 * the credential.Service comment) so secrets never round-trip
 * through the Wails bridge. That makes the Service the only layer
 * allowed to read the PAT — Manager itself stays transport-neutral
 * and unaware of credential storage.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Branches(path: string): $CancellablePromise<$models.Branches | null> {
    return $Call.ByID(141254074, path).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Clone(opts: $models.CloneOptions): $CancellablePromise<$models.CloneResult | null> {
    return $Call.ByID(3869084983, opts).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Commit(opts: $models.CommitOptions): $CancellablePromise<$models.CommitResult | null> {
    return $Call.ByID(2190917583, opts).then(($result: any) => {
        return $$createType5($result);
    });
}

export function Discard(opts: $models.DiscardOptions): $CancellablePromise<void> {
    return $Call.ByID(106030516, opts);
}

/**
 * Fetch refreshes remote-tracking refs. When opts.PAT is empty, the
 * Service auto-fills it from the keychain entry for the repo's
 * "origin" URL — frontend doesn't need to (and can't) read the
 * secret itself.
 */
export function Fetch(opts: $models.FetchOptions): $CancellablePromise<$models.FetchResult | null> {
    return $Call.ByID(3289441430, opts).then(($result: any) => {
        return $$createType7($result);
    });
}

export function IsGitRepo(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(685777186, path);
}

export function Log(path: string, limit: number): $CancellablePromise<$models.Commit[]> {
    return $Call.ByID(3722488696, path, limit).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * Push sends commits to the named remote. Same keychain auto-fill
 * behavior as Fetch.
 */
export function Push(opts: $models.PushOptions): $CancellablePromise<$models.PushResult | null> {
    return $Call.ByID(2431245618, opts).then(($result: any) => {
        return $$createType11($result);
    });
}

export function RemoteInfo(path: string): $CancellablePromise<$models.RemoteInfo | null> {
    return $Call.ByID(1356102196, path).then(($result: any) => {
        return $$createType13($result);
    });
}

export function RepoRoot(path: string): $CancellablePromise<string> {
    return $Call.ByID(651993186, path);
}

export function Status(path: string): $CancellablePromise<$models.Status | null> {
    return $Call.ByID(3686552508, path).then(($result: any) => {
        return $$createType15($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Branches.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.CloneResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.CommitResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.FetchResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.Commit.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.PushResult.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $models.RemoteInfo.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $models.Status.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
