// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Kind identifies a widget's display role. Closed enum: adding one is a
 * deliberate package change with a matching frontend component.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * KindProgressBar renders a progress bar fed by RunBarEvent; Total 0 is
     * indeterminate.
     */
    KindProgressBar = "progressbar",

    /**
     * KindStatusMessage renders a single-line label fed by RunStatusEvent.
     */
    KindStatusMessage = "statusmessage",

    /**
     * KindChart renders an interactive chart: it owns the stat-object and
     * chart-shape pickers and drives the Lua call itself, unlike the
     * event-fed kinds.
     */
    KindChart = "chart",
};

/**
 * Widget is one entry in a plugin's form.json (sharing the array with template
 * Fields; the frontend dispatches on "kind" vs Field's "type"). Array position
 * is render order. ID is the editor's stable handle, not a Lua route.
 */
export class Widget {
    "id": string;
    "kind": Kind;
    "label"?: string;

    /** Creates a new Widget instance. */
    constructor($$source: Partial<Widget> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = Kind.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Widget instance from a string or object.
     */
    static createFrom($$source: any = {}): Widget {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Widget($$parsedSource as Partial<Widget>);
    }
}
