// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Cursor is the per-backend sync watermark.
 * Ts marks "everything older has reached this backend"; Version is the
 * remote-side identifier (git commit hash, gigot version) at that ts.
 */
export class Cursor {
    "ts": string;
    "version": string;

    /** Creates a new Cursor instance. */
    constructor($$source: Partial<Cursor> = {}) {
        if (!("ts" in $$source)) {
            this["ts"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Cursor instance from a string or object.
     */
    static createFrom($$source: any = {}): Cursor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Cursor($$parsedSource as Partial<Cursor>);
    }
}

/**
 * CursorMap is keyed by backend ("git", "gigot").
 */
export type CursorMap = { [_ in string]?: Cursor };

/**
 * Entry is one journal record. Sync entries fill Backend/Version/...;
 * file-op entries fill Path/Bytes. Encoded as JSONL on disk.
 */
export class Entry {
    "ts": string;
    "op": string;
    "path"?: string;
    "bytes"?: number;
    "backend"?: string;
    "version"?: string;
    "pushed"?: number;
    "pulled"?: number;

    /** Creates a new Entry instance. */
    constructor($$source: Partial<Entry> = {}) {
        if (!("ts" in $$source)) {
            this["ts"] = "";
        }
        if (!("op" in $$source)) {
            this["op"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     */
    static createFrom($$source: any = {}): Entry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Entry($$parsedSource as Partial<Entry>);
    }
}

/**
 * PendingChange is one entry in PendingResult.Paths.
 */
export class PendingChange {
    "path": string;
    "op": string;

    /** Creates a new PendingChange instance. */
    constructor($$source: Partial<PendingChange> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("op" in $$source)) {
            this["op"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PendingChange instance from a string or object.
     */
    static createFrom($$source: any = {}): PendingChange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PendingChange($$parsedSource as Partial<PendingChange>);
    }
}

/**
 * PendingResult is the shape returned by Pending() and exposed to the
 * frontend. Count is always equal to len(Paths) - kept as a convenience
 * so JS callers don't need to call paths.length.
 */
export class PendingResult {
    "count": number;
    "paths": PendingChange[];

    /** Creates a new PendingResult instance. */
    constructor($$source: Partial<PendingResult> = {}) {
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("paths" in $$source)) {
            this["paths"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PendingResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PendingResult {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField1_0($$parsedSource["paths"]);
        }
        return new PendingResult($$parsedSource as Partial<PendingResult>);
    }
}

// Private type creation functions
const $$createType0 = PendingChange.createFrom;
const $$createType1 = $Create.Array($$createType0);
