// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound facade for the render module. Vue calls
 * these to drive the Storage workspace's Render button.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListHelpers - the catalog of every Handlebars helper this module
 * registers, for the Information panel's "Render helpers reference".
 * Static data (no Manager state read); returned as a fresh slice the
 * frontend can sort/filter freely.
 */
export function ListHelpers(): $CancellablePromise<$models.HelperDescriptor[]> {
    return $Call.ByID(3874415751).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RenderForm - Handlebars markdown + sanitized HTML for one
 * (template, datafile) pair. Empty datafile renders defaults.
 */
export function RenderForm(templateName: string, datafile: string): $CancellablePromise<$models.Result | null> {
    return $Call.ByID(679525684, templateName, datafile).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * RenderFullHTML - self-contained HTML document (DOCTYPE + head + body)
 * with the formidable-prose stylesheet inlined. Used by the storage
 * workspace's "Copy HTML" action so what the user pastes into a .html
 * file renders identically to the in-app preview.
 */
export function RenderFullHTML(templateName: string, datafile: string): $CancellablePromise<string> {
    return $Call.ByID(3308919126, templateName, datafile);
}

/**
 * RenderHTML - re-render arbitrary markdown (Vue's editor preview).
 */
export function RenderHTML(markdown: string): $CancellablePromise<string> {
    return $Call.ByID(902651679, markdown);
}

/**
 * RenderMarkdown - Handlebars stage only. Useful when Vue wants to let
 * the user edit the intermediate markdown before HTML rendering.
 */
export function RenderMarkdown(templateName: string, datafile: string): $CancellablePromise<string> {
    return $Call.ByID(2775873335, templateName, datafile);
}

/**
 * RenderSlideBlockHTML renders one slide block's content to HTML, so the canvas
 * editor shows the same output the deck will render. content is the block's
 * value (string, 2D array, etc.); templateName scopes image URLs.
 */
export function RenderSlideBlockHTML(templateName: string, kind: string, content: any): $CancellablePromise<string> {
    return $Call.ByID(4009042845, templateName, kind, content);
}

/**
 * ValidateMarkdownTemplate parses the given Handlebars source and
 * reports parse errors plus helper-name warnings. Cheap enough to call
 * on every keystroke (debounced from the frontend).
 */
export function ValidateMarkdownTemplate(src: string): $CancellablePromise<$models.ValidationReport> {
    return $Call.ByID(1954975287, src).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.HelperDescriptor.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Result.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.ValidationReport.createFrom;
