// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExportService is the Wails surface for the offline-wiki bundle export. It
 * holds the same Handler the HTTP server uses (so pages render identically) plus
 * a byte-saver, keeping the binary zip off the Wails IPC boundary.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExportPack builds the offline-wiki bundle, wraps it as a branded .bundle
 * (manifest + payload, sealed with password when non-empty), and writes it to
 * path. selections maps a template filename to the deck values to include
 * (empty = all decks for a presentation; ignored for a document). Returns the
 * stems skipped (a template that failed to load, or a presentation with no
 * exportable decks).
 */
export function ExportPack(selections: { [_ in string]?: string[] }, path: string, password: string, meta: $models.ExportMeta): $CancellablePromise<string[]> {
    return $Call.ByID(49834387, selections, path, password, meta).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ResolveDependencies expands the given template picks into the full set the
 * bundle needs (the picks plus every template they link to, transitively) so the
 * frontend can auto-toggle the related templates on and explain why. The backend
 * also applies this expansion at export time (ExportPack), so a bundle is
 * self-contained even if the caller skips this call; this just surfaces it to the
 * UI ahead of the export.
 */
export function ResolveDependencies(selected: string[]): $CancellablePromise<$models.DependencyResult> {
    return $Call.ByID(2103155701, selected).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.DependencyResult.createFrom;
